### ISSUE TITLE
Missing task to start gluster-blockd

### ISSUE THREAD

**Issue by eddiechen** [openshift/openshift-ansible#10308]
#### Description

Provide a brief description of your issue here. For example:

> On a multi master install, if the first master goes down we can no
> longer scaleup the cluster with new nodes or masters.

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`

If you're operating from a **git clone**:

* The output of `git describe`

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

```
VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
2. [step 2]

##### Expected Results
Describe what you expected to happen.

```
Example command and output or error messages
Charro Gruver from ODFL was testing gluster-block deployment and unable to create new block devices for his Openshift environment. Upon troubleshooting, he realized gluster-blockd was not running. Therefore, it was not responding to block LUN creation requests. He was able to fix it manually by running "systemctl start gluster-blockd" in Openshift.
```

##### Observed Results
Describe what is actually happening.

```
Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)

##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```
He believes the following task needed to be added to this Ansible playbook. He was able to test and confirm the fix:

- name: Start gluster-blockd (external)
  service:
    name: gluster-blockd
    state: started
    enabled: yes
  delegate_to: "{{ item }}"
  with_items: "{{ glusterfs_nodes | default([]) }}"
  when:
  - not glusterfs_is_native | bool

**Comment by cgruver** [comment]
@eddiechen Thanks for opening this issue.

Here is some additional info.

I built an Origin 3.10 cluster and pre-provisioned 5 Centos 7.5 nodes to serve as an Independent Glusterfs cluster for my Origin environment.

I executed the playbook to install glusterfs with:

openshift_storage_glusterfs_is_native=false
openshift_storage_glusterfs_heketi_is_native=true
openshift_storage_glusterfs_storageclass=true
openshift_storage_glusterfs_block_deploy=true
openshift_storage_glusterfs_block_storageclass=true
plus other options...

The glusterfs install completed successfully.  

Glusterfs claims would deploy fine.  However, Gluster-block claims would be stuck in a pending state.

The errors being thrown by Heketi and the Block-Provisioner were very similar to the issue reported in: 
https://bugzilla.redhat.com/show_bug.cgi?id=1630117

This situation is repeatable.

After some digging I noticed that buried at the beginning of the Heketi errors was a notice that it was getting a connection refused from cluster-blockd.  I checked the glusterfs nodes and confirmed that cluster-blockd was not enabled.

I searched through the playbooks for glusterfs install and noticed that they do not attempt to enable or start cluster-blockd.  So, I made the following modification to glusterfs_common.yml to add a task to start cluster-blockd.
.....
- import_tasks: glusterfs_deploy.yml
  when: glusterfs_is_native
 
- name: Start glusterd (external)
  service:
    name: glusterd
    state: started
    enabled: yes
  delegate_to: "{{ item }}"
  with_items: "{{ glusterfs_nodes | default([]) }}"
  when:
  - not glusterfs_is_native | bool
 
- import_tasks: heketi_setup.yml
  when: glusterfs_heketi_is_native
 
- name: Start gluster-blockd (external)
  service:
    name: gluster-blockd
    state: started
    enabled: yes
  delegate_to: "{{ item }}"
  with_items: "{{ glusterfs_nodes | default([]) }}"
  when:
  - not glusterfs_is_native | bool
  - glusterfs_block_deploy
 
…….

I destroyed my Origin 3.10 cluster and rebuilt it including the modified playbook.

The issue was resolved.

Another work around is to enable and start glusterd and cluster-blockd on your Glusterfs nodes before running the glusterfs playbook.
