### ISSUE TITLE
Support migrating from non-HA deployment to HA

### ISSUE THREAD

**Issue by rrati** [openshift/openshift-ansible#1031]
The installer should support upgrading an existing deployment from non-HA to an HA deployment.

**Comment by detiber** [comment]
@rrati, I suspect it will be a while for this still.

The first major issue us rekeying certs for the lb host.

Second is updating all references to the master URL and master public URL through the clustr.

Third is migration of etcd data from the embedded etcd to an external ha etcd.

We have been talking about using an external etcd even for single master deployments, so that should make #3 a bit easier though.

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit
