### ISSUE TITLE
Openshift 3.11 Cluster console issue

### ISSUE THREAD

**Issue by ZrytyADHD** [openshift/openshift-ansible#10930]
#### Description

I cant access the Cluster Console from web site
I go in Menu-> Service Catalog->Cluster Console

[https://ibb.co/hV0dwc2](url)

and get "Page cannot be found".
Choosing this menu option redirect me to https://console. **My Hostname**

##### Version of installed components

ansible --version 2.6.5
docker -- version 1.3.1

##### Steps To Reproduce

git clone https://github.com/openshift/openshift-ansible
cd openshift-ansible
sudo ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
sudo ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml

##### Expected Results
Installed and working enviroment to deploy apps.

Access to Cluster console thru website.

##### Observed Results
Error: 
Page cannot be found after trying to access Cluster Console thru web console

##### Additional Information

Enviroment: Rhel 7.5 with minimum install and completed all dependiecies for install OKD Openshift
Reinstalling whole enviroment from scratch 2 times and get the same effect.

**Comment by ZrytyADHD** [comment]
Ok i got it to make it work we need to add record to DNS server.

**Comment by jblbn** [comment]
> 
> 
> Ok i got it to make it work we need to add record to DNS server.

Hi could you describe your fix in more detail at all please? Thanks

**Comment by ZrytyADHD** [comment]
> 
> 
> > Ok i got it to make it work we need to add record to DNS server.
> 
> Hi could you describe your fix in more detail at all please? Thanks

Of course.
I'm using Windows server 2016 with AD and DNS role installed on it.
To make cluster console run properly 👍 go to DNS
find Forward Lookup Zones
find my domain suffix for example nn.pl in there i choose to create new host (A or AAAA) enter settings:
Hostname : console.apps beacause my full adress which i wan to get work is console.apps.nn.pl
Why without nn.pl because dns add this for me. Try to enter host name to match adress of your cluster console  you can check it in Full qualifield domain name (FQDN) field below
Example if your cluster console adress is console.extras.df.com you need to enter console.extras such as hostname.
In ip adress field enter the adres of you master node.

**Comment by jblbn** [comment]
Thanks for your feedback. Had a very similar issue but resolved in the logs there were no DNS lookup failures, as they were all direct IP's. We ended up:
- Uninstalling entire platform  
- Removing all docker images and containers  
- Updating all yum packages  
- Rebooting server  
- Reinstalling from scratch  
- Running update.yml  
No idea of root cause but very odd for a brand new platform :/ 
Cheers

**Comment by alokhom** [comment]
"I cant access the Cluster Console from web site" this is because the web request is not going to place where the cluster console is web hosted.... 
well one needs to mention cluster console ip and console.apps.subdomain.domain.com on the hostfile of the requesting machine so that the traffic is correctly routed to cluster console ip (infra node ip)

**Comment by Nurlan199206** [comment]
i had same issue i just add to `/etc/hosts` infra node IP.

`console.apps.example.com YOUR INFRA NODE IP`

![Снимок экрана 2020-08-16 в 17 14 41](https://user-images.githubusercontent.com/22808731/90333023-06edb280-dfe4-11ea-9f2b-3c2cbe35862d.png)
