### ISSUE TITLE
Oauth Proxy verifies token through public master hostname

### ISSUE THREAD

**Issue by jocelynthode** [openshift/openshift-ansible#11137]
#### Description

On multi-master installation with the openshift prometheus stack and EFK stack deployed, login to kibana or cluster console fails due to token verification timeout. I did not find any varible to configure the oauth authorization server

##### Version
```
openshift v3.11.0+1c3e643-87
kubernetes v1.11.0+d4cacc0
```

##### Steps To Reproduce
1. Install Openshift 3.11 with EFK stack and cluster console enabled and nodes with no access to internet
2. Try to login on the cluster console

##### Expected Results
Login should be successful and token verification should use master internal ip or hostname

##### Observed Results
Login fails due to a timeout when console pods try to contact the openshift master through the public hostname

```
$ curl https://172.30.0.1/.well-known/oauth-authorization-server
{
  "issuer": "https://<PUBLIC_MASTER_HOSTNAME>",
  "authorization_endpoint": "https://<PUBLIC_MASTER_HOSTNAME>/oauth/authorize",
  "token_endpoint": "https://<PUBLIC_MASTER_HOSTNAME>/oauth/token",
  "scopes_supported": [
    "user:check-access",
    "user:full",
    "user:info",
    "user:list-projects",
    "user:list-scoped-projects"
  ],
  "response_types_supported": [
    "code",
    "token"
  ],
  "grant_types_supported": [
    "authorization_code",
    "implicit"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ]
}
```

**Comment by vrutkovs** [comment]
>token verification should use master internal ip or hostname

Is there a reason to use internal master IP? Public master is usually a LB for various masters, so sticking to internal master address might not work on HA install

/cc @jcantrill

**Comment by jocelynthode** [comment]
@vrutkovs I'm not sure I understand what you're saying.

We have the following variables defined for the master hostnames:
```
openshift_master_cluster_method=native
openshift_master_cluster_hostname=openshift-internal.example.net
openshift_master_cluster_public_hostname=openshift.example.com
```
Since we have a multi master setup, both are load-balanced (the internal on layer 4 and external on layer 7). The DNS for the internal resolves to an internal IP which is accessible by the Openshift nodes in the cluster.

The DNS for the external resolves to a public IP which Openshift nodes cannot access as they do not have access to internet.

When pods in the cluster try to verify the token on the oauth server I would like for them to user the internal DNS as they can access this IP.

**Comment by vrutkovs** [comment]
>The DNS for the external resolves to a public IP which Openshift nodes cannot access as they do not have access to internet.

Ah, I see. That makes sense, yes. Let see if logging folks don't mind changing that

**Comment by jocelynthode** [comment]
@vrutkovs I not only encounter this problem on logging but on the cluster console and grafana dashboard for the prometheus monitoring stack

**Comment by jcantrill** [comment]
> > The DNS for the external resolves to a public IP which Openshift nodes cannot access as they do not have access to internet.
> 
> Ah, I see. That makes sense, yes. Let see if logging folks don't mind changing that

I have no objections as long as it continues to function correctly

**Comment by patlachance** [comment]
@jocelynthode: Your issue seem very similar to the one I have for months. 
- openshift_master_cluster_public_hostname resolves to a public internet IP address
- openshift cluster don't have direct internet access, network traffic need to go thru browsing proxy
- unable to connect to services embedding oauth-proxy

***For Kibana, the problem is that:***
- http_proxy variables are not propagated to the oauth-proxy container in the various pods where it is used
- the oauth-proxy component doesn't handle http_proxy environment variable (see https://github.com/openshift/oauth-proxy/issues/71 for more information about the issue and related PR https://github.com/openshift/oauth-proxy/pull/96.)

The good news is that the PR was merged and image registry.redhat.io/openshift3/oauth-proxy:v3.11.82 now handle http_proxy as expected.

The bad news is that the openshift-ansible-roles haven't been patched to propagate http_proxy variables. I just created a PR to fix it (https://github.com/openshift/openshift-ansible/pull/11317)

***For the cluster console***

Issue is still related to missing http_proxy handling in the custom &http.Transport created in the auth/auth.go http client (same as issue with oauth-proxy above).
 
See https://github.com/openshift/console/issues/1248 and related PR https://github.com/openshift/console/pull/1249

My custom image is available on Docker hub if you want to give it a try: docker.io/oip-rnd/openshift-console:pr-1249

***For Cluster Monitoring Operator***
Again, http_proxy environment variales are not propagated. As a quick workaround, you can patch the deployments generated by the operator with commands similar to

```
PROXY_HOSTNAME="<proxy_hostname>"
PROXY_PORT="<proxy_port>"
NO_PROXY="localhost,.localdomain,127.0.0.1,169.254.169.254,172.30.0.1,.local,.priv,.svc,.cluster.local,.elb.amazonaws.com,.internal,internal-openshift-master.**<private_dns_domain>**"

ansible masters[0] -b -m shell -a "oc -n openshift-monitoring set env deployment/grafana -c grafana-proxy http_proxy=http://${PROXY_HOSTNAME}:${PROXY_PORT}/"
ansible masters[0] -b -m shell -a "oc -n openshift-monitoring set env deployment/grafana -c grafana-proxy https_proxy=http://${PROXY_HOSTNAME}:${PROXY_PORT}/"
ansible masters[0] -b -m shell -a "oc -n openshift-monitoring set env deployment/grafana -c grafana-proxy no_proxy=${NO_PROXY}"
ansible masters[0] -b -m shell -a "oc -n openshift-monitoring set env statefulset/prometheus-k8s -c prometheus-proxy http_proxy=http://${PROXY_HOSTNAME}:${PROXY_PORT}/"
ansible masters[0] -b -m shell -a "oc -n openshift-monitoring set env statefulset/prometheus-k8s -c prometheus-proxy https_proxy=http://${PROXY_HOSTNAME}:${PROXY_PORT}/"
ansible masters[0] -b -m shell -a "oc -n openshift-monitoring set env statefulset/prometheus-k8s -c prometheus-proxy no_proxy=${NO_PROXY}"
```

**Comment by parametriq** [comment]
This issue exists for any multi-master + load-balancer setup from what I can see, not just http proxy (LB behind firewall/NAT at least, like here: https://github.com/myllynen/openshift-ha-load-balancer). I cannot believe it is rather stale and overlooked currently. Oauth in all containers is broken, gives 504 gateway timeout errors. Cluster console, Prometheus and Kibana auth never succeeds.

Moreover, after installing Maistra/Istio on the cluster I get the same situation when trying to login to Jaeger, therefore its integration with the rest of the setup fails with errors. I was able to dodge the problem for Kiali's webpage only because certain options exist allowing simple login/pass auth... 

The suggested workaround above is surely better than nothing, but is rather time-consuming and partial(sorry, I think very few people would like to go fix every container image that has oauth implemented just to find out this change is not even yet supported). Is there no cluster-wide solution? For example, documentation points to /etc/origin/master/master-config.yaml files located on the master nodes for manual configuration of already installed cluster. This here PDF mentions configurable oauth parameters on page 158, Table 7.11: https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/pdf/configuring_clusters/OpenShift_Container_Platform-3.11-Configuring_Clusters-en-US.pdf  Can this be of any help or those are only responsible for web console(which works fine BTW)? At any rate, I wasn't able to find an example of how to properly use production-like configuration where public IP of HA load balancer is behind firewall, NAT, http proxy or in a separate VLAN from internal IP and Openshift cluster itself & OAuth requests from containers would still be re-routed as intended.

Usual tinkering with DNS, setting openshift_master_cluster_hostname and openshift_master_cluster_public_hostname variables in inventory file is clearly not enough, any push in the right direction would be highly appreciated.

**Comment by Boran** [comment]
Hi, I think I've been hit with the same, issue.
3 masters behind a LB for the public API, cert signed by an Internal CA.
Access to the main web interface in https with the public API address works fine, but not the cluster console or prometheus.

In the pods logs for openshift-console, it complains about the internal CA:
2019/10/11 07:22:33 auth: unable to verify auth code with issuer: Post https://mypubicapi.example.com/oauth/token: x509: certificate signed by unknown authority

Reading the PDF linked by @parametriq, I'm not sure what the workaround is. On page 158 there is the table 7.11, with a parameter MasterCA - is that what must be added? But where does one add that in the console-config configmap, or perhaps the environment.

**Comment by parametriq** [comment]
I have to note we get a different error in openshift-console containers currently:

auth: State in url does not match State cookie

Although I never bothered to generate certificates myself, just using self-signed certs auto-generated during initial cluster installation. I suspect that for some reason console.apps.dc.rk(my cluster console DNS-name) was not included in the cert.

Will try to generate own certs using FreeIPA/Dogtag and report back later...

**Comment by parametriq** [comment]
I think I found out how to fix OAuth issues with Multi-master Openshift 3.11 architecture behind non-native HA LB where cluster PublicIP/URL is not reachable from within cluster subnet/VLAN... and what's important for me -- without touching container images. I only did this for Cluster Console deployment now and its working (No more non-informative "Oops! Something went wrong!" errors). Also I suspect that (maybe) more has to be done for default monitoring/logging deployments because those use oauth-proxy sidecar containers, unlike cluster console.

Variables involved:
masterPublicURL: https://okd-origin.dc.rk:8443
masterURL: https://okd-lb.dc.rk:8443

Anyways, here's what was done on already installed cluster:

1) Changed masterPublicURL in console-config ConfigMap to my actual internal masterURL,
restarted deployment for Cluster console project.

2) On every master-node in /etc/origin/master/master-config.yaml in oauthConfig section did exactly the same, e.g:
oauthConfig:
...
  masterPublicURL: https://okd-lb.dc.rk:8443
  masterURL: https://okd-lb.dc.rk:8443
...
then changed to root user and performed
master-restart api
master-restart controllers

3) Deleted all pods with 'oc delete pods --all -n openshift-console' and cleaned cookies for my consoleURL (e.g. console.apps.dc.rk) in the browser.

4) PROFIT!

P.S. I have to note that I'm using this edge HA LB setup which leverages LVS/IPVS in NAT mode for balancing all ingress traffic and HAProxy in tcp mode for reverse-proxying traffic to master /api endpoints:
https://github.com/myllynen/openshift-ha-load-balancer
so this is not a proxy requiring some user login/password for authorization, for bypassing that issue you still need to tinker with HTTP_PROXY-ish env variables

**Comment by Mihai-CMM** [comment]
I still see the issue in 3.11.146
"new detailed openshift 3.11 documentation problem solved" - what do you mean with this? 
In our case the internal LB cannot be resolved publically and openshift-console will redirect to it if I follow above advice, but was enough for an ugly hack.

Keep everything like it's now, setup dnsmasq.d to resolve locally public url (set up a new hosts file and point the url to master IP's on each master node) and then I've did an Iptables prerouting to forward 443 to 8443 on each master.
This cannot be a prod env with these many hacks. 
When will the oauth proxy be fixed to respect http proxies?
Thanks

**Comment by parametriq** [comment]
> "new detailed openshift 3.11 documentation problem solved" - what do you mean with this?
> In our case the internal LB cannot be resolved publically and openshift-console will redirect to it if I follow above advice, but was enough for an ugly hack.

You are right, its just a dirty hack, but as long as it works, and since we don't need any of the oauth-authorized services available publically + don't use any "edge proxy" with login/password authorization this will do for now in my case, I guess.

Let's face it -- all the development is in the Openshift 4 branches now, I doubt anyone will pay attention to this issue any time soon.
