### ISSUE TITLE
Install Openshift 3.11 Couldn't find csr for nodes 

### ISSUE THREAD

**Issue by srujan70** [openshift/openshift-ansible#11206]
Hi Team,

We are trying to install openshift multi master 3.11V using git clone. But we are getting the below error while approving node certificates. Could anyone please suggest us what is the root cause of this error.

Failure summary:
  1. Hosts:    oshmaster-xx-xx-xx-xxx
     Play:     Approve any pending CSR requests from inventory nodes
     Task:     Approve node certificates when bootstrapping
     Message:  Could not find csr for nodes: oshnodeapp-xx-xx-xx-xxx, oshnodeedge-xx-xx-xx-xxx, oshnodeinfra-xx-xx-xx-xxx, oshnodeinfra-xx-xx-xx-xxx, oshnodeedge-xx-xx-xx-xxx, oshnodeapp-xx-xx-xx-xxx

Thanks,
Srujan.

**Comment by vrutkovs** [comment]
Did `origin-node` service on masters started without errors?

**Comment by srujan70** [comment]
Hi @vrutkovs ,

Thanks for the reply. Could you please help how to check the status of origin-node service on masters?

-Srujan

**Comment by srujan70** [comment]
I guess this is what you are looking for and yeah that is running on master.

[openshift@oshmaster-10-131-142-223 ~]$ systemctl status origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon **2019-02-18** 10:41:07 UTC; 1h 59min ago
     Docs: https://github.com/openshift/origin
 Main PID: 5436 (hyperkube)
   CGroup: /system.slice/origin-node.service
           └─5436 /usr/bin/hyperkube kubelet --v=2 --address=0.0.0.0 --allow-privileged=true --anonymous-auth=true --authentication-token-webhook=true --authentication-token-webhook-cach...

**Comment by vrutkovs** [comment]
Check that other nodes have this service running. Also, check if CSR state - `oc get csr`

**Comment by theovich** [comment]
Hi Team,

We've same problem. We are trying to install openshift origin behind corporate proxy server and it fail with error message when preparing certificates
_1. Hosts:    mast01.c1-ocp.domain.com
     Play:     Approve any pending CSR requests from inventory nodes
     Task:     Approve node certificates when bootstrapping
     Message:  Could not find csr for nodes: infra03.c1-ocp.domain.com, infra02.c1-ocp.domain.com, infra01.c1-ocp.domain.com_

origin-node is running on all of the master nodes and systemctl status origin-node.service show:

_origin-node[8709]: E0221 21:32:36.731293    8709 summary.go:102] Failed to get system container stats for "/system.slice/origin-node.service": failed to get cgroup stats for "/system.slice/origin-node.service": failed to get container info for "/system.slice/origin-node.service": unknown container "/system.slice/origin-node.service"_

_[root@mast01 ~]# oc get csr show a lot of pending requests.

NAME                                                   AGE       REQUESTOR                                                 CONDITION
csr-26wtt                                              1m        system:node:mast03.c1-ocp.domain.com           Pending
csr-4lv99                                              13m       system:node:mast03.c1-ocp.domain.com           Pending
csr-6kwmc                                              1m        system:node:mast01.c1-ocp.domain.com           Pending
csr-6r6c7                                              15m       system:node:mast03.c1-ocp.domain.com           Pending
csr-b7cwx                                              15m       system:node:mast02.c1-ocp.domain.com           Pending
csr-blzv4                                              20m       system:admin                                              Pending
csr-d8zgs                                              20m       system:admin                                              Approved,Issued
csr-mnhwp                                              15m       system:node:mast01.c1-ocp.domain.com           Pending
csr-q4vgj                                              20m       system:admin                                              Pending
csr-spjh6                                              20m       system:admin                                              Approved,Issued
csr-sw7hf                                              20m       system:admin                                              Approved,Issued
csr-tgf86                                              13m       system:node:mast01.c1-ocp.domain.com           Pending
csr-vj55t                                              1m        system:node:mast02.c1-ocp.domain.com           Pending
csr-x5r6h                                              13m       system:node:mast02.c1-ocp.domain.com           Pending
csr-zckqj                                              20m       system:admin                                              Pending
node-csr-5kYQJwqRjQ5l6tXJJO8RGfgto5XKJQ6DgU2fNQwt9b4   13m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-deUt0SCGx3Py5jd9tDCgs5cxVRbFeRpdfvvs0qxpaO0   13m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending
node-csr-wDKjaJstCotZrEDma2GLtTCUtOkmov8UYiVDZZB4SxI   13m       system:serviceaccount:openshift-infra:node-bootstrapper   Pending_

Can it be some error in our ansible/hosts file? What we can do to complete the installation?
Thanks for your help.

**Comment by srujan70** [comment]
Hi @vrutkovs ,

Apart from master servers, none of the nodes are having the origin-node.service running. Please find the below output.

[openshift@oshnodeedge-10-131-142-236 ~]$ systemctl status origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2019-02-25 10:23:17 UTC; 4s ago
     Docs: https://github.com/openshift/origin
  Process: 5505 ExecStart=/usr/local/bin/openshift-node (code=exited, status=255)
 Main PID: 5505 (code=exited, status=255)

And the command "oc get csr " resulting in "no resources found"

Thanks,
Srujan.

**Comment by arenasmunera** [comment]
Hi @vrutkovs,

I am having the same problem but with different outputs that apparently are ok:

[openshift@master-0 ~]$ systemctl status origin-node.service
● origin-node.service - OpenShift Node
   Loaded: loaded (/etc/systemd/system/origin-node.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-02-26 10:32:03 UTC; 2min 20s ago
     Docs: https://github.com/openshift/origin
 Main PID: 67563 (hyperkube)
   CGroup: /system.slice/origin-node.service
           └─67563 /usr/bin/hyperkube kubelet --v=2 --address=0.0.0.0 --allow-privileged=true --anonymous-auth=true --authentication-token-webhook=true --authentication-token-webhook-cache-ttl=5m --authorization-mode=Webhook...

[openshift@master-0 ~]$ oc get nodes
NAME                                 STATUS    ROLES     AGE       VERSION
app-node-0.openshift.example.com     Ready     compute   33m       v1.11.0+d4cacc0
app-node-1.openshift.example.com     Ready     compute   33m       v1.11.0+d4cacc0
infra-node-0.openshift.example.com   Ready     infra     33m       v1.11.0+d4cacc0
master-0.openshift.example.com       Ready     master    36m       v1.11.0+d4cacc0

[openshift@master-0 ~]$ oc get csr
NAME                                                   AGE       REQUESTOR                                                 CONDITION
csr-4zbql                                              39m       system:admin                                              Approved,Issued
csr-hgkrc                                              39m       system:admin                                              Approved,Issued
csr-j9dws                                              37m       system:node:master-0.openshift.example.com                Approved,Issued
csr-k52hk                                              36m       system:node:infra-node-0.openshift.example.com            Approved,Issued
csr-krt7h                                              36m       system:node:master-0.openshift.example.com                Approved,Issued
csr-x462p                                              36m       system:node:app-node-1.openshift.example.com              Approved,Issued
csr-zmnzg                                              36m       system:node:app-node-0.openshift.example.com              Approved,Issued
node-csr-5XzACvD94CgRIpsloisFcCcO41HefMcPMjzbDkgZlI8   36m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-AmWP5RoEJZ0CWoJLAqZ_AS-JyC-pRw-cMHnZOh6_auA   36m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued
node-csr-gsOVnam19QusuPMR_eirhhEtsm8F0AdIyIUjDIWzwx8   36m       system:serviceaccount:openshift-infra:node-bootstrapper   Approved,Issued

Thank you very much,

Carlos.

**Comment by vrutkovs** [comment]
No response from original poster in a week, closing this.

Other comments are not showing the same issue, please file new separate issues for these cases. Please include log of `sync` pods, `origin-node` journal and `oc get csr` output

**Comment by Voronenko** [comment]
Actually got the same issue, when installing master node in `containerized=no` mode for `openshift.local` domain for nodes.   Perhaps someone who had similar and resolved can provide a hint ?

**Comment by kumarranja** [comment]
any updates on this issue?
