### ISSUE TITLE
Deployment fails at step to Distribute bootstrap and start nodes playbook

### ISSUE THREAD

**Issue by singh-ashok** [openshift/openshift-ansible#11305]
#### Description

When deploying openshift origin 3.11 deployment fails  PLAY [Distribute bootstrap and start nodes]

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`
ansible 2.7.8
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@master openshift-ansible]# 

If you're operating from a **git clone**:

* The output of `git describe`
ansible 2.7.8
  config file = /root/openshift-ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
[root@master openshift-ansible]# 

If you're running from playbooks installed via RPM

* The output of `rpm -q openshift-ansible`

Place the output between the code block below:

TASK [openshift_node : Copy master bootstrap config locally] *************************************************************************************************************
task path: /root/openshift-ansible/roles/openshift_node/tasks/distribute_bootstrap.yml:3
Tuesday 05 March 2019  21:37:17 +0000 (0:00:00.089)       0:00:09.941 ********* 
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/basics/slurp.py
<master.example.com> ESTABLISH SSH CONNECTION FOR USER: root
<master.example.com> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=600s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o ControlPath=/root/.ansible/cp/%h-%r master.example.com '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<master.example.com> rc=1, stdout and stderr censored due to no log
<master.example.com> Failed to connect to the host via ssh: <error censored due to no log>
fatal: [master.example.com -> master.example.com]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 
    "changed": false
}

VERSION INFORMATION HERE PLEASE
```

##### Steps To Reproduce
1. [step 1]
use the version 3.11 deployment branch and below is host file o/p
# Create an OSEv3 group that contains the masters, nodes, and etcd groups
[OSEv3:children]
masters
nodes
etcd

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root
openshift_enable_service_catalog=false
openshift_additional_repos=[{'id': 'centos-okd-ci', 'name': 'centos-okd-ci', 'baseurl' :'https://rpms.svc.ci.openshift.org/openshift-origin-v3.11', 'gpgcheck' :'0', 'enabled' :'1'}]

# If ansible_ssh_user is not root, ansible_become must be set to true
#ansible_become=true

openshift_deployment_type=origin

# uncomment the following to enable htpasswd authentication; defaults to AllowAllPasswordIdentityProvider
#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider'}]

# host group for masters
[masters]
master.example.com

# host group for etcd
[etcd]
master.example.com

# host group for nodes, includes region info
[nodes]
master.example.com openshift_node_group_name='node-config-master'
app-node.example.com openshift_node_group_name='node-config-compute'
infra.example.com openshift_node_group_name='node-config-infra'

2. [step 2]


##### Expected Results
installation to complete successfuly

```
Example command and output or error messages
ansible-playbook -vvv -i inventory/hosts.final  playbooks/openshift-node/join.yml 

##### Observed Results Distribute bootstrap and start nodes error exception is thorwn 
fatal: [master.example.com -> master.example.com]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 
    "changed": false
}

but master installation is run from master node and ssh to master node work as shown below
[root@master openshift-ansible]# ssh master
Last login: Tue Mar  5 21:36:59 2019 from master.example.com
[root@master ~]# 

Example command and output or error messages
```

For long output or logs, consider using a [gist](https://gist.github.com/)


##### Additional Information

Provide any additional information which may help us diagnose the
issue.

* Your operating system and version, ie: RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

```
EXTRA INFORMATION GOES HERE
```

**Comment by bkunal** [comment]
Looks like I am hitting same issue as well:



TASK [openshift_node : Copy master bootstrap config locally] ******************************************************************************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_node/tasks/distribute_bootstrap.yml:3
<server1.example.com> ESTABLISH SSH CONNECTION FOR USER: root
<server1.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b96bff266b server1.example.com '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
<server1.example.com> rc=0, stdout and stderr censored due to no log
<server1.example.com> ESTABLISH SSH CONNECTION FOR USER: root
<server1.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b96bff266b server1.example.com '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734 `" && echo ansible-tmp-1554994126.35-97422714908734="` echo /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734 `" ) && sleep 0'"'"''
<server1.example.com> rc=0, stdout and stderr censored due to no log
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/basics/slurp.py
<server1.example.com> PUT /root/.ansible/tmp/ansible-local-16970ds6Eox/tmpzDAz_s TO /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734/slurp.py
<server1.example.com> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b96bff266b '[server1.example.com]'
<server1.example.com> rc=0, stdout and stderr censored due to no log
<server1.example.com> ESTABLISH SSH CONNECTION FOR USER: root
<server1.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b96bff266b server1.example.com '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734/ /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734/slurp.py && sleep 0'"'"''
<server1.example.com> rc=0, stdout and stderr censored due to no log
<server1.example.com> ESTABLISH SSH CONNECTION FOR USER: root
<server1.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b96bff266b -tt server1.example.com '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734/slurp.py && sleep 0'"'"''
<server1.example.com> rc=1, stdout and stderr censored due to no log
<server1.example.com> Failed to connect to the host via ssh: <error censored due to no log>
<server1.example.com> ESTABLISH SSH CONNECTION FOR USER: root
<server1.example.com> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b96bff266b server1.example.com '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1554994126.35-97422714908734/ > /dev/null 2>&1 && sleep 0'"'"''
<server1.example.com> rc=0, stdout and stderr censored due to no log
fatal: [server2.example.com -> server1.example.com]: FAILED! => {
    "censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", 
    "changed": false
}

NO MORE HOSTS LEFT ************************************************************************************************************************************
	to retry, use: --limit @/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.retry

PLAY RECAP ********************************************************************************************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0   
server1.example.com : ok=89   changed=27   unreachable=0    failed=1   
server3.example.com : ok=105  changed=16   unreachable=0    failed=0   
server2.example.com : ok=113  changed=16   unreachable=0    failed=1   
server4.example.com : ok=105  changed=16   unreachable=0    failed=0   


INSTALLER STATUS **************************************************************************************************************************************
Initialization              : Complete (0:00:37)
Health Check                : Complete (0:01:44)
Node Bootstrap Preparation  : Complete (0:14:09)
etcd Install                : Complete (0:00:00)
Master Additional Install   : Complete (0:00:01)
Master Install              : Complete (0:00:00)
Node Join                   : In Progress (0:00:05)
	This phase can be restarted by running: playbooks/openshift-node/join.yml


Failure summary:


  1. Hosts:    server1.example.com
     Play:     Configure nodes
     Task:     Create credentials for registry auth
     Message:  timeout: failed to run command ‘skopeo’: No such file or directory
               

  2. Hosts:    server2.example.com
     Play:     Distribute bootstrap and start nodes
     Task:     Copy master bootstrap config locally
     Message:  Failed without returning a message.
[server1 ~]# 
[server1 ~]# rpm -qa | grep ansible
openshift-ansible-roles-3.11.92-1.git.0.f2fade7.el7.noarch
openshift-ansible-docs-3.11.92-1.git.0.f2fade7.el7.noarch
openshift-ansible-3.11.92-1.git.0.f2fade7.el7.noarch
ansible-2.6.16-1.el7ae.noarch
openshift-ansible-playbooks-3.11.92-1.git.0.f2fade7.el7.noarch
[server1 ~]# rpm -qa | grep skopeo
[server1 ~]# yum install skopeo
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package skopeo.x86_64 1:0.1.31-8.gitb0b750d.el7 will be installed
--> Processing Dependency: libostree-1.so.1(LIBOSTREE_2016.3)(64bit) for package: 1:skopeo-0.1.31-8.gitb0b750d.el7.x86_64
--> Processing Dependency: libostree-1.so.1(LIBOSTREE_2016.8)(64bit) for package: 1:skopeo-0.1.31-8.gitb0b750d.el7.x86_64
--> Processing Dependency: libostree-1.so.1()(64bit) for package: 1:skopeo-0.1.31-8.gitb0b750d.el7.x86_64
--> Running transaction check
---> Package ostree.x86_64 0:2018.5-1.el7 will be installed
--> Processing Dependency: libarchive.so.13()(64bit) for package: ostree-2018.5-1.el7.x86_64
--> Running transaction check
---> Package libarchive.x86_64 0:3.1.2-10.el7_2 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================
 Package         Arch        Version                          Repository                      Size
===================================================================================================
Installing:
 skopeo          x86_64      1:0.1.31-8.gitb0b750d.el7        rhel-7-server-extras-rpms      3.7 M
Installing for dependencies:
 libarchive      x86_64      3.1.2-10.el7_2                   rhel-7-server-rpms             319 k
 ostree          x86_64      2018.5-1.el7                     rhel-7-server-extras-rpms      465 k

Transaction Summary
===================================================================================================
Install  1 Package (+2 Dependent packages)

Total download size: 4.5 M
Installed size: 14 M
Is this ok [y/d/N]: y
Downloading packages:
(1/3): libarchive-3.1.2-10.el7_2.x86_64.rpm                                 | 319 kB  00:00:02     
(2/3): ostree-2018.5-1.el7.x86_64.rpm                                       | 465 kB  00:00:02     
(3/3): skopeo-0.1.31-8.gitb0b750d.el7.x86_64.rpm                            | 3.7 MB  00:00:02     
---------------------------------------------------------------------------------------------------
Total                                                              1.8 MB/s | 4.5 MB  00:00:02     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : libarchive-3.1.2-10.el7_2.x86_64                                                1/3 
  Installing : ostree-2018.5-1.el7.x86_64                                                      2/3 
  Installing : 1:skopeo-0.1.31-8.gitb0b750d.el7.x86_64                                         3/3 
  Verifying  : ostree-2018.5-1.el7.x86_64                                                      1/3 
  Verifying  : 1:skopeo-0.1.31-8.gitb0b750d.el7.x86_64                                         2/3 
  Verifying  : libarchive-3.1.2-10.el7_2.x86_64                                                3/3 

Installed:
  skopeo.x86_64 1:0.1.31-8.gitb0b750d.el7                                                          

Dependency Installed:
  libarchive.x86_64 0:3.1.2-10.el7_2                  ostree.x86_64 0:2018.5-1.el7                 

Complete!
[server1 ~]#

**Comment by JonesCZ** [comment]
I have the same issue. Any advice?
