### ISSUE TITLE
ansible-1.9.4 and yum-3.4.3-125 and yum-utils-1.1.31-29 may skip installing packages

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1138]
@wshearn and I were looking into an issue where the installer was silently failing to install packages. This problem will manifest itself as an access denied error when ansible attempts to start a service that's provided by an RPM that was being silently skipped. The verbose (-vvv) output will show something similar to this 

```
ok: [ose-node1.example.com] => {"changed": false, "msg": "", "rc": 0, "results": ["Plugin \"search-disabled-repos\" requires API 2.7. Supported API is 2.6. providing atomic-openshift-node is already installed", "Plugin \"search-disabled-repos\" requires API 2.7. Supported API is 2.6. providing tuned-profiles-atomic-openshift-node is already installed"]}
```

This seems to be https://github.com/ansible/ansible-modules-core/issues/2559

After trying a few things we were able to figure out that updating both yum-3.4.3-132.el7 and yum-utils-1.1.31-34.el7 versions which shipped with RHEL 7.2 seems to have resolved the issue. I'm surprised we haven't seen more reports of this. Maybe this only happens when subscription-manager is the latest but yum isn't?

Mostly putting this in encase anyone else runs into it, but if someone else has time to look into this more we should consider enforcing a minimum version of yum as much as I'd rather not do so.

**Comment by detiber** [comment]
@sdodson, I don't think that we can enforce a minimum version of yum and/or subscription-manager, since we are supporting RHEL 7.1 for deployments/upgrades still.

That said, I suspect that if we can track down a way to identify when we have a bad combination of packages that exhibit the issue, then we can fail only when that condition is met.

**Comment by tbielawa** [comment]
According to this comment, the issue should be fixed in a newer ansible version

https://github.com/ansible/ansible-modules-core/issues/3066#issuecomment-219048424

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.

**Comment by sbadakhc** [comment]
Looks like this is back? https://github.com/openshift/openshift-ansible/issues/7490
