### ISSUE TITLE
where are "prerequisites.yml & deploy_cluster.yml"??

### ISSUE THREAD

**Issue by angry-tony** [openshift/openshift-ansible#11410]
hello,
where are "prerequisites.yml & deploy_cluster.yml" files??
i can only see it from README.txt.

```
**in README.txt**

**Simple all-in-one localhost Installation**
This assumes that you've installed the base dependencies and you're running on Fedora or RHEL

git clone https://github.com/openshift/openshift-ansible
cd openshift-ansible
sudo ansible-playbook -i inventory/hosts.localhost playbooks/prerequisites.yml
sudo ansible-playbook -i inventory/hosts.localhost playbooks/deploy_cluster.yml
```

**Comment by Kiran-B** [comment]
I believe those files are available only in 3.x release branches. I could be wrong though.
Example: [Release 3.11](https://github.com/openshift/openshift-ansible/tree/release-3.11/playbooks)

Installation of OpenShift 4.x uses a command-line installation wizard instead of Ansible playbooks. Probably that is the reason why those files are not in master branch.

**Comment by mtnbikenc** [comment]
Hello,
Kiran-B is correct.  The master branch is for OpenShift 4.1 which uses a command-line [installer](https://github.com/openshift/installer).  The files in this repo are for scaling up or upgrading RHEL workers in an existing 4.1 cluster.  Previous versions of the openshift-ansible installer can be found in the associated release branches.
