### ISSUE TITLE
how to use my subdomain and private IP range for route or service

### ISSUE THREAD

**Issue by zet809** [openshift/openshift-ansible#11509]
I am using OKD 3.11 on RHEL 7.6
My env is a little strange and need several layer of forwarding.

PC (10.x.x.x)--> (10.x.x.x)login node(20.x.x.x) --> (20.x.x.x)openshift cluster(172.30.x.x) --> (172.30.x.x)openshift svcs

After config port forwarding on login node, my PC can access openshift cluster webconsole with https://20.x.x.x:8443
But the problem is, for the cluster console inside the webconsole, it have the hostname `https://console.router.default.svc.cluster.local/ ` and can not be access from my PC.

What I have did:
1. After add EXTERNAL-IP for svc `console` inside namespace `openshift-console`, the `https://openshift-console` can be access from my PC, but it then failed to access `https://console.router.default.svc.cluster.local/auth/login`. 
2. I add the following parameter for inventory yml file, the services/routes can use okd.c20cls.com as the domain name, but still the domain name `cluster.local` added in /etc/resolv.conf. 
```
openshift_console_hostname=myconsole.okd.c20cls.com
openshift_master_default_subdomain=okd.c20cls.com
```

So, my question are:
1. how to use my own subdomain name and can be resolved correctly inside openshift cluster?
2. how to use a different IP range other than  the default 172.30.x.x?
3. It is strange that the public webconsole(20.x.x.x) will then need to access a private subnet(172.30.x.x), or just by design?

**Comment by niiku** [comment]
> how to use my own subdomain name and can be resolved correctly inside openshift cluster?

Is your `20.x.x.x` IP of your master/infra node accessable from your PC directly? If yes, you need to set the following vars in your inventory file:
```
openshift_master_cluster_public_hostname=myconsole.okd.c20cls.com
openshift_master_cluster_hostname=<hostname of master node which is resolvable to it's ip>
```
If not, you need to make your master/infra node accessable, either through a Load Balancer, IP Forwarding (Firewall) and make the IP of your LB or FW resolvable as the DNS name provided in `openshift_master_cluster_public_hostname`

> how to use a different IP range other than the default 172.30.x.x?

Is this ranged already used inside your network elsewhere? If not, leave it as it is, because this is the range for Kubernetes `Service` IPs and is never directly accessable from outside your cluster. To make Services available outside of your cluster, your normally use `Routes` (easy), `Ingress` or `NodePort`/`LoadBalancer` as `Service` type. If this range is already used in your network, you need to find a different subnet (preferable `/16`) inside you network and configure it in your inventory file, e.g.
```
openshift_portal_net=100.68.0.0/16
```

> It is strange that the public webconsole(20.x.x.x) will then need to access a private subnet(172.30.x.x), or just by design?

As already mentioned, the `172.30.0.0/16` is a private network inside your OpenShift Cluster created and maintained by the SDN. These range is exclusively for your Kubernetes `Services`. The webconsole itself is also exposed inside your cluster through a `Service` IP. But it's a bit special, as it is externally exposed by default on port 8443 on your master node together with the OpenShift API. So the :8443/console will be routed to your webconsole instance, but externally you don't need access to internal IP 172.30.0.0/16 IP.

**Comment by zet809** [comment]
hi, @niiku 
`So the :8443/console will be routed to your webconsole instance, but externally you don't need access to internal 172.30.0.0/16 IPs.`
In my openshift cluster, I'd like to access the `Cluster Console` page,  the openshift redirect me to `https://console.router.default.svc.cluster.local/` which is unavailable from 20.x subnet.
So, I'd like to know how to export the `Cluster Console` to be an 20.x subnet.

I have tried to add EXTERNAL-IP for svc console inside namespace `openshift-console`, the https://openshift-console can be access from my PC, but it then still failed to access https://console.router.default.svc.cluster.local/auth/login.

**Comment by zet809** [comment]
In fact, what I want to do is following https://docs.okd.io/latest/install/configuring_inventory_file.html#configuring-the-admin-console to view the cluster status.

**Comment by lkhomenk** [comment]
@zet809 check on your cluster where pods from `openshift-console` namespace are running. In our case they were on infra-nodes - not  master nodes. so just add dns(for openshift_console_hostname) and  routing to those nodes port 443 private IPs from 20.* subnet. that's a bit out of openshift scope

**Comment by sapkra** [comment]
@zet809 I have the same problem - were you able to solve it?

**Comment by zet809** [comment]
NO, not deal with it for some time.
