### ISSUE TITLE
New master config options for identity provider selection page

### ISSUE THREAD

**Issue by jwforres** [openshift/openshift-ansible#1180]
See docs changes here https://github.com/openshift/openshift-docs/issues/1422  and code changes here https://github.com/openshift/origin/pull/6596

The page isn't super useful yet unless you want to make sure you have a branded page the user sees before being redirected off to some login flow, e.g. if you want to see an "OpenShift" branded page before the user gets taken to GitHub's login page.  Eventually if we support multiple identity providers then the idea is that this page would always appear if the admin configured multiple providers with login support.

**Comment by jwforres** [comment]
Also the related oauth error page, configuration is basically the same just a different key in the config.

**Comment by detiber** [comment]
@dgoodwin can you verify if this is fully supported now?

**Comment by dgoodwin** [comment]
I'm not positive exactly which config options this issue is regarding. Digging through the code PR I see alwaysShowProviderSelection and providerSelection, are there any others?

alwaysShowProviderSelection can be configured via openshift_master_oauth_always_show_provider_selection in inventory. 

I don't think anything was added for providerSelection. Is this required as well @jwforres ?

**Comment by detiber** [comment]
@dgoodwin actually, according to https://github.com/openshift/online/issues/29 it looks like this is fully supported in openshift-ansible now.

Closing.
