### ISSUE TITLE
Should the load balancer be included as a non-schedulable infra node in the node inventory group in byo/config.yml?

### ISSUE THREAD

**Issue by lypht** [openshift/openshift-ansible#1213]
I've noted that [host.origin.example ](https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.origin.example) does not include the load balancer `[lb]` in the list of `[nodes]` with masters and nodes.  Once byo/config runs successfully, haproxy is running (and can be tested at *lb.foo.com:9000*) yet origin is not installed on this VM.  Should the load balancer be included as a non-schedulable infrastructure node with masters and nodes in the `[nodes]` inventory group?  If not, openshift is not installed, and a router cannot be scheduled as a pod on lb.foo.com.

**Comment by abutcher** [comment]
Hey @lypht, the `[lb]` host group represents a separate infrastructure component just for balancing the master API when using [multiple masters](https://docs.openshift.org/latest/install_config/install/advanced_install.html#multiple-masters). The router isn't meant to live on the load balancer by design. That being said, I don't think you would have any problems configuring the load balancer instance to also be a node if that fits your needs.

**Comment by lypht** [comment]
Thanks for the quick reply.  Perhaps I'm taking [this instruction](https://docs.openshift.org/latest/install_config/routing_from_edge_lb.html#including-lb-in-sdn) out of context, where it's indicating, when possible, to run a node on the load balancer itself.  I'll continue with routers assigned on the nodes.

**Comment by abutcher** [comment]
@lypht Ahhh, thanks for pointing that out. We have two different "load balancer" concepts it seems.

**Comment by lypht** [comment]
No worries.  The documentation on this project is superlative; and yet there are a ton of moving parts.  Thanks again.
