### ISSUE TITLE
Wrong fact when applying playbooks with SUBSET

### ISSUE THREAD

**Issue by spinolacastro** [openshift/openshift-ansible#1263]
As far as i know it only happens with dedicated etcd servers. If i try to apply the playbook as following:

<pre>
ansible-playbook -i hosts -l masters openshfit-ansible/playbooks/byo/config.yml
</pre>

The etcd cluster config is overwritten for the builtin etcd server and the cluster goes down.

**Comment by detiber** [comment]
Adding additional context.. The problem comes from the fact that we are dynamically setting the facts in openshift_facts and not persisting them.  The following variables should be set when invoking the openshift_master role:
- `openshift_master_embedded_dns` 
- `openshift_master_etcd_urls`

An alternative to setting `openshift_master_etcd_urls` is to set the following variables:
- openshift_master_etcd_hosts
- openshift_master_etcd_port
- openshift_master_etcd_use_ssl

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
