### ISSUE TITLE
Update inventory examples to use /etc/origin/master for htpasswd file.

### ISSUE THREAD

**Issue by detiber** [openshift/openshift-ansible#1312]

**Comment by jstuever** [comment]
I have a patch mostly ready for this. I want to clarify a few things. This change is for all three byo examples? Any others?

inventory/byo/hosts.aep.example
inventory/byo/hosts.origin.example
inventory/byo/hosts.ose.example

**Comment by detiber** [comment]
In openshift-ansible, yes.

There are probably also some references in the openshift-docs repo

**Comment by jstuever** [comment]
@detiber Thanks. I have another question regarding the path. I noticed my master configs always land in /etc/origin/* regardless of the deployment_type I choose when running the byo/config.yaml playbook. This contradicts ${subject}, which led me to realize the intended path might be different for each deployment_type. If so, this is a bug with [openshift_facts.py](https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_facts/library/openshift_facts.py#L661) comparing ['enterprise'] instead of ['openshift-enterprise', 'atomic-enterprise']. Can you confirm the intention here is to use the following paths?

atomic-enterprise => /etc/openshift
openshift-enterprise => /etc/openshift
origin => /etc/origin

**Comment by detiber** [comment]
As of Origin 1.1 and OSE 3.1 the path is indeed /etc/origin.

The title is incorrect.
