### ISSUE TITLE
Setting etcd volume on AWS manually

### ISSUE THREAD

**Issue by brettneese** [openshift/openshift-ansible#1322]
I'm noticing in https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/openshift-cluster/templates/user_data.j2#L15 that the etcd volume is being set by user-data. 

I'm provisioning by hand, but I'd like to use an external ebs volume on my etcd node. Do I just need to create a ebs volume, attach it, and copy that first stanza into my user data, or do I need to configure etcd elsewhere to use that volume?

**Comment by detiber** [comment]
@brettneese That is the default location for the non-embedded etcd service. If you are using the embedded etcd provided by the master service (available for non-ha environments only), then there is a different location used by default (somewhere under /var/lib/origin).

If you are not creating the disk at provisioning time, then you would most likely need to manually configure the volume for use rather than using cloud-config to manage the disk for you.

**Comment by brettneese** [comment]
Right, we're running our own etcd node. Do I just need to mount the
EBS device under /var/lib/etcd before provisioning?

On Monday, February 1, 2016, Jason DeTiberus <notifications@github.com>
wrote:

> @brettneese <https://github.com/brettneese> That is the default location
> for the non-embedded etcd service. If you are using the embedded etcd
> provided by the master service (available for non-ha environments only),
> then there is a different location used by default (somewhere under
> /var/lib/origin).
>
> If you are not creating the disk at provisioning time, then you would most
> likely need to manually configure the volume for use rather than using
> cloud-config to manage the disk for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openshift/openshift-ansible/issues/1322#issuecomment-178319935>
> .
>


-- 
Brett Neese
563-210-3459

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
