### ISSUE TITLE
s3 registry template fail with ose-docker-registry:v3.1.1.6

### ISSUE THREAD

**Issue by gaelL** [openshift/openshift-ansible#1332]
Hello,

I tried to run s3 registry on the new `v3.1.1.6` version. But it fail because a config is missing
```
delete:
   enabled: true
```
.

Referring to a diff between `v3.1.0.4` and `v3.1.1.6`  : 
```
docker run --rm --interactive=true --tty --entrypoint=cat registry.access.redhat.com/openshift3/ose-docker-registry:v3.1.0.4  config.yml > /tmp/config04.yml
docker run --rm --interactive=true --tty --entrypoint=cat registry.access.redhat.com/openshift3/ose-docker-registry:v3.1.1.6  config.yml > /tmp/config06.yml

[root@master01 origin]# diff -ruN /tmp/config04.yml /tmp/config06.yml 
--- /tmp/config04.yml   2016-02-04 17:25:44.247557897 +0100
+++ /tmp/config06.yml   2016-02-04 17:26:19.650557897 +0100
@@ -1,4 +1,3 @@
-docker run --rm --interactive=true --tty --entrypoint=cat registry.access.redhat.com/openshift3/ose-docker-registry:v3.1.1.6  config.yml > /tmp/config06.yml
 version: 0.1
 log:
   level: debug
@@ -9,6 +8,8 @@
     layerinfo: inmemory
   filesystem:
     rootdirectory: /registry
+  delete:
+    enabled: true
 auth:
   openshift:
     realm: openshift
```

How you want to deal with the template and docker image version ?

If you want to stick to the last version, I can do a pull request to add this parameter. If not, I let you decide show to maintain multiple version of the `config.yml` file.

Regards

**Comment by detiber** [comment]
@gaelL I'm assuming this is for the playbooks/adhoc/s3_registry.yml playbook.

If so, do you know if the `delete` param is backwards compatible with the previous version of the registry that we deployed?

@dak1n1 This will most likely cause you issues at some point.

**Comment by gaelL** [comment]
yes sorry it's for `playbooks/adhoc/s3_registry.yml`. I will check if the param is backwards compatible.

**Comment by gaelL** [comment]
The param not seems to be backwards compatible : 
```
[root@master01 origin]# oc logs docker-registry-15-dfxda
time="2016-02-04T12:01:24-05:00" level=fatal msg="Error parsing configuration file: Must provide exactly one storage type. Provided: [s3 delete]" 
```
My pod go into a bad state : 
```
NAME                        READY     STATUS             RESTARTS   AGE
docker-registry-15-dfxda    0/1       CrashLoopBackOff   5          2m
```

**Comment by detiber** [comment]
@gaelL thanks, that complicates things a bit. We either have to:

- Sacrifice older version compatibility (or fork the playbook for compatibility)
- Add conditional logic so that the playbook checks what version of {ose,aep,origin}-docker-registry is installed and and a condition the template accordingly.

@dak1n1 @wshearn since Ops is the primary consumer of this playbook, thoughts on the above?

**Comment by dak1n1** [comment]
Hmm. My docker registry is running fine on version 3.1.1.6, without the delete option.

[root@osevg-master-e6297 ~]# oc get pods docker-registry-7-0fqq2 -o yaml |grep image
    image: registry.access.redhat.com/openshift3/ose-docker-registry:v3.1.1.6

[root@osevg-infra-6a7a7 ~]# cat /var/lib/origin/openshift.local.volumes/pods/20d2b04b-cad3-11e5-9296-1218e6d608d7/volumes/kubernetes.io~secret/dockersecrets/config.yml

version: 0.1
log:
  level: debug
http:
  addr: :5000
storage:
  cache:
    layerinfo: inmemory
  s3:
    accesskey: ****************
    secretkey: **********************************
    region: us-east-1
    bucket: oso-osevg-docker
    encrypt: true
    secure: true
    v4auth: true
    rootdirectory: /registry
auth:
  openshift:
    realm: openshift
middleware:
  repository:
    - name: openshift

Since it's working as-is, I'm not particularly worried about adding the delete option quite yet. But you're welcome to add it if you'd like. I'm working on refactoring it to set up the secured registry bits across the cluster instead, since that's the direction we're moving in. Backwards compatibility shouldn't be an issue for us Ops.

**Comment by gaelL** [comment]
When you say running fine, you are talking about the registry status ? or you tried to push image in the registry ?

For us, the registry was running without the delete part but we was not able to push image in.

**Comment by gaelL** [comment]
I rollback again all changes and test it again on our customer platform. It seems to work.
Maybe a side effect from an other component. We are on a aws environment with proxy and restricted access. I will check with the customer if he did some changes this afternoon. Sorry for the noise, I close this issue
