### ISSUE TITLE
The PROD branch fails at Import Centos Image streams] 

### ISSUE THREAD

**Issue by alincalinciuc** [openshift/openshift-ansible#1338]
TASK: [openshift_examples | Import Centos Image streams] *********************\* 
failed: [xxx.xxx.xxx.xxx] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.353184", "end": "2016-02-04 23:01:39.702001", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-02-04 23:01:39.348817", "stdout_lines": [], "warnings": []}
stderr: unable to connect to a server to handle "imagestreamlists": Get https://192.168.251.4:8443/oapi: dial tcp 192.168.251.4:8443: connection refused

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/root/update.retry

xxx.xxx.xxx.xxx               : ok=54   changed=0    unreachable=0    failed=0  
xxx.xxx.xxx.xxx               : ok=54   changed=0    unreachable=0    failed=0  
xxx.xxx.xxx.xxx               : ok=214  changed=2    unreachable=0    failed=1  
xxx.xxx.xxx.xxx               : ok=54   changed=0    unreachable=0    failed=0  
localhost                  : ok=11   changed=0    unreachable=0    failed=0

**Comment by detiber** [comment]
@alincalinciuc This has already been fixed in master. The int, stage, and prod branches are used internally by OpenShift Operations and aren't tested for general use.

**Comment by alincalinciuc** [comment]
Thank you @detiber !

**Comment by vitaliedicusara** [comment]
Getting the the same issue with the latest code from the master.

TASK: [openshift_examples | Import Centos Image streams] **********************
failed: [10.2.2.5] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.163222", "end": "2016-02-08 12:23:40.585800", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-02-08 12:23:40.422578", "stdout_lines": [], "warnings": []}
stderr: unable to connect to a server to handle "imagestreamlists": Get https://10.2.2.5:8443/oapi: dial tcp 10.2.2.5:8443: connection refused

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/config.retry

10.2.2.5                   : ok=219  changed=22   unreachable=0    failed=1   
10.2.2.6                   : ok=50   changed=5    unreachable=0    failed=0   
10.2.2.7                   : ok=50   changed=5    unreachable=0    failed=0   
localhost                  : ok=15   changed=0    unreachable=0    failed=0

**Comment by detiber** [comment]
@vitaliedicusara So, the error is complaining about connecting to the api server. Are there any errors in the master logs? `journalctl -u origin-master -l`

**Comment by lorenzvth7** [comment]
+1

**Comment by karelstriegel** [comment]
+1

**Comment by detiber** [comment]
@lorenzvth7 @karelstriegel are you seeing this against master or against the 'prod' branch? The Prod branch should not be used.

**Comment by karelstriegel** [comment]
@detiber I'm seeing this against master. Did a checkout yesterday and tried to upgrade a 1.1.3 setup.

**Comment by detiber** [comment]
@karelstriegel thanks, can you share the inventory file you are using, and what type of hosts you are running against (CentOS 7, Fedora 23, Fedora Atomic, CentOS Atomic, etc)?

**Comment by karelstriegel** [comment]
@detiber for your request : http://pastebin.com/n2SfGS6n

**Comment by detiber** [comment]
@karelstriegel I'm not able to replicate this on a new install...  When you say you were trying to upgrade a 1.1.3 environment, were you doing it using the upgrade playbook or some other way?

**Comment by karelstriegel** [comment]
@detiber I've installed v1.1.3 using the playbook. I just pulled the git repo (master branch) at that time. A few weeks went and I noticed that version 1.1.5 was released, so performed a git pull on my local git clone of the master branch and I executed the upgrade playbook. I followed the [official documentation](https://docs.openshift.org/latest/install_config/upgrading/automated_upgrades.html#upgrading-to-openshift-origin-1-1-z-releases). 

ps: I've noticed that version 1.1.5 has been released,but when pulling the latest version of the openshift-ansible repo, it will upgrade your env to 1.1.4.

**Comment by zhwenh** [comment]
i get last master branch now Still show wrong info
ansible 1.9.4

hosts file content:

Create an OSEv3 group that contains the masters and nodes groups

[OSEv3:children]
masters
nodes

Set variables common for all OSEv3 hosts

[OSEv3:vars]

SSH user, this user should allow ssh based auth without requiring a password

ansible_ssh_user=root

If ansible_ssh_user is not root, ansible_sudo must be set to true

#ansible_sudo=true

deployment_type=origin

uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider

#openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

host group for masters

[masters]
master.example.com

host group for nodes, includes region info

[nodes]
master.example.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
node1.example.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
node2.example.com openshift_node_labels="{'region': 'primary', 'zone': 'west'}"

show this error :
TASK: [openshift_examples | Import Centos Image streams] **********************
failed: [10.1.130.14] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-centos7.json"], "delta": "0:00:00.265661", "end": "2016-03-31 14:24:58.952895", "failed": true, "failed_when_result": true, "rc": 1, "start": "2016-03-31 14:24:58.687234", "stdout_lines": [], "warnings": []}
stderr: unable to connect to a server to handle "imagestreamlists": Get https://10.1.130.14:8443/oapi: dial tcp 10.1.130.14:8443: connection refused

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
to retry, use: --limit @/Users/wen/config.retry

10.1.130.14 : ok=172 changed=1 unreachable=0 failed=1
10.1.130.15 : ok=7 changed=0 unreachable=0 failed=0
10.1.130.16 : ok=7 changed=0 unreachable=0 failed=0
localhost : ok=17 changed=0 unreachable=0 failed=0

**Comment by detiber** [comment]
@karelstriegel that is because the RPMs in the COPR repo haven't been updated. @sdodson do you think you could update the COPR repo for 1.1.5, or do you want to wait until the hotfix is out?

**Comment by detiber** [comment]
@zhwenh are there any errors in the journal for the master process? `journalctl -u origin-master -l`

**Comment by zhwenh** [comment]
Apr 02 23:12:08 slave673 systemd[1]: Starting Origin Master Service...
Apr 02 23:12:08 slave673 systemd[1]: origin-master.service holdoff time over, scheduling restart.
Apr 02 23:12:08 slave673 systemd[1]: origin-master.service failed.
Apr 02 23:12:08 slave673 systemd[1]: Unit origin-master.service entered failed state.
Apr 02 23:12:08 slave673 systemd[1]: origin-master.service: main process exited, code=exited, status=255/n/a
Apr 02 23:12:08 slave673 origin-master[23006]: F0402 23:12:08.130856   23006 run_components.go:357] SDN initialization failed: Error: Host network with IP: 10.1.130.0 conflicts with cluster network: 10.1.0.0/16
Apr 02 23:12:07 slave673 origin-master[23006]: I0402 23:12:07.847019   23006 common.go:77] Self IP: 10.1.130.16.
Apr 02 23:12:07 slave673 origin-master[23006]: [858.969977ms] [924ns] END
Apr 02 23:12:07 slave673 origin-master[23006]: [858.969053ms] [1.367638ms] Writing http response done (1 items)
Apr 02 23:12:07 slave673 origin-master[23006]: [857.601415ms] [28.611碌s] Self-linking done
Apr 02 23:12:07 slave673 origin-master[23006]: [857.572804ms] [857.536871ms] Listing from storage done
Apr 02 23:12:07 slave673 origin-master[23006]: [35.933碌s] [35.933碌s] About to List from storage
Apr 02 23:12:07 slave673 origin-master[23006]: I0402 23:12:07.834618   23006 trace.go:57] Trace "List /oapi/v1/imagestreams" (started 2016-04-02 23:12:06.975614435 +0800 CST):
Apr 02 23:12:07 slave673 origin-master[23006]: [761.337456ms] [610ns] END
Apr 02 23:12:07 slave673 origin-master[23006]: [761.336846ms] [1.861碌s] Decoded 1 nodes
Apr 02 23:12:07 slave673 origin-master[23006]: [761.334985ms] [761.333491ms] Decoding dir /openshift.io/imagestreams/openshift END
Apr 02 23:12:07 slave673 origin-master[23006]: [1.494碌s] [1.494碌s] Decoding dir /openshift.io/imagestreams/openshift START

**Comment by detiber** [comment]
This is the relevant line:
```
23:12:08.130856 23006 run_components.go:357] SDN initialization failed: Error: Host network with IP: 10.1.130.0 conflicts with cluster network: 10.1.0.0/16
```

You will need to override the `osm_cluster_network_cidr` variable to use a non-conflicting network. In your inventory, you could define it as follows:
```
osm_cluster_network_cidr=172.16.0.0/16

```

**Comment by zhwenh** [comment]
ok, So what do you suggest "osm_cluster_network_cidr=172.16.0.0/16" this added to the playbook  roles which is better? I'm new in openshift! thank.

**Comment by alongoldboim** [comment]
@detiber Hi, getting the same error, when will Copr be updated?
http://pastebin.com/gqpRN0kk

**Comment by detiber** [comment]
@sdodson @tdawson  ^ did the copr repo ever get updated?

**Comment by vijaycbe** [comment]
I've a similar error but there is no errors found related to SDN.

Here is my ansible inventory file

[OSEv3:children]
masters
etcd
nodes

# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

deployment_type=openshift-enterprise

# uncomment the following to enable htpasswd authentication; defaults to DenyAllPasswordIdentityProvider
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

osm_cluster_network_cidr = 192.168.59.0/24

# host group for masters
[masters]
ose-master1.spd-atlss.com

# etcd group
[etcd]
ose-master1.spd-atlss.com

# host group for nodes, includes region info
[nodes]
ose-master1.spd-atlss.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=false
ose-infra1.spd-atlss.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
ose-app1.spd-atlss.com openshift_node_labels="{'region': 'vbox', 'zone': 'devtest'}"
ose-app2.spd-atlss.com openshift_node_labels="{'region': 'vbox', 'zone': 'devtest'}"


I've a trial licence for Openshift enterprise.

the error is 

2018-03-28 10:13:21,717 p=8039 u=root |  failed: [ose-master1.spd-atlss.com] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json"], "delta": "0:00:00.634771", "end": "2018-03-28 10:13:21.700537", "failed": true, "failed_when_result": true, "rc": 1, "start": "2018-03-28 10:13:21.065766", "stdout_lines": [], "warnings": []}
166599-2018-03-28 10:13:21,717 p=8039 u=root |  stderr: unable to connect to a server to handle "imagestreamlists": Get https://ose-vip.spd-atlss.com:8443/oapi: dial tcp 192.168.59.151:8443: connection refused
2018-03-28 10:13:21,718 p=8039 u=root |  FATAL: all hosts have already failed -- aborting
2018-03-28 10:13:21,718 p=8039 u=root |  PLAY RECAP ********************************************************************
2018-03-28 10:13:21,719 p=8039 u=root |             to retry, use: --limit @/root/config.retry

2018-03-28 10:13:21,719 p=8039 u=root |  localhost                  : ok=15   changed=0    unreachable=0    failed=0
2018-03-28 10:13:21,719 p=8039 u=root |  ose-app1.spd-atlss.com     : ok=24   changed=0    unreachable=0    failed=0
2018-03-28 10:13:21,719 p=8039 u=root |  ose-app2.spd-atlss.com     : ok=24   changed=0    unreachable=0    failed=0
2018-03-28 10:13:21,719 p=8039 u=root |  ose-infra1.spd-atlss.com   : ok=24   changed=0    unreachable=0    failed=0
2018-03-28 10:13:21,719 p=8039 u=root |  ose-master1.spd-atlss.com  : ok=300  changed=4    unreachable=0    failed=1

While I changed the "osm_cluster_network_cidr" and retried, the error is

2018-03-28 11:48:10,083 p=12414 u=root |  TASK: [openshift_examples | Import RHEL streams] ******************************
2018-03-28 11:48:11,154 p=12414 u=root |  failed: [ose-master1.spd-atlss.com] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json"], "delta": "0:00:00.349319", "end": "2018-03-28 11:48:11.126801", "failed": true, "failed_when_result": true, "rc": 1, "start": "2018-03-28 11:48:10.777482", "stdout_lines": [], "warnings": []}
2018-03-28 11:48:11,155 p=12414 u=root |  stderr: unable to connect to a server to handle "imagestreamlists": Get https://ose-vip.spd-atlss.com:8443/oapi: dial tcp 192.168.59.151:8443: connection refused
2018-03-28 11:48:11,155 p=12414 u=root |  FATAL: all hosts have already failed -- aborting
2018-03-28 11:48:11,155 p=12414 u=root |  PLAY RECAP ********************************************************************
2018-03-28 11:48:11,156 p=12414 u=root |             to retry, use: --limit @/root/config.retry

2018-03-28 11:48:11,156 p=12414 u=root |  localhost                  : ok=15   changed=0    unreachable=0    failed=0
2018-03-28 11:48:11,156 p=12414 u=root |  ose-master1.spd-atlss.com  : ok=299  changed=5    unreachable=0    failed=1


The output of status log for atomic service is 

Mar 28 10:36:15 ose-master1 systemd[1]: Starting Atomic OpenShift Master...
Mar 28 10:36:15 ose-master1 atomic-openshift-master[18500]: W0328 10:36:15.781171   18500 start_master.go:269] assetConfig.loggingPublicURL: invalid value '', Details:
Mar 28 10:36:15 ose-master1 atomic-openshift-master[18500]: W0328 10:36:15.781405   18500 start_master.go:269] assetConfig.metricsPublicURL: invalid value '', Details:
Mar 28 10:36:16 ose-master1 atomic-openshift-master[18500]: I0328 10:36:16.439868   18500 plugins.go:71] No cloud provider specified.
Mar 28 10:36:16 ose-master1 atomic-openshift-master[18500]: I0328 10:36:16.604293   18500 start_master.go:380] Starting master on 0.0.0.0:8443 (v3.1.1.11-26-g629ff43)
Mar 28 10:36:16 ose-master1 atomic-openshift-master[18500]: I0328 10:36:16.604329   18500 start_master.go:381] Public master address is https://192.168.59.189:8443
Mar 28 10:36:16 ose-master1 atomic-openshift-master[18500]: I0328 10:36:16.604348   18500 start_master.go:385] Using images from "openshift3/ose-<component>:v3.1.1.11"
Mar 28 10:36:16 ose-master1 atomic-openshift-master[18500]: I0328 10:36:16.624278   18500 run_components.go:181] Using default project node label selector:
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: W0328 10:36:17.137361   18500 controller.go:290] Resetting endpoints for master service "kubernetes" to &{{
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459119   18500 master.go:237] Started Kubernetes API at 0.0.0.0:8443/api/v1
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459154   18500 master.go:237] Started Kubernetes API Extensions at 0.0.0.0:8443/apis/extensio
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459161   18500 master.go:237] Started Origin API at 0.0.0.0:8443/oapi/v1
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459168   18500 master.go:237] Started OAuth2 API at 0.0.0.0:8443/oauth
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459174   18500 master.go:237] Started Login endpoint at 0.0.0.0:8443/login
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459180   18500 master.go:237] Started Web Console 0.0.0.0:8443/console/
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.459186   18500 master.go:237] Started Swagger Schema API at 0.0.0.0:8443/swaggerapi/
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.636657   18500 ensure.go:184] Ignoring bootstrap policy file because cluster policy found
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.638428   18500 ensure.go:201] error waiting for policy cache to initialize: Post https://ose-
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.640286   18500 ensure.go:164] Unable to create default security context constraint privileged
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.641933   18500 ensure.go:164] Unable to create default security context constraint nonroot.
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.643569   18500 ensure.go:164] Unable to create default security context constraint hostmount-
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.645100   18500 ensure.go:164] Unable to create default security context constraint hostaccess
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.646609   18500 ensure.go:164] Unable to create default security context constraint restricted
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.648193   18500 ensure.go:164] Unable to create default security context constraint anyuid.  G
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.649987   18500 ensure.go:105] Error adding service account roles to "default" namespace: Get
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: E0328 10:36:17.651823   18500 ensure.go:52] Error creating namespace openshift-infra: Post https://ose-vip.s
Mar 28 10:36:17 ose-master1 openshift[18500]: skydns: ready for queries on cluster.local. for tcp4://0.0.0.0:53 [rcache 0]
Mar 28 10:36:17 ose-master1 openshift[18500]: skydns: ready for queries on cluster.local. for udp4://0.0.0.0:53 [rcache 0]
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.756635   18500 run_components.go:176] DNS listening at 0.0.0.0:53
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: I0328 10:36:17.758764   18500 start_master.go:507] Controllers starting (*)
Mar 28 10:36:17 ose-master1 systemd[1]: Started Atomic OpenShift Master.
Mar 28 10:36:17 ose-master1 atomic-openshift-master[18500]: F0328 10:36:17.924665   18500 run_components.go:393] Unable to initialize namespaces: unable to refresh the
Mar 28 10:36:17 ose-master1 systemd[1]: atomic-openshift-master.service: main process exited, code=exited, status=255/n/a
Mar 28 10:36:17 ose-master1 systemd[1]: Unit atomic-openshift-master.service entered failed state.
Mar 28 10:36:17 ose-master1 systemd[1]: atomic-openshift-master.service failed.
Mar 28 10:36:18 ose-master1 systemd[1]: atomic-openshift-master.service holdoff time over, scheduling restart.
Mar 28 10:36:18 ose-master1 systemd[1]: Starting Atomic OpenShift Master...


I've a particular  VM which is in the same network and having DNS entries for all these nodes with the hostnames and nslookup is working fine.


Output of network route

[root@ose-master1 ~]# ip route
default via 192.168.59.1 dev enp0s3 proto static metric 100
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.42.1
192.168.59.0/24 dev enp0s3 proto kernel scope link src 192.168.59.189 metric 100

**Comment by michaelgugino** [comment]
osm_cluster_network_cidr is the problem.  Don't set that variable unless the default conflicts with your existing network. @vijaycbe We don't support change that after a cluster has been deployed, so you'll need to create new instances from scratch.
Please file a new issue if you continue having problems.
