### ISSUE TITLE
[RFE] load balancer ansible option doesn't support port

### ISSUE THREAD

**Issue by thoraxe** [openshift/openshift-ansible#1349]
It looks like the default config for haproxy when having Ansible install it for you is to use port 8443.
There does not appear (in the hosts example) to be an option to set the port (eg: to 443).

**Comment by abutcher** [comment]
These should update ports on haproxy lb and elsewhere.

```
openshift_master_api_port=443                                                                                 
openshift_master_console_port=443
```

**Comment by thoraxe** [comment]
Are you saying that if those are used that it affects the port that lb gets configured for?

What if I want my LB on 443 but I don't want to move the rest of the things from 8443?

**Comment by abutcher** [comment]
Yeah, we need separate variables.

**Comment by detiber** [comment]
@thoraxe remember that the lb is not meant for production use...  I'm not sure we want to spend too much development time on it unless there is a functionality bug...

**Comment by edseymour** [comment]
@detiber So irrespective of the installer provisioning a LB, we would like to configure the public URLs ports, without affecting what the master port config. If we're installing the LB then, naturally, this should take this value. If we're not installing a LB, and using some other external system, we are defining the external port of the LB being provided, and not the port of the master api & console. 

We may still want to run the master on 8443 (perhaps we have a router running there), but the public URL would be 443 via some external LB. 

Why run a router on the master? Some external systems require this for integration.

**Comment by detiber** [comment]
On Feb 15, 2016 8:51 AM, "Ed Seymour" <notifications@github.com> wrote:
>
> @detiber So irrespective of the installer provisioning a LB, we would
like to configure the public URLs ports, without affecting what the master
port config. If we're installing the LB then, naturally, this should take
this value. If we're not installing a LB, and using some other external
system, we are defining the external port of the LB being provided, and not
the port of the master api & console.
>
> We may still want to run the master on 8443 (perhaps we have a router
running there), but the public URL would be 443 via some external LB.

The problem that I ran into with this in the past is that OpenShift would
force a redirect back to the locally configured port.

We might be able to work around it using the master SNI certs, otherwise
the load balancer would require being configured for re-encryption, which
is currently a chicken and egg problem.

>
> Why run a router on the master? Some external systems require this for
integration.

Indeed, it is far from ideal that they need to be located on the master
currently. The only reason the master is required to be a node is that it
needs to be part of the SDN.

**Comment by thoraxe** [comment]
Why is the load balancer option not for "production" use @detiber ?

**Comment by edseymour** [comment]
@abutcher I tried the following settings
```
openshift_master_api_port=443                                                                                 
openshift_master_console_port=443
```
But the install fails at the point it's trying to start the master-api. Checking the master-config.yaml I can see that it includes config to bind to 0.0.0.0:443 however, the atomic-openshift-master-api journal shows it starting up and binding to 0.0.0.0:8443 - whilst attempting to connect to itself on 443 

(These masters are unschedulable, so I figured we could listen on port 443, since nothing else would be)

**Comment by abutcher** [comment]
@edseymour I gave this a try this morning and it seems to be working

Haproxy configuration is using 443
```
...
frontend  atomic-openshift-api
    bind *:443
    default_backend atomic-openshift-api
    mode tcp
    option tcplog

backend atomic-openshift-api
    balance source
    mode tcp
    server      master0 192.168.122.224:443 check
    server      master1 192.168.122.96:443 check
    server      master2 192.168.122.95:443 check
...
```

Master binding to 443
```
servingInfo:
  bindAddress: 0.0.0.0:443
```

```
Feb 16 09:57:39 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:39.589453    3260 start_api.go:102] Using a listen address override "0.0.0.0:443"
Feb 16 09:57:40 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:40.521971    3260 start_master.go:380] Starting master on 0.0.0.0:443 (v3.1.1.6)
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724781    3260 master.go:237] Started Kubernetes API at 0.0.0.0:443/api/v1
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724815    3260 master.go:237] Started Kubernetes API Extensions at 0.0.0.0:443/apis/extensions/v1beta1
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724821    3260 master.go:237] Started Origin API at 0.0.0.0:443/oapi/v1
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724826    3260 master.go:237] Started OAuth2 API at 0.0.0.0:443/oauth
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724830    3260 master.go:237] Started Login endpoint at 0.0.0.0:443/login
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724834    3260 master.go:237] Started Web Console 0.0.0.0:443/console/
Feb 16 09:57:41 master4.example.com atomic-openshift-master-api[3260]: I0216 09:57:41.724839    3260 master.go:237] Started Swagger Schema API at 0.0.0.0:443/swaggerapi/
```

**Comment by abutcher** [comment]
@thoraxe Not for production because it introduces a single point of failure. Any other load balancing solution like elb or f5 would be preferable

**Comment by thoraxe** [comment]
You can already introduce single points of failure with the installer. I don't see the difference. By extension you are saying that we don't support a single master in production.

**Comment by abutcher** [comment]
Fair but configurations that introduce single points of failure are not recommended

**Comment by thoraxe** [comment]
not recommended != unsupported

=)

**Comment by edseymour** [comment]
@abutcher Haproxy configuration is using 443
I'm using OSE GA 3.1.1

The installer fails at the point where it checks the master is up and running. 
master-config.yaml does include
```
servingInfo:
  bindAddress: 0.0.0.0:443
```

However, the /etc/sysconfig/atomic-openshift-master-api file overrides this in its options:
```
OPTIONS=--loglevel=2 --listen=https://0.0.0.0:8443 --master=https://192.168.100.72:8443
```

**Comment by abutcher** [comment]
@edseymour Yep, confirmed that the master branch is correctly configuring options.

```
OPTIONS=--loglevel=2 --listen=https://0.0.0.0:443 --master=https://master4.example.com
```

**Comment by edseymour** [comment]
@abutcher yep - fixed, using master branch has resolved this
