### ISSUE TITLE
master.server.crt in multi master setup does not contain expected value

### ISSUE THREAD

**Issue by ebalsumgo** [openshift/openshift-ansible#1376]
I dont think this is a problem but did notice it while researching and tackling a different issue. The master.server.crt contains the CN of one of my masters as an IP rather than what I would have expected and have my lb hostname or at the very least my public_hostname. The SAN contains... well everything including the lb and both masters hostnames and their IPs.

Either way, not sure that it is explicitly a problem, just seems like "not the right thing"

Also, I don't know how this may or may not impact internal communications

**Comment by abutcher** [comment]
The certificates are currently just flat out copied from the first master to all other masters and the SANs include all hostnames (all other master ip/hostnames and all service names). I'm changing this behavior in https://github.com/openshift/openshift-ansible/pull/1337 so that we generate the certificates per master using the first master's CA.

**Comment by abutcher** [comment]
Closing. Master serving certificates are created per master via #1337.
