### ISSUE TITLE
try again all hosts

### ISSUE THREAD

**Issue by jayunit100** [openshift/openshift-ansible#1381]
Problem:
Ansible needs to waits till machines are all available and reachable to start. 
- why? idempotance not gauranteed really, and  
- the larger the cluster, the less the gaurnatee that all inventories will be readily available.
- example: On EC2 using our internal accounts, I ran this 5 times today, and 5 times, the first pass failed because of inventories not being available the first time....  

Example solution:
.. I assume this is common in other clusters ...  what are people doing about this?  i assume everyone has a wait/loop hacked somewhere , this is what im doing... its a hack but it works.

```
cat <<EOF > tmp_reachable
- hosts: all
  gather_facts: true
  max_fail_percentage: 0
  tasks:
    - action: ping
EOF
scp tmp_reachable $MASTERNAME:/tmp/reachable.yml
until ssh $MASTERNAME -c "ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook /tmp/reachable.yml --private-key /home/ec2-user/.ssh/libra.pem -vvv"
 ; do
     echo "Try again ping task!"
done
```

Production Solutions:
- Should we put retry logic directly into the installer by adding a `retry` play ?
- _Alternative:_ I think ansible 2x has native retry functionality

**Comment by jayunit100** [comment]
cc @timothysc

**Comment by detiber** [comment]
@jayunit100 can you provide some more info on how the clusters you are using are provisioned?

While we currently only "support" the byo playbooks the main reason is for conformity in troubleshooting and documentation. For cloud provisioning there are much better ways to invoke the playbooks and you can leverage dynamic inventory scripts that would negate this issue completely.

In general I'd be adverse to adding a general retry over the entire playbook, since we would need to then have to determine the cause of the failure and use that to determine if we should retry or if we should fail at that point. Additionally, a retry by default may gloss over issues in the installation process that would then be more difficult to notice and triage.

We are working on Ansible 2.0 support (through community contributions), unfortunately it isn't a high priority item and we've not been able to devote internal resources to it yet: https://github.com/openshift/openshift-ansible/issues/686

As far as leveraging dynamic inventory and tying into the automated provisioning, I would suggest looking at the way that the playbooks in playbooks/aws/openshift-cluster configure the variables that are passed through to the common playbooks. Another example can be found in https://github.com/2015-Middleware-Keynote/demo-ansible/blob/master/playbooks/openshift_setup.yml

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
