### ISSUE TITLE
[playbooks/libvirt] CentOS-7-x86_64-GenericCloud doesn't match sha256

### ISSUE THREAD

**Issue by cben** [openshift/openshift-ansible#1384]
[followup to #954]
`bin/cluster create libvirt foo` currently fails out of the box due to CentOS-7-x86_64-GenericCloud.qcow2.xz failing sha256sum check.

http://cloud.centos.org/centos/7/images/ dir is presently in a confusing state (which I don't know where to report):

- The current expected checksum, last updated in #954 (9461006300d65172f5668d8875f2aad7b54f7ba4e9c5435d65a84a5a2d66e39b)
matches `CentOS-7-x86_64-GenericCloud-1510.qcow2.xz`.
- According to http://cloud.centos.org/centos/7/images/sha256sum.txt ,
  the no-version-suffix `CentOS-7-x86_64-GenericCloud.qcow2.xz` is *supposed* to have same content as `CentOS-7-x86_64-GenericCloud-1503.qcow2.xz`.
  But the actual content has checksum c2e16bab8b5283cae77deb5bb0aad0a494cd4aabcb5dc5c71363056e88b93c0f, so it matches `CentOS-7-x86_64-GenericCloud-1511.qcow2.xz`.
- The last version mentioned in `sha256sum.txt` and actually appearing in the directory is `1601`.
  To make things more confusing, `sha256sum.txt.asc` has no mention of any `1601`.

Mismatch with the .txt files aside, I think the playbook should point to a specific `-YYMM` version so that it won't break in the future whenever `CentOS-7-x86_64-GenericCloud.qcow2.xz` gets updated.
(I could send a PR but I don't know which version to use.  I've tried both 1510 and 1511, and got unrelated errors, so can't even attest what's "working for me".)

**Comment by detiber** [comment]
@cben thanks for the heads up.

@akram @codificat are either of you able to test which CentOS image would be best to use?

@kbsingh can you help out with the CentOS image related issues mentioned here?

**Comment by kbsingh** [comment]
Hi Folks, @detiber thanks for pulling me in.

Firstly, report any issues with the images or contents around them to the centos-devel list ( https://lists.centos.org/ ) if you want to talk through anything, or hit bugs.centos.org if you know there is a problem. Do both if needed.

Secondly, the non versioned images are meant to point at the latest released images ( in this case, that would have been 1601, but we found a major regression in the atomic images and haven't released the 1601 stack as yet. should happen within the next 24 hrs ). At that point we should have consistency in the sha sum's as well - if you hit any of the specific versions, it would always match the sha sum's. Because of how the CDN is setup, and how long it takes content to cascade down, I dont want to put in an interim change, then change it all again when 1601 releases tomorrow AM UTC.

However, I will investigate why we have the symlinks moved, without the corresponding sha sum's changed.

**Comment by cben** [comment]
Thanks.
I saw 1602 is there now.  [Sent [some feedback to centos-devel](https://lists.centos.org/pipermail/centos-devel/2016-February/014435.html)]
My previous issues went away, now `bin/cluster create libvirt` worked with both -1510 and -1602 images.  Sending a PR.

**Comment by akram** [comment]
sorry for late answer and thank you for raising this issue.
The sha256 could be of course overriden in all cases, even if default value is not consistent with the release.
