### ISSUE TITLE
Real Dev clusters from zero

### ISSUE THREAD

**Issue by jayunit100** [openshift/openshift-ansible#1406]
Given an EC2 User name, password, and SSH Key, developers should be able to spin up an N node cluster using Openshift ansible on either RHEL or Fedora.

This should involve having to read any docs at all.  Possibly it could be a downstream product if its not easily abstracted to work on Fedora.

For downstream folks, I've created the github repo at roofmonkey/vagrant-centos-bd4/ec2-openshift: export 4 vars and up.sh.  It also hosts a shell script for building from source.  

Should we integrate it here ?

cc @smarterclayton @timothysc @danmcp

**Comment by jayunit100** [comment]
To clarify (since there are already so many utilities out there)

The goal here is "not" fleixbility: 
- Its something that scales 
- that we can agree on
- that can run on RHEL

Similar to the GCE kube-up.  I'm NOT attached to my implementation at all, but happy to use it as a starting point.   I'll defer to any other implementation that:

- can spin up a single cluster 
- at the click of the button 
- from source

**Comment by timothysc** [comment]
I debate where the best home for this might be...

**Comment by jayunit100** [comment]
Agree open to ideas on that to. For now it has an apartment,  but the goal is to collaboratively maintain it.

**Comment by detiber** [comment]
This is exactly what bin/cluster was originally designed for...  That said, the way that bin/cluster calls into  the common playbooks is sufficiently different than the way that we call into them using the byo playbooks.

That said, even with this use case, there is still need for a certain degree of flexibility. For example:
- What product to deploy (AEP, OSE, Origin)
- What version to deploy (latest released, earlier release, latest from source)
- tweak different variables for replicating different issues and/or testing different configurations

I'm perfectly fine with whatever the solution is to start with a smaller subset, but generally I see the issue is as follows:
- spin up development/test hosts (this is by far the least flexible part of the process, we can have a certain rigidity of what settings are tweakable and which are not).
- if deploying from source, build packages from source and expose through a yum repo.
- map the hosts from the dynamic inventory to groups that are recognized by the byo playbooks.
- read in a configuration file (preferably yaml, to avoid having to 'json encode' strings) that are then applied to the created groups/hosts
- call the byo playbooks

**Comment by detiber** [comment]
@jayunit100 I'd like to discuss the differences/similarities between the approaches and consolidating approaches more after I return back from DevNexus.

**Comment by timothysc** [comment]
xref: https://github.com/openshift/origin/issues/7219

**Comment by jayunit100** [comment]
@detiber SGTM.  Till then ill independently curate my recipe, which is vagrant based, and which follows what you prescribed (dyn inventory, builds own packages/hosts repo, use byo playbooks).

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
