### ISSUE TITLE
Unify atomic-openshift-master{,-api,-controllers} sysconfig

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#1443]
Followup to issues identified in #1385

**Comment by detiber** [comment]
So, the goal would be to consolidate down to just a single /etc/sysconfig/{atomic-openshift,origin}-master file and update the systemd units to all source the same env?

Overall, I like the idea, since it would reduce duplication, but we may need to consider doing that only for new installs and supporting the multiple files for existing installs to avoid clobbering user-edited configs.

Maybe a test to see if /etc/sysconfig/<unit-name> exists and if so use it, otherwise use the common env file?

**Comment by sdodson** [comment]
We can specify multiple environment files so we could load the common file, then load the more specific file in that order.  I keep meaning to look at the systemd unit templating article you sent my way but I never get to it. I think we should also consider that in part of this work.

TBH I haven't given this a whole lot of thought other than I wanted to make sure we had a followup issue to work on it, I didn't want to try to fix that in the global proxy pr just yet.

**Comment by detiber** [comment]
makes sense. I like the idea of loading the common env file and overriding just what is needed in the unit specific env file.
