### ISSUE TITLE
BYO: routers are not being created

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#1532]
I am using a byo playbook and the router is not being created.  I was told by @abutcher that the router is being hardcoded here:

https://github.com/openshift/openshift-ansible/blob/master/playbooks/common/openshift-master/config.yml#L184-L186

We just need the router to be installed on the infra nodes.

I have spoken with both @abutcher and @detiber  and they understand the issue.

Thanks!

**Comment by abutcher** [comment]
Thinking something like this:
* allow the node label signifying "this is an infrastructure node" to be configurable so that `openshift_something_infra_label="corn=beans"` or anything else would work
* the infrastructure node label would default to `"region=infra"` if there is a good reason to maintain the region label OR we could default to `"type=infra"`? @detiber 
* this label would become the default selector for the router and registry but each could be overridden

**Comment by detiber** [comment]
I like the idea of defaulting to type=infra, though we need to make additional adjustments to make it work right.

Mainly,  we'd need to set the default project node selector to exclude the type=infra, we'd also need to address this issue https://github.com/openshift/openshift-ansible/issues/1358
