### ISSUE TITLE
Systems don't unsubscribe with libvirt

### ISSUE THREAD

**Issue by jdnieto** [openshift/openshift-ansible#1652]
I'm using Red Hat subscription to create a libvirt cluster with "bin/cluster".
Everything deploys good, systems are subscribed and attached to a pool. But everytime I run "bin/cluster terminate" I get:
```
TASK: [rhel_unsubscribe | Remove RedHat subscriptions] ************************ 
skipping: [dmartin-node-compute-885c9]
skipping: [dmartin-master-83eeb]
skipping: [dmartin-node-compute-4741e]
skipping: [dmartin-node-infra-05bfa]
```

And I need to manually remove systems from Red Hat page.

**Comment by detiber** [comment]
@jdnieto can you provide more info on what options you are passing to bin/cluster? 

While I think we can improve the logic used for determining if systems are subscribed/unsubscribed (using the `bool` filter instead of `| lower in ['no', 'false']` for the tests, I would expect that to cause issues with registration as well as unregistration.

Without more context, the first thing that comes to mind would be to make sure that you are passing the `-t` flag to bin/cluster terminate, otherwise it will default to 'origin' which would cause the rhel_unsubscribe role to be skipped.

**Comment by jdnieto** [comment]
You can look two billion times and see nothing. I have a TYPO instead "enterprise" I wrote "enterpirse". I was using aliases :astonished:
