### ISSUE TITLE
Detect docker-registry ip and add them to NO_PROXY hosts

### ISSUE THREAD

**Issue by jkroepke** [openshift/openshift-ansible#1919]
Since docker does not support CIDR in NO_PROXY, it would be awesome automatic detect the registry ip and add them to dockers' NO_PROXY environemnt variable.

**Comment by detiber** [comment]
@sdodson were we waiting on enabling dns for the registry to support this?

I know we wanted to avoid adding all of the IPs in the service IP range to the list. Alternatively, we could create the registry with a fixed service IP (say the second IP in the service network CIDR), and then automatically add that address to the no proxy list.

**Comment by sdodson** [comment]
Yeah, we were expecting to be able to push to the registry using its hostname rather than IP address but we found out just before 1.2/3.2 release that doesn't work and it looks like making that work won't come in until 1.3/3.3.

One recommendation that someone made was that we could go ahead and create the service early on even if we're not creating the actual registry. I'd want to try that out.

**Comment by sdodson** [comment]
Yeah, we were expecting to be able to push to the registry using its hostname rather than IP address but we found out just before 1.2/3.2 release that doesn't work and it looks like making that work won't come in until 1.3/3.3.

One recommendation that someone made was that we could go ahead and create the service early on even if we're not creating the actual registry. I'd want to try that out.

**Comment by cpitman** [comment]
Is there a reason not to add the entire services CIDR to the no_proxy set?

**Comment by sdodson** [comment]
> Is there a reason not to add the entire services CIDR to the no_proxy set?

Docker can't handle CIDRs in NO_PROXY. https://github.com/docker/docker/issues/9145

**Comment by fgiloux** [comment]
How far are we to have that fixed? Another option may be to let the user specify an IP address for the registry service from his CIDR in the ansible inventory, so that he can also specify this address in his no_proxy configuration?

**Comment by garethahealy** [comment]
Any movement on this? Have a customer asking.

**Comment by bahho** [comment]
Still the same. With atomic-openshift-utils.noarch : 3.4.67 : 1.git.0.14a0b4d.el7 the ip of the internal registry is not added to NO_PROXY in the docker config. 
It would be great if the ip was added to ADD_REGISTRY and INSECURE_REGISTRY options automatically, as well.

**Comment by jkroepke** [comment]
Closed, since the registry is available via dns name by default.
