### ISSUE TITLE
three master install fails. master-2 object has been modified

### ISSUE THREAD

**Issue by juddmaltin-dell** [openshift/openshift-ansible#1934]
Installing with openshift-on-openstack heat templates, making great progress, however:

https://gist.github.com/98435cadb22bee00b43599c260d794b6

```
stderr: Error from server: node "openshift-openshift-master-2.example.com" cannot be updated: the object has been modified; please apply your changes to the latest version and try again
```

I see that master-2 had some trouble coming up for a while, waiting for storage, it seems.  Race condition?  Should I post the rest of the logs from my install?

**Comment by abutcher** [comment]
We should move node labels to the node config but I think we could add some retries to these two tasks (labels, schedulability) as a workaround.

@deads2k does retrying seem like the right approach here? Is there an upstream issue that you know of wrt `cannot be updated` or is this expected in some cases?

@juddmaltin-dell yes, please post the rest of the logs if there were other issues.

**Comment by deads2k** [comment]
> @deads2k does retrying seem like the right approach here? Is there an upstream issue that you know of wrt cannot be updated or is this expected in some cases?

In the case of colliding updates, the first one in wins, the others are rejected since every field is stomped (think full column replacement in sql).  The (usually) better alternative is to create a patch and use `oc patch` to apply it.  Instead of stomping every field, it selectively targets a given field (update a single column in sql).  Because of that targeted behavior, it will attempt to re-apply itself server-side as long as there has not been a conflicting change.

**Comment by deads2k** [comment]
Oh, and with regard to the specific question, you should pull the new object, update the single field you want to change (along with re-evaling the condition that made you choose to update), and try again.

**Comment by sdodson** [comment]
@juddmaltin-dell Is this still an issue? I believe we've made improvements in this area.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
