### ISSUE TITLE
Unable to use use_cluster_metrics (openshift.common.use_cluster_metrics)

### ISSUE THREAD

**Issue by gaelL** [openshift/openshift-ansible#2048]
Hi,

I tried to use `use_cluster_metrics = true` (https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L31)

To configure kubernetes read-only-port. In the template : `roles/openshift_node/templates/partials/kubeletArguments.j2`

```
{% if openshift.common.use_cluster_metrics | bool %}
kubeletArguments:
  "read-only-port":
    - "10255"
{% endif %}
```

But the `openshift.common.use_cluster_metrics` fact still false. See : 

```
ansible-playbook playbooks/byo/openshift_facts.yml | grep use_cluster_metrics
                        "use_cluster_metrics": false, 
                        "use_cluster_metrics": false, 
                        "use_cluster_metrics": false, 
                        "use_cluster_metrics": false, 
                        "use_cluster_metrics": false, 
```

Did I miss something ?

Regards,

**Comment by abutcher** [comment]
It looks like we aren't persisting the fact within `roles/openshift_common/tasks/main.yml` with the [other common facts](https://github.com/openshift/openshift-ansible/blob/5c095116ff23ee1ccbe6ba0407cff0fb05d9980d/roles/openshift_common/tasks/main.yml#L18-L30). This is causing the default value of `False` to be used even when `use_cluster_metrics` is configured otherwise.

**Comment by abutcher** [comment]
I think this is getting cleaned up in https://github.com/openshift/openshift-ansible/pull/1978 /cc @sdodson

**Comment by sdodson** [comment]
@gaelL please see the description of #1978 for the proper method to deploy metrics and followup additional docs in #2369
