### ISSUE TITLE
OpenShift pod metrics-deployer deploys more than once

### ISSUE THREAD

**Issue by jdnieto** [openshift/openshift-ansible#2051]
When deploys OpenShift with `openshift_hosted_metrics_deploy=True` it creates a pod called **metrics-deployer-????** based on a template in **openshift-examples/files/examples/latest/infrastructure-templates/{origin,enterprise}/metrics-deployer.yaml**. If ansible runs more than once the template is processed again and it creates a new **metrics-deployer-????** pod ends in Error state.
Should be changed  template from:
`generateName: metrics-deployer-`
to
`name: metrics-deployer`

**Comment by sdodson** [comment]
@mwringe what do you think about staticly defining the metrics-deployer pod name a protection against multiple automated installs? A bit of additional context here, we're in progress of making it so that ansible will automatically deploy metrics when users install via the installer. So if a user were to re-run the installer they'd potentially get the metrics deployer deployed multiple times. What's the safest/most proper thing to do in those scenarios?

**Comment by mwringe** [comment]
@sdodson assuming metric components are not part of the installer, what happens exactly when the installer is re-run?

**Comment by sdodson** [comment]
@mwringe it should be idempotent, it should ensure everything completed the first time around is re-done if necessary or skipped if it's already in the desired state.  Perhaps we should set REDEPLOY?

**Comment by mwringe** [comment]
@sdodson 'redeploy' will nuke everything, including persisted volumes, and then restart everything. We have a 'refresh' option which is similar to redeploy, but its keep the persisted data and routes. But we don't have a 'redo only this component if its in error' option. Maybe we need something like that

**Comment by detiber** [comment]
Do we really need to mess with the generated name of the metrics deployer? It almost seems as if we should have a good way to validate the metrics deployment without the deployer involved so that we can determine if there is a need to invoke the deployer for metrics at all? Or maybe that should just be a function of the deployer itself...  say a refresh if needed command?
