### ISSUE TITLE
RFE: Make adding different types of identity providers easier to the inventory file

### ISSUE THREAD

**Issue by mwoodson** [openshift/openshift-ansible#2083]
Let me preface this by saying this isn't an easy issue to solve.  But this is one that I would like to get some improvements on.  It would help Openshift Ops quite a bit.

**The current problem:**

We are using the BYO inventory file to configure a lot of clusters with all sorts of authentication schemes.  There is one variable to configure all of these:

_openshift_master_identity_providers_

Then, we need to set this var as a json dict.  There are multiple problem with this:
- there is no good examples with all of the different supported auth types (at least I couldn't find them)
- the auth types don't have all of the options documented. (https://gist.github.com/detiber/da042623b26522fcd5767825eafe97a0 as an example)
- the dictionaries that are needed do NOT line us with official docs of the auth type.  What i mean by this, we pass in a dictionary of values that are then put in the right place in the yaml code by the byo.  For example, I can't look at https://docs.openshift.com/enterprise/3.2/install_config/configuring_authentication.html and come up with what the json dictionary should be.
- each dictionary takes different options depending on the auth type.
- the dictionaries are hard to read
- not all options in the dict are needed. It's hard to know what is, what isn't.  IT would help if this was lined up with documents.

**Comment by mwoodson** [comment]
I would like to brainstorm on the possible outcome.  I would love to hear other's thoughts.

Here is one of the suggestion that could help solve the issue.  Take this for what it's worth.

What if a variable was added like:

openshift_master_identity_type=

This would be one of the types of id that openshift supports.  It could be "google", "github", "openid", "htpasswd", etc...

Then, there would be a list of required or variables that go with each provider type.  I would envision each type having it's own set of variables that are needed.  If the option isn't required, the byo should handle that appropriately. For example, if 

openshift_master_oauth_type=google

We would then have other variable that are used:

openshift_master_oauth_google_provider_clientID=<tbd>
openshift_master_oauth_google_provider_clientSecret=<tbd>
openshift_master_oauth_google_provider_hostedDommain=<tbd>

There could be oauth level ones that map accross all types of auth.  For example, the higher level ones could be something like:

openshift_master_oauth_mappingMethod=lookup

This could be documented fairly easily.  We could add additional variables based on the oauthConfig found in the docs and in the config file. 

I think this would be much easier than the existing dictionary.  This would also line up with what is in the docs and follow the oauthConfig dictionary found in the master-config.yml.

**Comment by detiber** [comment]
Just wanted to add another consideration to the list. It is currently possible to configure multiple providers of the same type currently (2 google identity providers that are tied to different domains for example) as long as the name attribute on the identity provider config is specified...  

We definitely need to provide a better experience outside of the complex variable we currently expose, but how that is done isn't clear to me yet. 

@mwoodson there are definitely components of your proposal that I like very much, since it is clear what is being configured, I just wonder if throwing in things like falling back to openshift_master_oauth_* for the github, google, gitlab, etc providers is the right answer, since it seems like it may actually detract a bit from the simplicity both in end user use and in the implementation.

I do think that we should (at some point) refactor the identity provider complex variable to support the upstream syntax instead of the failed attempt at simplification that I originally created.

Just spitballing here, but maybe the right answer is to provide a simplified interface for a limited number of identity providers (ideally 1, but I could be convinced to go for 2 or 3), and any configuration beyond that would require dropping down to the complex variable. We could even have a filter that translates from the simplified interface to the complex interface (which could then potentially remove the need for limiting it to just a small number of providers).

@abutcher thoughts?

**Comment by mwoodson** [comment]
Filed a bug here:

https://bugzilla.redhat.com/show_bug.cgi?id=1357061

**Comment by mwoodson** [comment]
@detiber  If you could have a simple version that worked for a handful of auth providers, I would support that.  But when we start jamming in data structures into a single variable, in my opinion that loses it's simplicity.  I am not against providing  something simple, but I do want the flexibility to put in something.

I'd be ok with being able handing over a "final configuration chunk", something that the final output would like in master-config.yml, and then you put it in place as one of the auth types.  We could store our auth  variables in yaml at that point, hand them to the installer, and just have it do the right thing.  Then you could keep a simple and have this way be the "advanced" config.  

Hmm, the more I think about this, the more I like this.  The advantages are:

- we could use official documentation for the right variables.  We wouldn't have to guess how they will be interpreted and then converted
- we could use this to check against the master config  with config management.
- it should be easy for you, and then not have to write all sorts of different variables for different advanced auth types, and maintain them.  It's just pure yaml.

I like this this idea, thoughts from you guys?

**Comment by detiber** [comment]
> I'd be ok with being able handing over a "final configuration chunk", something that the final output would like in master-config.yml, and then you put it in place as one of the auth types. We could store our auth variables in yaml at that point, hand them to the installer, and just have it do the right thing. Then you could keep a simple and have this way be the "advanced" config.

Yes, this is pretty much what I had in mind. The "simplification" in place now was a failed experiment. In the future we will keep in line with upstream configs for things like this.

That said, the big pain with complex vars right now is mainly due to the use of the inventory file and the serialization/deserialization process.


> Hmm, the more I think about this, the more I like this. The advantages are:

> - we could use official documentation for the right variables. We wouldn't have to guess how they will be interpreted and then converted

100% agree

> - we could use this to check against the master config with config management.
> - it should be easy for you, and then not have to write all sorts of different variables for different advanced auth types, and maintain them. It's just pure yaml.

I mostly agree, we do need to do validation, but my thinking on this now is to potentially leverage json schema to do the validations.

> - we are not converting things back and forth. If an advanced user wants to put in the auth, one can just do it this way, not having to worry about the way it should look.

Agreed, the upstream docs should be the reference for complex vars like this. I originally tried to make it feel more native to ansible and that was a mistake.

**Comment by tbielawa** [comment]
> I mostly agree, we do need to do validation, but my thinking on this now is to potentially leverage json schema to do the validations.

You can tap me If we do go down the json schema route, I've got experience writing schemas from work during the [Inception Era](https://github.com/RHInception/re-common/tree/master/schemas).

**Comment by detiber** [comment]
@tbielawa nice! I don't think we'll be going down that route too soon, but it's something that was brought to my attention by the ci/cd work and seems like a much better way to do validation rather than the way we've been doing it up until this point.
