### ISSUE TITLE
ansible_connection=local is added automatically by the installer when using hostnames via the quick installer

### ISSUE THREAD

**Issue by alongoldboim** [openshift/openshift-ansible#2262]
@simon3z @dkorn @smunilla @sdodson 
We are using ssh connection to execute the playbook on remote vm and then disconnecting hence we need the vm to create an ssh connection to itself and supply tty to the process.
Using hostnames in the installer causes it to append ansible_connection=local to the local vm, this behavior should be optional not mandatory.
http://pastebin.com/W0cNth4a (inventories, ansible.log), the only difference in the config files that were used to create those inventories is the  "connect_to: 10.35.48.24" to
 "connect_to: vm-48-24.eng.lab.tlv.redhat.com".

**Comment by alongoldboim** [comment]
@smunilla waiting for alternative fix, this is important to get off our list :) thanks.

**Comment by smunilla** [comment]
@alongoldboim I'm working on it. I just want to make sure all our bases are covered for interactive installs.

**Comment by detiber** [comment]
@alongoldboim So, the main reason that we are updating the connection to be a local connection is that we've had intermittent issues where the ssh connection back to itself is severed during the iptables configuration step. Can you provide info on the error you are seeing when the connection back to itself is local rather than over ssh?

**Comment by alongoldboim** [comment]
@detiber Yea, we are using the openshift-installer in the following way:
```
SSH_AUTH_SOCK=socket nohup sudo -b -E atomic-openshift-installer -u -c /usr/share/ansible/openshift-ansible/inventory.yaml install 1> ANSIBLE_LOG 2> #ANSIBLE_ERROR_LOG < /dev/null
```
When we don't connect through ssh then there is no tty supplied, and then playbook fails.

**Comment by detiber** [comment]
@alongoldboim is it not possible to allocate a ptty when invoking the installer? I can't say I'm familiar with using SSH_AUTH_SOCK in that way

**Comment by alongoldboim** [comment]
@detiber any suggestions on how I can allocate it?

**Comment by detiber** [comment]
@alongoldboim not using SSH_AUTH_SOCK, I've never seen using that env var for executing a binary instead of just passing host auth through to the client.

Assuming you are using net-ssh to make the remote connection, it is possible to call the request_pty method on the Channel, more info is available here: http://net-ssh.github.io/net-ssh/Net/SSH/Connection/Channel.html

**Comment by alongoldboim** [comment]
@detiber The only problem is that we need to execute the installer and disconnect because we can't keep the connection open, once we disconnect we lose the pty.

**Comment by detiber** [comment]
@alongoldboim ah, I think I finally understand. Out of curiosity, how are you validating the installation if the connection is closed after initiating the installer?

@smunilla I'm good with allowing for an override of this behavior when using an unattended install, I think we still need the default behavior to be the normal behavior, though.

**Comment by smunilla** [comment]
@detiber Yeah my plan is to add it by default during interactive mode, but give users the ability to not include it (or edit it out of the file interactive mode generates)
