### ISSUE TITLE
Uninstall playbook fails to clean up /var/lib/etcd when it has its own mount point

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#2317]
We often recommend mounting /var/lib/etcd separately from /var for disk write stability. When we do this, the uninstall playbook fails on running `rm -rf /var/lib/etcd` because it's a mounted disk. You'll see an error like 'device or resource busy'.

Is there any reason not to simply change this to `rm -rf /var/lib/etcd/*` or should there be more error checking?

cc: @abutcher @detiber

**Comment by detiber** [comment]
@etsauer I think /var/lib/etcd/* should be fine.

Out of curiosity, though is this being done simply as a way to better facilitate using lvm loop rather than adding an additional device for handling docker storage through lvm thin pool? Or is there additional value in separating out /var/lib/etcd even when using a thin pool for storage? If there is a good reason to recommend the separate volume, we probably want to surface that up to the official docs.

**Comment by etsauer** [comment]
@detiber no we have a specific rule for etcd's storage for long running environments: protect its disk. If it's disk fills up and it can't write, it causes outages and (for older versions) could permanently corrupt the cluster.

**Comment by detiber** [comment]
@etsauer I just realized that while attempting to multitask I was thinking /var/lib/docker rather than /var/lib/etcd. Apologies for the confusion/noise.
