### ISSUE TITLE
Silent error if openshift_master_identity_providers setting incorrect or malformed

### ISSUE THREAD

**Issue by edseymour** [openshift/openshift-ansible#2513]
If you add a openshift_master_identity_providers setting which is not accepted, for some reason, then this is not reported as a error. However, the side-effect of the error is that the checks to determine if httpd-tools should be installed fail (see issue https://github.com/openshift/openshift-ansible/issues/2321)

OpenShift 3.3 RPM Version: atomic-openshift-utils-3.3.22-1.git.0.6c888c2.el7.noarch
Ansible version: 2.2.0
##### Steps To Reproduce
1. add malformed or incomplete configuration in Ansible inventory file for the property `openshift_master_identity_providers` 
##### Current Result

Failure message for each master:

```
atal: [poc-master-1-1]: FAILED! => {"failed": true, "msg": "The conditional check '(item.kind == 'HTPasswdPasswordIdentityProvider') and not openshift.common.is_atomic | bool' failed. The error was: error while evaluating conditional ((item.kind == 'HTPasswdPasswordIdentityProvider') and not openshift.common.is_atomic | bool): 'unicode object' has no attribute 'kind'\n\nThe error appears to have been in '/usr/share/ansible/openshift-ansible/roles/openshift_master/tasks/main.yml': line 79, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install httpd-tools if needed\n  ^ here\n"}
```
##### Expected Result

A message reporting a failure specific to the `openshift_master_identity_provider` setting, i.e. not a side-effect.

**Comment by michaelgugino** [comment]
Hello,

  Thank you for reporting this issue.  Unfortunately, a malformed variable can affect things in surprising ways.  It is not practical to check each variable for 100% correctness before utilization.

The correct usage of openshift_master_identity_providers is documented here:  https://docs.openshift.org/latest/install_config/configuring_authentication.html#identity-providers-ansible

I am closing this bug because usage is correctly documented.
