### ISSUE TITLE
Support for Encrypted bindPasswords in openshift_master_identity_providers

### ISSUE THREAD

**Issue by etsauer** [openshift/openshift-ansible#2594]
I would like to know whether the installer has support for managing an external or encrypted file for bindPasswords in the openshift_master_identity_providers. It looks like from the sample inventories, that there is currently no way to provide a key file, nor is there a way to just provide the password and request that the playbook run the necessary `oadm ca encrypt` command to create it. I would like to request it be added if it's not already. 

Documentation: https://docs.openshift.com/container-platform/3.3/install_config/master_node_configuration.html#master-node-configuration-passwords-and-other-data
##### Version

Latest
##### Steps To Reproduce

n/a
##### Current Result

n/a
##### Expected Result

n/a
##### Additional Information

n/a

**Comment by detiber** [comment]
@smunilla ptal

**Comment by gregswift** [comment]
I'd like to second this with some further justification.  We manage our inventory file in git, as i think one would expect.  But we can't manage the bindPassword in our git repositories.  Because of this everyone has a locally edited copy of the inventory files, which complicates sharing.  

In theory we could move this to a vault file, but even that doesn't seem _easy_ to integrate consistently in this playbook. Commonly this would either be called out as a variable file in the playbooks or placed in the group_vars. Either of those methods require modifications to the main openshift-ansible structure that now create a fork that has to be managed.

Alternatively, you can pass an answer file separately
```ansible -i blah -e "@identity_provider.yml" --ask-vault-pass byo/config.yml ``` But then we have to ensure everyone always remembers the answer file.  Yes, its doable... just pointing out how it can be problematic.

**Comment by michaelgugino** [comment]
You can use a vault encrypted file in group_vars/all directory and it will always be included, no need to use extra_vars.
