### ISSUE TITLE
Need generic way to deploy with a specific CNI plugin

### ISSUE THREAD

**Issue by yfauser** [openshift/openshift-ansible#2698]
I am working on integrating our network virtualization product (NSX) with OpenShift using CNI.
I'm deploying OpenShift in my Lab using the BYO playbooks.

When deploying OpenShift with BYO, I don't want to install OpenShift SDN, I only want to the network plug-in name in the master and node config to be 'cni':

```
os_sdn_network_plugin_name=cni
openshift_use_openshift_sdn=false
```

I found that this is not working and added a quick fix to get around this:
https://github.com/yfauser/openshift-ansible/commit/ee2f9daacea2f84d9f7917bcbae38648bd359191

While this is a quick fix, I would rather want to suggest a generic way to handle cases like ours.
Instead of having a separate flag per network plugin vendor, like used in the Nuage and Flannel case, it would be great to be able to specify the cni config file in the [OSEv3:vars] e.g. like:

```
openshift_use_openshift_sdn=false

os_sdn_network_plugin_name=cni
os_sdn_network_cni_netconf=<file or template name>
os_sdn_network_cni_netbinary=<file or template name>
```

or

```
openshift_use_openshift_sdn=false

os_sdn_network_plugin_name=cni
os_sdn_network_cni_package=<rpm to install>
```

What do you guys think?

Also, let me know if you want to receive a pull request for the above 'quick fix'

Thanks!

##### Version
▶ git describe
openshift-ansible-3.4.14-1-5-gee2f9da

▶ ansible --version
ansible 2.1.1.0

Centos7.2 used as base OS

**Comment by detiber** [comment]
> Instead of having a separate flag per network plugin vendor, like used in the Nuage and Flannel case, it would be great to be able to specify the cni config file in the [OSEv3:vars] e.g. like:

```
openshift_use_openshift_sdn=false

os_sdn_network_plugin_name=cni
os_sdn_network_cni_netconf=<file or template name>
os_sdn_network_cni_netbinary=<file or template name>
```
> or

```
openshift_use_openshift_sdn=false

os_sdn_network_plugin_name=cni
os_sdn_network_cni_package=<rpm to install>
```

> What do you guys think?


I love the idea. Currently the flannel and nuage configurations we support do not leverage CNI, but I think the addition of generic CNI configuration would be a great addition.

Out of the two suggested configurations, I prefer the package-based approach, since it would line up more with customer expectations for package-based installations of OpenShift. That said, there would need to be a container available for the CNI plugin to work on containerized installations. I can also see the need to be able to specify/override config. I think maybe a combined approach that allowed you to specify a package (or a container image) and optionally specify config would cover all of the use cases.

> Also, let me know if you want to receive a pull request for the above 'quick fix'


Please do, I think it's a good stop-gap until we can provide a better interface for specifying CNI configuration.

**Comment by yfauser** [comment]
Thanks! I submitted a pull request for the 'quick-fix'.

I will start working on a the above suggested generic way to deploy CNI Plugins and send you pulls for review in the next few weeks.

**Comment by djosborne** [comment]
@yfauser any update / work done on this yet?

**Comment by yfauser** [comment]
@djosborne I did not have the time to work on this in a concentrated way, but I'm planning to spend time on this in the first two weeks of January. Do you have CNI based work where you have RPMs that I could try to deploy?

**Comment by djosborne** [comment]
@yfauser I have a CNI plugin I'd like to add, but unfortunately it is not packaged as an RPM. I guess due to its custom installation requirements, it would probably have to be added as a playbook regardless of the work you've outlined here. I'll follow your work in case there's any rewrites of the growing number of `openshift_use_X` variables which I think the only piece that could affect me.

**Comment by djosborne** [comment]
@yfauser just raised #3022 , thought you might be interested, but didn't want to bloat the conversation here :)
