### ISSUE TITLE
Redeploy certificates

### ISSUE THREAD

**Issue by fesenko** [openshift/openshift-ansible#2830]
I set up an OpenShift cluster on AWS. The cluster's configuration as the following:

- one master;
- two compute nodes;
- one infra node.

Can I use the following command to redeploy certificates?

`ansible-playbook  -i inventory/aws/hosts -e 'cluster_id=<cluster_name> cluster_env=dev deployment_type=origin' playbooks/common/openshift-cluster/redeploy-certificates.yml`

When I execute the command I don't see the cluster's nodes affected, only localhost.

##### Version
git describe openshift-ansible-3.4.17-1-133-gf5d74f4
ansible 2.2.0.0
Amazon Linux AMI release 2016.03

Thanks

**Comment by abutcher** [comment]
Hey @fesenko, the entry point for this playbook is `playbooks/byo/openshift-cluster/redeploy-certificates.yml` rather than the `/common/` playbook. That said, the byo playbook won't properly set up host groups based on instance tags with a dynamic inventory.

The missing piece here would be an aws entry point for redeploying certificates. Take a look at the differences between [playbooks/byo/openshift-cluster/config.yml](https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-cluster/config.yml) and [playbooks/aws/openshift-cluster/config.yml](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/openshift-cluster/config.yml).

The aws entry point for config includes [cluster_hosts.yml](https://github.com/openshift/openshift-ansible/blob/master/playbooks/aws/openshift-cluster/cluster_hosts.yml) vars which translate groups based on instance tags to the groups that openshift-ansible expects to exist. An aws entry point for redeploying certificates would set things up similarly and then call into the common playbook for redeploying certificates.

**Comment by fesenko** [comment]
@abutcher, thank you
