### ISSUE TITLE
Create libvirt cluster returns no such file or directory

### ISSUE THREAD

**Issue by dtpest** [openshift/openshift-ansible#2863]
##### Version
ansible 2.2.0.
openshift-ansible-3.4.17-1-158-g90fb07f

##### Steps To Reproduce
git clone https://github.com/openshift/openshift-ansible.git
cd openshift-ansible
bin/cluster list libvirt '' <- OK
bin/cluster create libvirt lenaic 

##### Current Result
failed: [localhost] (item=lenaic-master-cc363) => {"failed": true, "item": "lenaic-master-cc363", "msg": "Cannot access storage file '/home/labuser/libvirt-storage-pool-openshift-ansible/lenaic-master-cc363-docker.qcow2' (as uid:1124, gid:78): **No such file or directory**"}

##### Expected Result
Starting VM's

##### Additional Information
Tried as root-user and also as own user.
virsh -c qemu:///system pool-list <- ok
libvirt_storage_pool_path <- set variable with "-o" - path is changed, but same issue

**Directory content:**

- CentOS-7-x86_64-GenericCloud.qcow2
- CentOS-7-x86_64-GenericCloud.qcow2.xz
- lenaic-master-31bf5_configdrive
- lenaic-master-bb99e_cloud-init.iso
- lenaic-master-bb99e_configdrive
- lenaic-master-cc363_cloud-init.iso
- lenaic-master-cc363_configdrive

**Comment by sdodson** [comment]
@lhuard1A mind taking a look at this?

**Comment by lhuard1A** [comment]
Hello @dtpest,

Could you please provide:

* the ansible logs that are preceding your error. Something like that:
```
TASK [Create the cloud-init config drive path] *********************************
changed: [localhost] => (item=lenaic-node-compute-c9010)

TASK [Create the cloud-init config drive files] ********************************
changed: [localhost] => (item=[u'lenaic-node-compute-c9010', u'user-data'])
changed: [localhost] => (item=[u'lenaic-node-compute-c9010', u'meta-data'])

TASK [Create the cloud-init config drive] **************************************
changed: [localhost] => (item=lenaic-node-compute-c9010)

TASK [Refresh the libvirt storage pool for openshift] **************************
changed: [localhost]

TASK [Create VM drives] ********************************************************
changed: [localhost] => (item=lenaic-node-compute-c9010)

TASK [Create VM docker drives] *************************************************
changed: [localhost] => (item=lenaic-node-compute-c9010)

TASK [Create VMs] **************************************************************
changed: [localhost] => (item=lenaic-node-compute-c9010)

TASK [Start VMs] ***************************************************************
changed: [localhost] => (item=lenaic-node-compute-c9010)

TASK [Wait for the VMs to get an IP] *******************************************
FAILED - RETRYING: TASK: Wait for the VMs to get an IP (60 retries left).
FAILED - RETRYING: TASK: Wait for the VMs to get an IP (59 retries left).
FAILED - RETRYING: TASK: Wait for the VMs to get an IP (58 retries left).
```
what I’m really interested in is the `Create VM docker drives` task. It is the one that creates the `<clusterid>-master-<id>-docker.qcow2` file.

* the full content of `~/libvirt-storage-pool-openshift-ansible/`
* the output of `virsh -c qemu:///system vol-list --pool openshift-ansible`

According to your inputs, since you have the `clusterid>-master-<id>_cloud-init.iso` files, the [`Create the cloud-init config drive`](https://github.com/openshift/openshift-ansible/blob/master/playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml#L52) task was successful.
I guess the error message you pasted was coming from the [`Create VMs`](https://github.com/openshift/openshift-ansible/blob/master/playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml#L70) task.
So, the question is: « What went wrong during the [`Create VM *drives`](https://github.com/openshift/openshift-ansible/blob/master/playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml#L62) tasks ? »

If the `Create VM *drives` task is well in `changed` state with no error, then try to launch `bin/cluster` in verbose mode so that we have the full command line that was issued by Ansible.

**Comment by dtpest** [comment]
Does work now with the new Ansible version
