### ISSUE TITLE
make ci is too slow

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#2933]
Running tests locally with `make ci` is disconcertingly slow, and there seems to be ways of improving it:

For a local development flow:
- [ ] do not recreate a virtualenv in every run
- [ ] print clearly what failed instead of wall-of-text (is it possible? pylint, I'm looking at you)
- [ ] run `flake8`, `pylint`, `nosetests`, etc, even if a previous step failed (maybe)
- [ ] perhaps we should run tests first, `pylint` later, because tests take a second to run, and `pylint` takes a much longer time.

For remote CI, the current flow is possibly fine. I intend to work on it myself, adding the issue for visibility / tracking.

**Comment by tbielawa** [comment]
@rhcarvalho I agree with you. Sometimes the `pycrypto` package can take a while to install just because of all the native modules that need to be compiled.

You're right, we don't have to re-create the virtualenv on every run. The only reason to destroy it every time is to ensure that any changes to the test requirements (due to importing new non-standard libraries) are installed (or not) between runs. I guess you need 'expert' information to know that you can skip that step and run each test individually.

I want to clean up the pylint output as well, especially now that we are applying the checks to a lot more paths. Locally I've had good results filtering with this simple grep.

Now:

> $ make ci-pylint 2>&1 | wc -l                    
> 247

Filtered:

> $ make ci-pylint 2>&1 | grep -v 'locally-disabled' | wc -l 
> 41

That would be easy to incorporate into the `ci` systems `ci-pylint` target. Here's an example where I intentionally break one of the pylint rules (abbreviated):

```
$ make ci-pylint                                                           
#############################################
# Running PyLint Tests in virtualenv
#############################################
. oo-installenv/bin/activate && python -m pylint --rcfile ../git/.pylintrc ../filt....
This option u'required-attributes' will be removed in Pylint 2.0This option u'ignore-iface-methods' will be removed in Pylint 2.0
************* Module oo_filters
************* Module openshift_master
************* Module openshift_quick_installer
************* Module default
************* Module profile_tasks
...
************* Module openshift_cert_expiry
C:132, 0: Exactly one space required after comma
    for name,value in cert_loaded.get_subject().get_components():
            ^ (bad-whitespace)
************* Module openshift_upgrade_config
************* Module ec2_ami_find
...
```

Right now the `ci` target runs these dependency targets:

> ci: clean virtualenv ci-list-deps ci-flake8 ci-pylint ci-unittests

Running a full `make ci` on my box takes about 50 seconds to a minute to complete. If I skip rebuilding the virtualenv (`make ci-list-deps ci-flake8 ci-pylint ci-unittests`) it takes about 18 seconds. So we're spending about 30 to 40 seconds (about 66% of our time) just building the virtualenv. That number can fluctuate too depending on your bandwidth, pypi load, and how fast your client can compile the native modules.

I hesitate to suggest that we should run all tests unconditionally. I think if we didn't stop on every broken check then people won't necessarily see all of the failing items (pyflakes, pep8, etc). If we factor out rebuilding the virtualenv every time then iterative testing should be much simpler and quicker. And, what's broken will always be the last thing on the screen.

As for rearranging the order, yes, totally! Running the unittests takes ~1 second on my machine. 

```
$ /bin/time make ci-unittests
#############################################
# Running Unit Tests in virtualenv
#############################################
. oo-installenv/bin/activate && python setup.py nosetests
...
ooinstall/variants.py               37      1    97%
----------------------------------------------------
TOTAL                             1118    319    71%
----------------------------------------------------------------------
Ran 117 tests in 0.634s

OK
VIEW CODE COVERAGE REPORT WITH 'xdg-open cover/index.html' or run 'make viewcover'
1.09user 0.08system 0:01.19elapsed 99%CPU (0avgtext+0avgdata 37800maxresident)k
0inputs+408outputs (0major+13046minor)pagefaults 0swaps
```

So listing all the target times out, maybe we should order them like this:

* unit tests: 1s
* pyflake8: 3.5s
* pylint: 13s

> $ grep -E '^ci:' Makefile
> ci: ci-list-deps ci-unittests ci-flake8 ci-pylint

Which when ran still takes about 18 seconds. As for making the virtualenv I just found a strategy online for conditionally making and updating the virtualenv via the Makefile. If the `test-requirements.txt` file modification time is newer than the `oo-installenv/` directory then the virtualenv is rebuilt.

Pull request incoming presently.
