### ISSUE TITLE
Customizing install in AWS not working

### ISSUE THREAD

**Issue by jds2001** [openshift/openshift-ansible#3012]
Installing a cluster in AWS using bin/cluster failed when customizing some playbook variables via forcing them in extra_vars.

Totally understand that bin/cluster is unsupported, however an alternative, supported method of launching in AWS seems not to exist - would welcome a pointer to another way to do what I'm trying to do!

 I think that the problem might be the escaping is bad, leading to bad YAML but that's just a theory.

The following are the modifications that I made to the Cluster.create() function:

        cluster['openshift_master_identity_providers'] = '[{\'name\': \'htpasswd_auth\', \'login\': \'true\', \'challenge\': \'true\', \'kind\': \'HTPasswdPasswordIdentityProvider\', \'filename\': \'/etc/origin/master/htpasswd\'}]'
        cluster['openshift_master_htpasswd_users'] = '{\'jstanley\': \'<redacted>\', \'admin\': \'<redacted>\'}'
        cluster['os_sdn_network_plugin_name'] = 'redhat/openshift-ovs-multitenant'
        cluster['osm_use_cockpit'] = 'true'
        cluster['osm_cockpit_plugins'] = '[\'cockpit-kubernetes\']'

##### Version
[root@ansible openshift-ansible]# git describe
openshift-ansible-3.4.17-1-283-g930102c
[root@ansible openshift-ansible]# ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### Steps To Reproduce
1. Add the above lines to bin/cluster
2. Run 'bin/cluster create aws test1'

##### Current Result
`TASK [openshift_master : Install httpd-tools if needed] ************************`
`fatal: [test1-master-9f81f]: FAILED! => {"failed": true, "msg": "The conditional check '(item.kind == 'HTPasswdPasswordIdentityProvider') and not openshift.common.is_atomic | bool' failed. The error was: error while evaluating conditional ((item.kind == 'HTPasswdPasswordIdentityProvider') and not openshift.common.is_atomic | bool): 'unicode object' has no attribute 'kind'\n\nThe error appears to have been in '/root/openshift-ansible/roles/openshift_master/tasks/main.yml': line 74, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install httpd-tools if needed\n  ^ here\n"}`

##### Expected Result
Installed cluster

##### Additional Information
Trying to install Origin with the default CentOS7 AMI's.

**Comment by tbielawa** [comment]
@jds2001 you're correct that the `bin/cluster` script isn't supported any more. The best reference I can provide right now is to our `openshift-ansible-contrib` repo. It contains a 'reference architecture' for AWS deployments and some playbooks that might help you out

* https://github.com/openshift/openshift-ansible-contrib/tree/master/reference-architecture/aws-ansible

Note that the `-contrib` repo is also community supported (like the `bin/cluster` script), however the reference arch in the contrib repo receives more regular updates. I haven't used it myself. The README includes gratuitous usage instructions. Maybe that can help you get closer to where you're going. Please give it a look-see and let me know how it turns out :smile:

**Comment by adelton** [comment]
Potentially related: https://github.com/openshift/openshift-ansible/issues/2513

**Comment by michaelgugino** [comment]
The affected code path has been removed.

Closing this issue because it is no longer valid.
