### ISSUE TITLE
Upgrade scripts assume that inventory_hostname is resolvable, but that's not required during install or in the GCE ref arch

### ISSUE THREAD

**Issue by smarterclayton** [openshift/openshift-ansible#3029]
```
- name: Wait for master API to come back online
  become: no
  local_action:
    module: wait_for
      host="{{ inventory_hostname }}"
      state=started
      delay=10
      port="{{ openshift.master.api_port }}"
  when: inventory_hostname in groups.oo_masters_to_config
```

in `openshift-ansible/playbooks/common/openshift-cluster/upgrades/docker/restart.yml` tries to connect to inventory_hostname, which is not resolvable from another host.

**Comment by smarterclayton** [comment]
Either that, or the assumptions about what value inventory_hostname is for upgrade are different for install and the ref archs.  The default inventory value for this in the GCE ref-arch is `ci-prclaytontest-ig-m-8z94` which I carried through.

**Comment by smarterclayton** [comment]
Why is this a local action?

**Comment by detiber** [comment]
Instead of inventory_hostname, this should get a valid hostname from the hosts.

Outside of that, this probably shouldn't be a local action, since it cannot be guaranteed that the individual master hostname is reachable from the local machine. Instead, another master should probably be used in the case of multiple masters, and a node in the case of a single master.
