### ISSUE TITLE
make ci not checking all Python files

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/openshift-ansible#3053]
We rely on the [".py" extension to find and run pylint et al](https://github.com/openshift/openshift-ansible/blob/afa745c53379408955b87db91b9b29d51fabf37b/utils/Makefile#L37), and that omits some files, e.g.:
- [playbooks/common/openshift-cluster/upgrades/files/pre-upgrade-check](https://github.com/openshift/openshift-ansible/blob/afa745c53379408955b87db91b9b29d51fabf37b/playbooks/common/openshift-cluster/upgrades/files/pre-upgrade-check#L6)

Perhaps the file above was checked some time ago, for it has a `pylint: disable` comment.

**Comment by tbielawa** [comment]
I checked this out, luckily there are only a few missing

```
[~/rhat/openshift/openshift-ansible] 11:08:05  (installer-count-bz1388739)
$ find . -type f | grep -v '\.git' | xargs file | grep 'Python script' | awk '{print $1}' | grep -E -v '\.py:$'
./docs/style_guide.adoc:
./docs/best_practices_guide.adoc:
./playbooks/libvirt/openshift-cluster/tasks/launch_instances.yml:
./playbooks/common/openshift-cluster/upgrades/files/pre-upgrade-check:
./bin/cluster:
```

The first two aren't python files, they're documentation

The next file is just a playbook yaml file

pre-upgrade-check you already noted and has not been modified in years. Nor is it referenced from anywhere in the entire code base. I assume it is no longer used.

The last file, `bin/cluster` is for a tool we no longer support but for some reason we still keep around in the repo.

I think this issue is OK to close. I don't see anything that actually requires updating our files-to-check list. Please let me know if I'm missing something.

Thanks @rhcarvalho
