### ISSUE TITLE
Please fix  openshift-github-bot

### ISSUE THREAD

**Issue by fweimer** [openshift/openshift-ansible#3121]
openshift-github-bot@redhat.com is posting bogus comments to Red Hat Bugzilla, referencing the `openshift-ansible` repository:

* https://bugzilla.redhat.com/show_bug.cgi?id=2244#c3

**Comment by sdodson** [comment]
@dobbymoodge https://github.com/openshift/openshift-ansible/commit/74216e24c0c02efccb304a6c1efe131775948e1e pushed a notification to the bug because the commit said "issue#2244"

I think two things should change, the bot should only send notifications from Members, not Contributors. And it should only push notifications that explicitly say Bug or BZ I forget which the rule is.

**Comment by dobbymoodge** [comment]
Oh wow, this is a funny one. Will look closer this afternoon

**Comment by dobbymoodge** [comment]
This looks like a problem with the bugzilla service integration in GitHub. I'm not sure how to modify that behavior, looking into it now.

**Comment by dobbymoodge** [comment]
@sdodson @fweimer This behavior has to do with the somewhat inflexible bugzilla integration that github offers. The line that triggers this is: https://github.com/github/github-services/blob/master/lib/services/bugzilla.rb#L155

Our options for fixing this don't look great. I don't think a pull request against github/github-services would be effective, since they say they're only accepting bug fixes, not new features, and this isn't exactly a bug. That leaves us the option 1) of writing our own webhook, implementing some additional parameters to constrain which bugs it will update, and exposing it where GitHub can get to it, and option 2) of disabling the integration.

Probably the best approach is to just be more careful about how we reference GitHub issues on  repos where we want the bugzilla integration.

**Comment by sdodson** [comment]
Fine with me. I guess we need to be cognizant not to merge anything when the bug or issue referenced isn't relevant.
