### ISSUE TITLE
Incorrect COCKPIT_KUBE_URL when using openshift_hosted_router_force_subdomain

### ISSUE THREAD

**Issue by lcarva** [openshift/openshift-ansible#3167]
#### Description

During standalone registry deployment, if `openshift_hosted_router_force_subdomain` is set, it may cause incorrect OAuth behavior due to incorrect `COCKPIT_KUBE_URL`.

##### Version

```
ansible 2.2.0.0
openshift-ansible-3.4.55-1
```

##### Steps To Reproduce
1. In `inventory.yml` set the following:
```ini
[OSEv3:vars]
deployment_type=openshift-enterprise
deployment_subtype=registry
openshift_hosted_router_force_subdomain='${name}.app.mydomain.com'  
openshift_master_default_subdomain=app.mydomain.com
openshift_master_identity_providers=[{'name': 'google', 'challenge': 'false', 'login': 'true', 'kind': 'GoogleIdentityProvider', 'clientID': '<client-id>',  'clientSecret': '<client-secret>'}]
```
Notice that `${namespace}` is not defined in `openshift_hosted_router_force_subdomain`.

2. Run `ansible-playbook`:
```
ansible-playbook -i inventory.yml playbooks/byo/config.yml
```
3. Access registry-console: https://registry-console.app.mydomain.com

##### Expected Results

Expect registry console to display properly and OAuth to be successful when accessing it via browser.

##### Observed Results

OAuth is initiated but fails with:
```json
{"error":"invalid_request","error_description":"The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."}
```

This is due to incorrect value for redirectURIs in OAuth provider:
```
# oc get oauthclient cockpit-oauth-client -o jsonpath='{.redirectURIs}'
[https://registry-console-default.app.mydomain.com]
```
Notice the presence of namespace, `-default`

The route actually has both values (with and without namespace):
```
# oc get route registry-console -o jsonpath='{.spec.host}'
registry-console-default.app.mydomain.com

# oc get route registry-console -o jsonpath='{.status.ingress[].host}'
registry-console.app.mydomain.com
```

##### Additional Information

It appears that oauthclient's `redirectURIs` are set based on `COCKPIT_KUBE_URL`[0], which is resolved by inspecting route's `.spec.host`[1].

[0] https://github.com/openshift/openshift-ansible/blob/0516c051463951379399135c24093175f4127c94/roles/cockpit-ui/tasks/main.yml#L72
[1] https://github.com/openshift/openshift-ansible/blob/0516c051463951379399135c24093175f4127c94/roles/cockpit-ui/tasks/main.yml#L58-L61

**Comment by lcarva** [comment]
The same appears to be true for `docker-registry` app. However, in this case it does not cause OAuth errors. Instead it causes the wrong hostname, in the docker command hints, to be displayed in cockpit-ui.

**Comment by kvjeevan123** [comment]
I am trying to create a cockpit pod in the openshift origin (all-in-one environment) running the below command
oc process -f openshift-cockpit.template -v OPENSHIFT_OAUTH_PROVIDER_URL=https://x.x.x.x:8443 | oc create -f - 
Provided the COCKPIT_KUBE_URL as the machine IP where I have openshift origin deployed. While trying to access the route URL, I am getting the below error -
{
error: "invalid_request",
error_description: "The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is otherwise malformed."
}

Can someone guide me how to resolve this and Is this the template I should be using to monitor pods/containers deployed in Origin environment.

**Comment by abessifi** [comment]
Hi folks,
Does this issue persist ?
