### ISSUE TITLE
Provide comprehensive list of tunables

### ISSUE THREAD

**Issue by sdodson** [openshift/openshift-ansible#322]
We need to provide a comprehensive list of tunables. Also, is there a way to determine which variables are 'private' versus 'public'? What's the best way to document this? I think just syncing the docs in each of the roles is good enough but it'd be nice if we had a rollup of those in one place.

@twiest @detiber thoughts?

**Comment by sdodson** [comment]
Perhaps a thoroughly annotated byo inventory file?

**Comment by detiber** [comment]
@sdodson I would avoid an annotated byo inventory file for this, since variables can (and should) be specified in better ways using the group_vars and host_vars instead of using the inventory file.  Rather, we should document the tunables in one or more README files.  Maybe a generic readme for tuneables that is then referenced from the other READMEs?

**Comment by twiest** [comment]
@sdodson this is a very good idea, and we definitely need something like this.

This seems to be in line with the recently merged cli_ variables from PR #269.

Obviously there are more tunables. :)

**Comment by tbielawa** [comment]
This is probably covered under the **Future Plans** doc:

https://docs.google.com/document/d/1uqW2Ze0Hc_2D976k2WTN6TNvAuuOZFPyztQ3d4iGCgQ/edit

Additionally, I believe many of our inventory files, role READMEs, as well as online literature have had extensive documentation updates.
