### ISSUE TITLE
Detected OpenShift version 1.3.0 does not match requested openshift_release 1.5.0-alpha.2

### ISSUE THREAD

**Issue by cgutshal** [openshift/openshift-ansible#3357]
#### Description

Provide a brief description of your issue here. For example:

I attempting to install a single master origin using the v1.5.0-alpha.2 release

##### Versions
>ansible 2.2.1.0
>  config file = /etc/ansible/ansible.cfg
>  configured module search path = Default w/o overrides

Git Clone:
> openshift-ansible-3.5.3-1-196-g950f5ba

##### Steps To Reproduce
1. set openshift_release to v1.5.0-alpha.2 in etc/ansible/hosts
2. run deploy via ansible-playbook openshift-ansible/playbooks/byo/config.yml

##### Expected Results
Successful deployment of OSO on server with the nodes connected. 

##### Observed Results
```
ASK [openshift_version : fail] ************************************************
fatal: [lnpnprifosm006v.int.asurion.com]: FAILED! => {"changed": false, "failed": true, "msg": "Detected OpenShift version 1.3.0 does not match requested openshift_release 1.5.0-alpha.2. You may need to adjust your yum repositories, inventory, or run the appropriate OpenShift upgrade playbook."}
```

##### Additional Information
* Master OS == RHEL 7.2, Fedora 23 (`$ cat /etc/redhat-release`)
* Your inventory file (especially any non-standard configuration parameters)
* Sample code, etc

##### Comments
Is it possible this is to the rpm's for 1.5 origin not being available yet? I read through some old issues that pointed to that being one of the main reasons for the error.

**Comment by cgutshal** [comment]
Switching to the containerized install resolved this, so closing for now.

**Comment by abutcher** [comment]
Hey @cgutshal, the latest version in the [centos paas sig repos](http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin/) is `1.4.1-1`. I'm not sure when we'll see 1.5 rpms in those repos. @tdawson may have a better idea.

**Comment by tdawson** [comment]
The repo you are pointing to is the "released" repo.  That means it's only for rpms that have been released by origin upstream, built into rpms on CentOS, passed tested, then released.
Since origin 1.5.0 is still in it's alpha stage, it's going to be a while before you see it in there.

Now for the better news.  We're going to start having seperate repo's for each release.  So version 1.3, 1.4, and 1.5 will all have their own repo you can point at.  (The one you pointed at will continue to stay update with the latest released).  So you will be able to point at 1.5 as it's going through it's alpha stage.
The not so better news is we expect this to take at least 2 weeks or so to implement, so it's not just around the corner.

**Comment by cgutshal** [comment]
@tdawson Good to know! Appreciate the info this.
