### ISSUE TITLE
Allow configure OpenShift console on an another port

### ISSUE THREAD

**Issue by chmouel** [openshift/openshift-ansible#343]
I have been trying a few things setting up those variables : 

```
openshift_master_console_port=43
openshift_master_public_api_url=https://master.example.com
openshift_master_api_url=https://master.example.com
openshift_master_bind_addr=0.0.0.0
openshift_master_public_console_url=https://master.example.com/console/
openshift_master_api_port=43
```

but I could not find the right variable and kubeconfig files weren't updated as well, is it supported to change the default console port number from 8443 to 43 ?

**Comment by detiber** [comment]
@chmouel We have some pieces in place for customizing some of the ports, however it's not fully supported yet (for example, the iptables rules will not be updated for the changed ports). There may also be other places in the ansible playbooks and roles that we expect the default values, since we haven't tested with non-default ports up to this point.

**Comment by chmouel** [comment]
@detiber thanks, should I leave this PR open as a TODO request?

**Comment by detiber** [comment]
@chmouel indeed, lets leave this open until we fully support changing the api/console ports.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
