### ISSUE TITLE
Using a non-root account as ansible_ssh_user failes when root doesn't have permission to write to home

### ISSUE THREAD

**Issue by nirtal** [openshift/openshift-ansible#3668]
#### Description

When running openshift-ansible playbook with other ansible_ssh_user then root, the root user tries to create files in the ansible_ssh_user home folder.
This breaks the playbook run when the root user doesn't have permissions to write in the users home folders, as an example when the the users home folder is on a nfs share.

##### Version

```
openshift-ansible-3.4.69-1 from https://github.com/openshift/openshift-ansible/releases
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### Steps To Reproduce
1. Create a user with a homefolder where root user don't have permissions to write, on the masters.
2. Run the openshift-ansible playbooks and use the previous user as ansible_ssh_user.

##### Expected Results

```
I expect for openshift-ansible playbooks to not create files in my ansible_ssh_user home folder.
Or I expect for the openshift-ansible run to not break when it can't create files in the ansible_ssh_user home folder.
```

##### Observed Results

```
The ansible playbooks tries to create ~/.kube folder and ~/.kube/config for the ansible_ssh_user and for the root user.
This fails for the ansible_ssh_user and the playbooks/installation stops.
See https://gist.github.com/nirtal/15f78dcc8cca5dd4487685bc763236de for the failing part of openshift-ansible
```

##### Additional Information

```
OS: Red Hat Enterprise Linux Server release 7.3 (Maipo)
Inventory file: https://gist.github.com/nirtal/f4baf3477d638002b080589d70872c82
```

**Comment by woopla** [comment]
Just stumbled upon this too. My dirty workaround was to create a symlink from `/tmp/.kube` to `~user/.kube` on the master Ansible is running this.

I tried running this as the user itself, but it won't work because `/etc/openshift` is not readable by the user.

Maybe using a two-step approach would work?

1. `root` copies content to a user accessible location (say /tmp) and chowns it to the user
2. Regular user moves that dir to its final location

Thanks,

Clément
