### ISSUE TITLE
Upgrade playbook should unexclude the origin-excluder

### ISSUE THREAD

**Issue by jhadvig** [openshift/openshift-ansible#3858]
At the start of the upgrade.yml playbook (any version) the plytbook itself should unexclude the origin-excluder so the new one could be upgraded to the newest version, as well as other pckags that the play is upgrading. The issue is the newset version could not be downloaded.
```
TASK [openshift_excluder : Install docker excluder] ****************************
task path: /usr/share/ansible/openshift-ansible/roles/openshift_excluder/tasks/install.yml:7
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "No package matching 'origin-docker-excluder-3.6.0-0.alpha.0.165.801b564*' found available, installed or updated", 
    "rc": 126, 
    "results": [
        "No package matching 'origin-docker-excluder-3.6.0-0.alpha.0.165.801b564*' found available, installed or updated"
    ]
}
```

Not sure what should be the best solution, cause I saw the  [comment](https://github.com/openshift/openshift-ansible/blob/master/playbooks/byo/openshift-cluster/upgrades/v3_6/upgrade.yml#L53-L54) for the upgrade process, but I've thought that this should be done automatically.
Here is the [install_upgrade job](https://ci.openshift.redhat.com/jenkins/view/All/job/test_branch_origin_extended_conformance_install_update/164/consoleFull)
@sdodson @ingvagabund thoughts ?

**Comment by stevekuznetsov** [comment]
This is a blocker for the Install/Upgrade job

**Comment by ingvagabund** [comment]
@jhadvig can you more elaborate on what is going on here? The excluder install task [1] is trying to install any 3.6 docker-excluder (the version given by ``openshift_pkg_version`` variable). What is the reason the ``origin-docker-excluder-3.6.0-0.alpha.0.165.801b564*`` is not found? Is it because there is no repository providing that rpm? Or is it because there is an excluder that excludes any ``origin-docker-excluder-3.6`` rpm?

[1] https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_excluder/tasks/install.yml#L9

**Comment by stevekuznetsov** [comment]
@ingvagabund it's the latter -- the excluder we need was built and is available, but a previous exclude step is excluding it

**Comment by ingvagabund** [comment]
@stevekuznetsov thanks, we had a chat with @jhadvig confirming the same.
