### ISSUE TITLE
openshift_master_cluster | Authenticate to the cluster

### ISSUE THREAD

**Issue by johnjelinek** [openshift/openshift-ansible#394]
The playbook fails on this step for me (branch: `v3.0.0-7`).

```
TASK: [openshift_master_cluster | Authenticate to the cluster] ****************
failed: [osv3-master-556cc74b-9129-4b85-a4bd-8cbd3550cef4] => {"changed": true, "cmd": ["pcs", "cluster", "auth", "-u", "hacluster", "-p", "poweruser", "osv3-master-556cc74b-9129-4b85-a4bd-8cbd3550cef4", "osv3-master-f997c52a-4e44-4588-9f52-5f4f1d5ee554", "osv3-master-43e6ffb5-cdfa-4cf6-83b0-4e4c5c652bdc"], "delta": "0:00:12.466634", "end": "2015-07-27 14:17:20.446011", "rc": 1, "start": "2015-07-27 14:17:07.979377", "warnings": []}
stderr: Error: unable to connect to pcsd on osv3-master-43e6ffb5-cdfa-4cf6-83b0-4e4c5c652bdc
Unable to connect to osv3-master-43e6ffb5-cdfa-4cf6-83b0-4e4c5c652bdc ([Errno 113] No route to host)
stdout: osv3-master-556cc74b-9129-4b85-a4bd-8cbd3550cef4: Authorized
osv3-master-f997c52a-4e44-4588-9f52-5f4f1d5ee554: Already authorized
```

Is the issue about `pcsd` and `No route to host` or is it really about being `Already authorized`? How should I troubleshoot this?

**Comment by johnjelinek** [comment]
I think the problem is `No route to host` rather than `Already authorized`. I deleted my `master`s and it just came back with `([Errno -2] Name or service not known)`. Maybe there's a dependency I'm missing that's not in the playbook?

**Comment by detiber** [comment]
@johnjelinek I agree that it looks like the error is actually the no route to host.  I suspect that during the run the third master failed (osv3-master-43e6ffb5-cdfa-4cf6-83b0-4e4c5c652bdc) prior to the completion of the tasks in the openshift-master role.  

For many issues, the full log helps more than just the last error in the log.  If one of the master hosts fail prior to the end of the cluster setup, you will probably have to delete the cluster and re-run ansible, since the ansible role only checks for the existence of the cluster on the first master host when deciding whether to configure the cluster or not.

To delete the cluster on the first master: `pcs cluster destroy`

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
