### ISSUE TITLE
Check available docker images and rpms versions

### ISSUE THREAD

**Issue by ingvagabund** [openshift/openshift-ansible#4023]
During the containerized deployment the docker images version and rpm versions can be out of sync. We should check both versions and stop the deployment if they are not the same at the very beginning of the installation.

**Comment by sdodson** [comment]
Is this a general problem or just a problem that the CI jobs were having earlier today?

The CD team builds RPMS, creates a private yum repo, then builds images from that repo. Once that's done they push those images to their final destination and publish the yum repo at roughly the same time.

The CI jobs earlier today were failing because we were pulling directly from the repo where they build their images so I've changed it to point to where the images get published. Hopefully that will fix the CI jobs we've been having trouble with. It has at least for the problems we saw earlier today.

**Comment by ingvagabund** [comment]
AFAIK, CI problem only. The purpose of the issue is to just report the OCP version of the docker images and the excluder rpm. So we can see if they are different or not. Followed by a pretty message that says what is really going on instead of excluders not being available. Checking the flow it is not a trivial problem to check the version at the beginning if the deployment is containerized. So I would just report the message right before the excluders are installed. The role itself fails if the excluders are not available anyway.

**Comment by jhcook** [comment]
Hi there. Why does this fail a check if this is a CI issue only? I've downgraded the excluder and rerun the pre_upgrade before upgrade. The excluder is upgraded during the pre_upgrade and the checks fail all over again. 

The automated documentation states this is a dry run. I am trying to go from 3.4.1.7 to 3.4.1.44 with zero success. The excluder is being updated to the latest RPM which supersedes the Docker image version and the update bombs.

**Comment by ingvagabund** [comment]
Hi, which pre_upgrade playbook did you run?

**Comment by jhcook** [comment]
openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v3_4/upgrade.yml

**Comment by ingvagabund** [comment]
If the rpm version and docker image version differs, you can set the following variables explicitly:
```
openshift_pkg_version=-3.4.1.44
openshift_version=3.4...
```

The `openshift_pkg_version` corresponds to available rpm version and `openshift_version` to the docker one.
