### ISSUE TITLE
openshift_logging: don't create local tmpdir with `become`

### ISSUE THREAD

**Issue by stevekuznetsov** [openshift/openshift-ansible#4203]
Local tmp dir is created without `local_action` and `become: no`. This causes permissions errors when the control host is in the cluster and the tmpdir is created as root but the user running the playbook isn't root.

**Comment by irozzo-1A** [comment]
@stevekuznetsov Same issue has not been fixed for [release-1.5](https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_logging/tasks/generate_jks.yaml#L23). In addition there are other `local_action`s which should have `become: no` as well (i.e.. [roles/openshift_logging/tasks/generate_jks.yaml](https://github.com/openshift/openshift-ansible/blob/release-1.5/roles/openshift_logging/tasks/generate_jks.yaml#L29-L96)). I detected it because I launched the playbook from a container where `sudo` is not available. Are you ok if I submit a PR to fix it?

**Comment by stevekuznetsov** [comment]
@irozzo-1A absolutely -- please submit a PR!

**Comment by sdodson** [comment]
The cherry-pick failed, @irozzo-1A can you open a backport PR?

**Comment by stevekuznetsov** [comment]
@kargakis why no comment here?

**Comment by kargakis** [comment]
The bot is not handling issues.

**Comment by stevekuznetsov** [comment]
D'oh... this is an issue
