### ISSUE TITLE
Getting stuck at: TASK: [os_firewall | Start and enable iptables service]

### ISSUE THREAD

**Issue by minettiandrea** [openshift/openshift-ansible#434]
when deploying a multimaster system with ansible playbook never finishes on a bare metal set up (3 master hosts, 3 etcd, 2 nodes), ansible script is stuck at:
TASK: [os_firewall | Start and enable iptables service] ***********************
changed: [master1.openshift.mydomain.com]

i expect to have printed also 
changed: [master2.openshift.mydomain.com]
changed: [master3.openshift.mydomain.com]
then continue the install script, but the masters cluster gets broken and nothing happens anymore.

Version-Release number of selected component (if applicable):
- Openshift v3
- CentOS 7.1
- Ansible 1.9.2
- openshift-ansible commit: 241c72f

Thank you

**Comment by detiber** [comment]
@minettiandrea I would need additional output from the failed run, as well as the host file you used for installing (if using the byo playbooks, otherwise I'd need the flags you used to invoke bin/cluster).

the os_firewall role is invoked from a few different playbooks, so from the output you included it is tough to tell which specific playbook, task file, or role it is being called from.  There are some tasks that are serialized and some that are parallelized.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.

**Comment by nicolasproton** [comment]
I am facing the same issue only whenever I run in environments with 3 masters (when running 1 master configuration the issue doesn't occur).
atomic-openshift-utils.noarch   3.3.54-1.git.0.61a1dee.el7
atomic-openshift.x86_64           3.3.1.7-1.git.0.0988966.el7

**Comment by detiber** [comment]
@nicolasproton are you running Ansible from one of the master hosts? If so, you should update the host definition in your inventory to add `connection=local` for the host you are running on.

**Comment by nicolasproton** [comment]
@detiber Yes I am running the install from one of the master and I have tried "connection=local" for that one master but it doesn't to make any difference. Still having the problem.
