### ISSUE TITLE
error occurs at  "vagrant provision" step

### ISSUE THREAD

**Issue by screeley44** [openshift/openshift-ansible#447]
I have a rhel 6.5 laptop that I've installed vagrant 1.7.4,vbox 4.3.20, ansible, etc... I'm trying to see if I can get a quick cluster up and running using this openshift-ansible repo

I don't get any errors when I do the first step using vbox commands:
               vagrant up --no-provision

but when I do the:
               vagrant provision

**smooth sailing**
...
...
ok: [master] => (item=master.kubelet-client.crt)
ok: [master] => (item=master.server.crt)
ok: [master] => (item=openshift-master.crt)
ok: [master] => (item=openshift-registry.crt)
ok: [master] => (item=openshift-router.crt)
ok: [master] => (item=etcd.server.crt)

TASK: [set_fact ] ************************************************************* 
fatal: [master] => Failed to template {{ g_master_cert_stat_result.results | map(attribute='stat.exists') | list | intersect([false])}}: template error while templating string: no filter named 'map'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/config.retry

localhost                  : ok=7    changed=0    unreachable=0    failed=0   
master                     : ok=12   changed=2    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

can't seem to get around this issue and not sure where to get more information on it or maybe there is something fundamentally wrong with my whole approach???  I just don't know?  Is this an issue or something else?

**Comment by detiber** [comment]
@screeley44 this is indeed odd...  the map filter is provided by jinja2. I'm not sure if this is an issue with the version of jinja2 installed on RHEL 6 or if it is an artifact from using ansible 1.7.x, which I would suspect would fail for other reasons.  

I would recommend only running using the latest ansible (1.9.2 currently).

**Comment by screeley44** [comment]
@detiber - my ansible version is the 1.9.2 actually 

ansible                  noarch                  1.9.2-1.el6                     @epel                  7.0 M

**Comment by detiber** [comment]
@screeley44 my bad, late night ticket replies led to me mistaking the vagrant version above for the ansible version.

Can you verify the version of jinja that you have installed?

The version from my system:
```
jdetiber@jdetiber:~➤ rpm -qa | grep jinja
python-jinja2-2.7.3-2.fc22.noarch
```

**Comment by screeley44** [comment]
@detiber - hehehe, I know how that goes, no biggie... so here is my jinja version (not sure how easy that is to update either?? if that is even a possible cause)

[screeley@screeley ~]$ rpm -qa | grep jinja
python-jinja2-2.2.1-2.el6_5.x86_64

[screeley@screeley ~]$ python -V
Python 2.6.6

**Comment by detiber** [comment]
@screeley44 it looks like the map filter was introduced in version 2.7 of jinja2: http://jinja.pocoo.org/docs/dev/changelog/#version-2-7

Just spit balling here, but you could probably configure a python virtualenv and install ansible within a virtualenv with a newer version of jinja2 (http://configure.systems/install-ansible-within-a-virtualenv-easily/). 

Most of the testing so far has been using RHEL7/Fedora so we haven't really hit these issues...  One of our future plans is to have a containerized install, so that would solve many of the dependency issues (as long as the host running the installation can run a docker/atomic app container).

**Comment by screeley44** [comment]
@detiber - ah, cool, thanks for the help and let me give that a try and see what happens.  If I make any progress will post here and let you know

**Comment by gr3x** [comment]
Just for your information, I got the same problem : 
python-jinja2-2.2.1-2.el6_5.x86_64
Python 2.6.6

I know it's a bad thing I did but it works and it's a dedicated management VM with openshift ansible:
1) yum uninstall python-jinja2 (& ansible because of dependencies)
2) reinstall a newer unoficial version of python-jinja2 (python-jinja2-2.7.2-1.el6.noarch.rpm)
3) reinstall ansible

**Comment by detiber** [comment]
@abutcher any thoughts on a way to easily replace the map filter with something that is available in jinja 2.2.1 ?

**Comment by abutcher** [comment]
@detiber replace every `map` with `oo_collect`?

**Comment by detiber** [comment]
@brenton this issue can be closed.
