### ISSUE TITLE
One node OpenShift setup through Vagrant

### ISSUE THREAD

**Issue by LalatenduMohanty** [openshift/openshift-ansible#452]
I am looking for a single node OpenShift box which can be used through Vagrant as the idea is to start from a simple setup. The current setup for the existing vagrantfile spun of 3 vms. 

CC @voxik @detiber

**Comment by voxik** [comment]
@LalatenduMohanty Sorry, I am not familiar with OpenShift nor their Vagrant files, so I can't be of any help here.

**Comment by detiber** [comment]
@LalatenduMohanty indeed, since that was the main test case we were targeting when I created the Vagrantfile (I was trying to mimic the beta training as closely as possible).

I'm all for extending the Vagrantfile to support additional types of deployments, however I don't expect it will be a development priority in the short term (other fish to fry so to speak). I'd be happy to review and/or test PRs for improvements to it though.

**Comment by LalatenduMohanty** [comment]
@detiber I have tested the current vagrantfile and it works fine on F22+Virtalbox 4.3 setup. I went with the defaults so ended up using 3 nodes. I am assuming I can just change the Vagrantfile to only provision me the master or master + 1 node and it should work fine. Do you think it should work?

I will test these once I am done with the current testing.

**Comment by detiber** [comment]
@LalatenduMohanty indeed, it should work. I was just thinking of having it configurable properly through an ENV variable, so that altering the size of the environment in the Vagrantfile doesn't require modifying the actual vagrantfile.

**Comment by LalatenduMohanty** [comment]
@detiber cool. Let me see if I can improve it by adding environment variables . However I am curious to know if you think having the dnsmasq setup on the master node would create issue as mentioned in [1]

[1] https://github.com/openshift/training/blob/master/deprecated/beta-4-setup.md#appendix---dnsmasq-setup

**Comment by detiber** [comment]
@LalatenduMohanty yes, the master host stands up a dns server used internally to the cluster, so dnsmasq would not be able to bind to port 53.

**Comment by LalatenduMohanty** [comment]
@detiber any suggestion how to work around this?

**Comment by detiber** [comment]
@LalatenduMohanty That was the main motivation for me to use the hostmanager plugin. But I haven't tested any issues related to container dns resolution when using the VagrantFile...  There may be some hints in the playbooks/libvirt/openshift-cluster directory as to how the libvirt provider handles dns resolution, but I'm not sure how much of that would be applicable to VirtualBox, since I'm not sure VirtualBox does the automatic dnsmasq configuration that libvirt does.

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
