### ISSUE TITLE
Logging installation on a nodes with insufficient resources should fail gracefully instead of seemly succeeding

### ISSUE THREAD

**Issue by portante** [openshift/openshift-ansible#4581]
#### Description
When the nodes on which logging pods will be scheduled do not have enough resources to host them, the playbook for installing logging seems to complete with out errors.

##### Version
```
ansible-2.2.3
openshift-ansible-3.4.79-1.git.0.6faa668.el7.noarch
```

##### Steps To Reproduce
1. Create a cluster with VMs for infrastructure nodes that are less than 16 GB
2. Try to deploy logging

##### Expected Results
Would expect that the playbook would detect failures to install due to lack of resources and abort the installation with an error.

##### Observed Results
Logging playbook continues and seems to complete without reporting any errors.

**Comment by ewolinetz** [comment]
So the expectation would be that based on the resource request, if there are no nodes that would be able to deploy to we should gracefully fail the deployment? Or is this without specifying a resource limit on the Logging components?

**Comment by portante** [comment]
If we issue a deployment for any of the pods and the deployment fails, it seems like the ansible playbook/role continues on with the next step without noticing any problems.

If the script fails to deploy a pod successfully, it might be because of lack of resources, it could also be due to other reasons than what is encountered.  It seems prudent to verify a step taken in ansible actually succeeds.

**Comment by sosiouxme** [comment]
"success" in deploying OpenShift is something you have to define carefully. You can successfully define all the pods you want to run, then you might have to wait indefinitely for the images to actually be pulled and run. You want the installer to sit and wait while that happens? How long is "too long"? It *seems* like a good idea but it's not how anything else works in the installer for now. I just ran an install where it ran through everything "successfully" except no nodes had come up due to a networking bug so in fact nothing was running (despite having defined router, registry, logging, registry console...). "Success" in a deployment seems to mainly consist of defining everything you want to run; there's no synchronous wait in most cases to see if it all actually comes together.

**Comment by portante** [comment]
Do you agree that error handling is the majority of software engineering?  And do you also agree that making interfaces usable is also a big part of what we offer to users?

We offer playbooks that deploy logging, right?  Do we clearly tell the users that the playbook is not guaranteed to result in logging running successfully, only that all components are properly defined?

If we are not willing to do the work to create playbooks that help the user to deploy logging so that it runs successfully, perhaps the playbooks should only *define* all the components and their configurations, but not start them.  Instead, we'd document the order in which the components should be started once successfully deployed.

Continuing this line of reasoning then, for upgrading, we'd need a mode were we make changes to the various component definitions, but not restarting all the services that might be running currently.  Then we'd document for the user how to do that.

What do you think ( @sosiouxme, @ewolinetz, @jcantrill )?

**Comment by sosiouxme** [comment]
The current state of things is definitely not too user-friendly. I think we want (customers want) as much as possible to have everything automated in a single consistent way, not a long list of things you have to do after you run "an install". So in describing the status quo, let me not advocate for the status quo. It needs improvement.

One complication is that there can be a lot of wait time in between defining something that you want to happen and having it actually happen, and not much way to determine when/if it might happen. Waiting synchronously for things to happen would slow down the run quite a bit and isn't really necessary in the cases we're talking about here - things will generally work themselves out eventually, or not, regardless of whether the install waits for it. But what I think we can reasonably do is check before the run if an action is likely to run into any snags, and check at the end of the run whether it is actually up and running. A general pattern like this:

1. Bootstrap whatever tools/config we might need for the next step.
2. Determine (for all relevant roles) if there are any known problems they will encounter, and abort if so.
3. Run all the requested actions.
4. Validate that those requests were fulfilled as we expected them to be (retry until success, failure, or timeout).

Actually this is the pattern that's recently been forming (with the addition of checks early in the install, and I don't see why we couldn't start running checks after the install) but it needs to go deeper on a per-role basis. We've had some discussions on the group 3 teams about how Ansible roles aren't really well-aligned with multi-mode patterns - we want to keep a role encapsulating its subject matter, but run it and its dependencies in multiple modes. I'd like to have all the roles have a bootstrap mode, a pre-run mode, a run mode, and a validation mode, and define a loop to run them all one mode at a time so that the overall effect is the flow above, regardless of which roles are involved. I have a thought for how this might work generally that I want to try out, so... more later.

/cc @brenton @Miciah @rhcarvalho food for thought for our team.
