### ISSUE TITLE
Openshift-sdn collide on installation

### ISSUE THREAD

**Issue by timothysc** [openshift/openshift-ansible#463]
Running a recent installation our cluster appears to have killed our network and I believe it is related to the SDN configuration.  

On our cluster we have a very important node unrelated to our installation.:
host01-rack10.scale.openstack.engineering.redhat.com. 86400 IN A 10.1.4.1

After running the installer it appears that one of the nodes had configured its lbr0 to 10.1.4.1 which unleashed chaos.  This does not appear to be referenced anywhere here: 
https://docs.openshift.com/enterprise/3.0/architecture/additional_concepts/sdn.html

Nor do I see an variable overload described here: 
https://docs.openshift.com/enterprise/3.0/admin_guide/install/advanced_install.html 
1. I'm curious how we can avoid this?
2. Is this recent?

cc @smarterclayton @detiber

**Comment by erinboyd** [comment]
@smarterclayton @detiber @timothysc 
After running the installer, node registration would fail with the hosts being unreachable.  On one host we did ifconfig tun0 down, because we noticed network conflicts on this host.  After running the installer again, we continued to see this issue on more and more nodes.
So, tore down the cluster and restarted, we now die on  The connection to the server kube-apiserver2.scale.openstack.engineering.redhat.com:8443 was refused - did you specify the right host or port...
Upon looking at the routing tables, they have been completely hosed by the installer. Several hosts pointing to other hosts now.

**Comment by detiber** [comment]
@erinboyd @timothysc thanks for digging into this deeper...  there are variables that can be set to override the default SDN subnet:
- osm_cluster_network_cidr
- osm_cluster_host_subnet_length

Without overriding these variables the default is to use 10.1.0.0/16

**Comment by erinboyd** [comment]
@detiber Thank you for the swift reply. Will try these out and let you know

**Comment by timothysc** [comment]
Our typical flannel CIDR is for default flannel on atomic host is: 192.168.0.0/16 , subnetLen: 24

**Comment by detiber** [comment]
@timothysc I assume you mean a subnet mask of 24, instead of a host subnet length of 24, since 24 > 16.

outside of that nitpicky differentiation, I would have to defer to @smarterclayton or @rajatchopra as to why 10.1.0.0/16 was chosen as our default...  though I suspect it would have fewer conflicts for local virtual networks than 192.168.0.0/16 would.

**Comment by timothysc** [comment]
I think the nit at this point would be in the docs, or collision detection.

**Comment by erinboyd** [comment]
@detiber @smarterclayton The flannel doc here https://access.redhat.com/articles/1353773#flannel indicates 24 as the length (link from @timothysc )

**Comment by detiber** [comment]
@erinboyd @timothysc looking at that doc, I see the differentiation...  it is between the subnet bit length and the subnet host bit length...  for a /24 the subnet bit length is 24, and the subnet host bit length is 8...

inconsistent terminology and using the english language for specific concepts FTL

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
