### ISSUE TITLE
Modify OpenShift configuration

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#469]
I successfully deployed OpenShift on OpenStack with `./bin/cluster create openstack openshift`. After that, the master node is inaccessible because it automatically redirect me to private IP address of the VM instead of the floating IP address. I know it is possible to fix this by editing `master-config.yaml` in master node, but every time I run `./bin/cluster update openstack openshift`, `master-config.yaml` is regenerated. Is there anyway to elegantly modify the configuration files?

**Comment by detiber** [comment]
@xionglingfeng I suspect that the issue is related to the metadata provided by your openstack instance.  I'm not sure if there is a way to override openshift_public_hostname (and potentially openshift_public_ip) for the instances, maybe @lhuard1A can comment further, since he has been more involved with the OpenStack support.

**Comment by lhuard1A** [comment]
Well spotted!
Forcing `openshift_public_hostname` to the public IP seems to fix the bad redirects.
Could you please validate #474 ?

**Comment by xionglingfeng** [comment]
@lhuard1A I have replied that issue.
I have a simple question: which way is the best practice to configure the OpenShift installation, use `ansible` for initial installation and modify configuration files in each VM, or edit the configuration file in `ansible` then do a installation and modify nothing directly in VM after that?

**Comment by detiber** [comment]
A slight diversion:
We have plans to improve the way we are handling the configuration files so that instead of using a template we will be using a module designed for managing the configuration files (and attempt to not overwrite hand edited changes, unless the user tells us to). I don't have any concrete details on that plan yet, since we have yet to really dig into other than the initial discussion of needing to handle the current situation better. We plan to have something in place for the enterprise 3.1 release (origin 1.1 release) to better enable upgrades (which will be handled through openshift-ansible).

Now to answer your question:
I would try to manage what you can within ansible now. 

If you are an experienced ansible user, feel free to add support for configuration items that we do not currently support that you may need (and PRs are always welcome :smile: ).

If you do not feel comfortable enough to make those changes in ansible, feel free to raise issues on this repository for features you need supported as well. You can then manage changes to the config files that aren't supported by hand (until they are supported), just be aware that if you need to run ansible for some reason (adding additional nodes, modifying some supported configuration, etc), you will need to re-add those changes back after running ansible.

**Comment by xionglingfeng** [comment]
@detiber I am new to ansible... how can I modify the configuration files elegantly with ansible? I mean, which files shall I edit and which files shall I avoid touching with?

**Comment by detiber** [comment]
@xionglingfeng elegantly is the tricky part here.

We reference the following configs (that I know of) in the documentation:
/etc/openshift/master/master-config.yaml
/etc/openshift/node/node-config.yaml
/etc/openshift/master/scheduler.json
/etc/openshift/master/policy.json

The "easiest" way would be to store the end result that you want these files to be in an ansible repository and overwrite the results of any openshift-ansible runs with the file end state you want.  This is far from elegant though.

Since the config files are yaml or json, ansible does not provide a simple way to modify just a single setting for each config file. This is where I'd like to have a module that manages these files come in, since they would be able to understand the data structures defined in the config files and can better judge the intent of the config rather than just looking at the text line-by-line.

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
