### ISSUE TITLE
What is infra_node?

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#470]
The OpenShift documentation only mentioned `master`, `node` and `etcd`, but `./bin/cluster create` has a parameter `-i` which called `infra node`. So what is this node used for?

**Comment by detiber** [comment]
@xionglingfeng infra nodes (short for infrastructure nodes) are nodes which are set aside for deploying the internal router/registry and other internal components.

The main goal (especially for deployments which utilize openshift-sdn), is that the infrastructure nodes are the only ones that need to be exposed to the internet at large (since external traffic would enter the sdn after hitting the router(s)). It also prevents user applications from interfering with infrastructure components.

The biggest thing is that it is not actually an additional host type, but rather a subtype of a node.

@wshearn can comment more about the implementation, since he is the one that wrote it.

**Comment by xionglingfeng** [comment]
@detiber Thanks for your answering! If the official document can be updated with this information, it will be less confuse for our new users :-)

**Comment by wshearn** [comment]
The infra nodes are covered in the docs here: https://github.com/openshift/training/blob/master/02-Installation-and-Scheduler.md#node-labels
