### ISSUE TITLE
One or more required Docker images are not available, but not sure why

### ISSUE THREAD

**Issue by djdevin** [openshift/openshift-ansible#4790]
#### Description

Getting a strange failure, I saw #4608 but I'm not running a prerelease version. I confirmed that host even has the image present. Strange thing is that other nodes don't have this message.

```
Failure summary:

  1. Host:     router1
     Play:     Verify Requirements
     Task:     openshift_health_check
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required Docker images are not available:
                   openshift/origin-deployer:v1.5.1
               Configured registries: docker.io
```

##### Version
```
$ ansible --version
ansible 2.3.1.0
  config file = /home/centos/openshift/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

openshift-ansible-3.6.153-1-40-gf171187
```

##### Steps To Reproduce
1. Run install playbook, this is on a current 1.5.1 installation

##### Additional Information

Bastion is centos7

Hosts are F26 Atomic

Provide any additional information which may help us diagnose the
issue.

```
# Openshift version
openshift_release=v1.5
openshift_image_tag=v1.5.1
```

**Comment by sosiouxme** [comment]
skopeo is used to check availability but we don't really capture details for when it comes back negative; would be helpful to see what the command output was here, otherwise we don't have much to go on.
@djdevin could you run the playbook again with the -vvv option on ansible, capture the log, and attach it? I only really need the part starting with the last task running (`openshift_health_check`), but if that's too sensitive to post, you can send it relatively privately to lmeyer at redhat.com.

**Comment by djdevin** [comment]
Thanks, but of course I can't reproduce it now. We had earlier cluster DNS issues but they appeared fixed. I ran skopeo manually and it looked fine. I'll get a more verbose log if it comes up again.

**Comment by sosiouxme** [comment]
Perhaps we should add in a retry... network blips happen.
