### ISSUE TITLE
RHEL 7 : cannot stat /proc/sys/kernel/exec-shield: No such file or directory

### ISSUE THREAD

**Issue by cello86** [openshift/openshift-ansible#4948]
#### Description
We tried to install Openshift Origin 1.4.0 on a 3 nodes cluster shipped with RHEL 7.3, but during the installation we received this error:

> STDERR:
> 
> sysctl: cannot stat /proc/sys/kernel/exec-shield: No such file or directory
> 
> RUNNING HANDLER [openshift_node : reload systemd units] ***********************************************************
> Monday 31 July 2017  12:33:33 +0200 (0:00:00.211)       0:15:08.728 ***** 

The parameter has been moved out from /proc as reported into this note https://access.redhat.com/solutions/974563.

##### Version
# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

# git describe
openshift-ansible-3.7.1-1-40-g3be2748

##### Steps To Reproduce
We execute the installation ansible playbook config.yml on a RHEL 7 node and after some tasks we noticed this error repetead.

##### Expected Results
We would terminate the installation on the nodes.

##### Additional Information
# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by sdodson** [comment]
@cello86 I don't think it's the cause of your problems, but please be aware that you should be using the `release-1.4` branch of this repo in order to install Origin 1.4. I imagine that this the result of a broken /etc/sysctl.conf prior to running our installer and that needs to be addressed first. Prior to running our installer can you run `systectl -p /etc/sysctl.conf` and see if you get the same error?

**Comment by cello86** [comment]
@sdodson  I confirm that a puppet module apply this change before the installation. We have fixed it and the installation works fine.

Thanks a lot,
Marcello
