### ISSUE TITLE
Provide info on failed nodes after install

### ISSUE THREAD

**Issue by tdudgeon** [openshift/openshift-ansible#5088]
#### Description

As discussed on the mailing list (https://lists.openshift.redhat.com/openshift-archives/users/2017-August/msg00007.html) when a node fails to be provisioned there should be notification of this at the end of the process.

##### Version

Ansible version 22.3.1.0

Git checkout:
```
git describe
openshift-ansible-3.7.1-1-198-g2bc6832
```

##### Steps To Reproduce

Run installer with simple 1 master, 1 node setup. Installer completes, but node has not joined cluster (reason unknown).

##### Expected Results

Some notification at the end of the install process that node(s) have failed to be provisioned, and preferably some reason why.

##### Observed Results
This is what is reported at the end. It appears that all is good, but it is not.
```
PLAY RECAP **************************************************************************************************************************************************************
2c0e37ab-f41e-40f1-a466-a575c85823b6.priv.cloud.scaleway.com : ok=463 changed=166 unreachable=0 failed=0   
5dece82d-6baa-474e-8613-4e038abd6270.priv.cloud.scaleway.com : ok=162 changed=55 unreachable=0 failed=0   
localhost : ok=13 changed=0 unreachable=0 failed=0   
```
(first is the master, second is the node)

On master:
```
oc get nodes
NAME STATUS AGE VERSION
2c0e37ab-f41e-40f1-a466-a575c85823b6.priv.cloud.scaleway.com Ready,SchedulingDisabled 26m v1.6.1+5115d708d7
```
Note only master is running.

##### Additional Information

CentOS Linux release 7.3.1611 (Core)

**Comment by tbielawa** [comment]
My response, copied from openshift-users mailing list,

Can you please provide more information? You full inventory would be very useful right now for debugging. Feel free to mask your hostnames if you wish. What I need to see to debug this further are all the parameters you're setting in the `[OSEv3]` section and applying to each host in `[masters]` and `[nodes]`.

As for those two stalls you mentioned:

> Ensure OpenShift <THING> correctly rolls out (best-effort today)

The delays you experienced are normal and expected. Those delays are typically because the pod images were being downloaded to your hosts. However, you showed your `oc get nodes` output and I noticed your master said `Ready,SchedulingDisabled`. Because your master is labeled as `SchedulingDisabled` then your master should *NOT* be running any pods. In which case that means it wasn't downloading pod images.

Can you please provide the following information:

* The output from `oc get all` on your master
* The output `docker images` on your node *AND* your master
* Your complete inventory file. As I said before, feel free to mask your hostnames or IPs if you prefer.

You logs would also be helpful. Ensure you run ansible-playbook with the -vv option for extra verbosity. You can do this in two ways:

1) If you run the install again you can set:

> log_path = /tmp/ansible.log

in the `[defaults]` section of your ansible.cfg file. 

2) Alternatively you can capture the output of ansible using the `tee` command like so:

> ansible-playbook -vv -i <INVENTORY> ./playbooks/byo/config.yml | tee /tmp/ansible.log

Again, if you wish to keep this information private, my GPG key is in my signature. Short ID is 0333AE37. 


Thanks!

**Comment by tdudgeon** [comment]
Full details are here: https://github.com/OpenRiskNet/home/blob/master/openshift/simple-ansible.md
