### ISSUE TITLE
Can not visit web console after lb_master crashed

### ISSUE THREAD

**Issue by vanloswang** [openshift/openshift-ansible#5292]
#### Description

> Can not visit web console after lb_master crashed. So how to setup a high available lb_master ?

##### Version

```
ansible 2.2.3.0
openshift-ansible-3.6.173.0.5-3
origin-3.6.0
```

##### Steps To Reproduce
1. following https://docs.openshift.org/latest/install_config/install/advanced_install.html#multiple-masters to setup 'MULTIPLE MASTERS WITH MASTER AND ETCD ON THE SAME HOST' with tree master and one lb_master.
2. visit the web console, now visit ok.
3. poweroff the lb_master, then visit the web console, now visit failed.
4. change to master ip or domain address to visit web console, visit failed.

##### Expected Results
visit master web console ok after lb_master crashed.

##### Observed Results
visit failed!!!

**Comment by sdodson** [comment]
That's correct, the load balancer itself is not hightly available, it's intended just for proof of concept purposes. We don't provide a solution for that because in most environments customers tend to have a preferred solution for load balancing already. If it's a cloud environment that's something like an AWS ELB or on premises something like an F5 device or other highly available load balancing solution.

This isn't something we've validated but you should be able to deploy multiple hosts in the lb group and then make use of ipfailover and keepalived to load balance a virtual ip address between the two load balancers.

**Comment by vanloswang** [comment]
@sdodson Could I deploy lb and lb ipfailover with keepalived  along with the three master?

**Comment by sdodson** [comment]
Yes you could do that too.
