### ISSUE TITLE
not able to login jenkins in openshift

### ISSUE THREAD

**Issue by naveenkumartangallapally** [openshift/openshift-ansible#5383]
Hi,

I deployed jenkins in openshift environment and its working fine.

but i am not able to login jenkins and where i can find jenkins credentials in openshift.

i was tried also to set sudo access by
oadm policy add-scc-to-user anyuid -z default

but its not working.can any one help me to resolve the issue

**Comment by gabemontero** [comment]
Hi @naveenkumartangallapally - going to need a few more specifics in order to help you.

1) How did you instantiate jenkins into openshift?  Did you use our template(s)?

2) Please provide the contents of the jenkins pod log

3) Please provide a screen shot of your browser window when things do not work

4) run `oc get sa <jenkins service account name> -o yaml` and provide the output

**Comment by bparees** [comment]
closing due to lack of feedback needed to debug.
/close
