### ISSUE TITLE
openshift-ansible should allow for a storageclass definition

### ISSUE THREAD

**Issue by oybed** [openshift/openshift-ansible#5666]
#### Description
When choosing to use dynamic storage with logging and metrics, it won't successfully bring up these services until a storageclass has been defined to allow for the dynamic provisioning of the backend storage. Hence, there should be an inventory variable that allows for setting up a storageclass as part of openshift-ansible / provisioning of the cluster. 

##### Version

```
> git describe
openshift-ansible-3.6.173.0.45-1
```

##### Steps To Reproduce
1. Set up an inventory with the following variables, then perform a cluster provisioning:
```
openshift_hosted_metrics_deploy: true
openshift_metrics_install_metrics: true
openshift_metrics_cassandra_storage_type: dynamic
openshift_metrics_cassandra_pvc_size: 50G
```
2. After a successful provisioning of the cluster,  observe that the cassandra PVC is NOT bound and stuck in a "pending" state until a storageclass has been defined. 

##### Expected Results
I'd expect that a storageclass can be defined at time of provisioning and hence allow for a successful deployment with dynamic storage. 

```
Example command and output or error messages
```

##### Observed Results
See step 2 of "Steps to Reproduce" above

##### Additional Information
N/A

**Comment by fgimenezm** [comment]
I think the problem is here:
https://github.com/openshift/openshift-ansible/blob/fcedb45f4ca3294979caf20d4d3026a26ff57b9a/roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml#L51

It only adds the storage class name if `openshift_metrics_cassandra_storage_type` is *not* set to dynamic which is odd.

Then in the "dynamic" part:
https://github.com/openshift/openshift-ansible/blob/fcedb45f4ca3294979caf20d4d3026a26ff57b9a/roles/openshift_metrics/tasks/generate_cassandra_pvcs.yaml#L68

it does *not* add the storage class.
so the PVC remains pending because it doesn't have a class to do the dynamic provisioning.

Isn't that logic backwards?

**Comment by fgimenezm** [comment]
https://github.com/openshift/openshift-ansible/issues/5666

that explains it
