### ISSUE TITLE
setting password for CloudForms / ManageIQ

### ISSUE THREAD

**Issue by joelddiaz** [openshift/openshift-ansible#5849]
#### Description

When running the full installer or just the playbook for installing CloudForms / ManageIQ, the pod comes up with default credentials. There should be a way to provide a non-default password that gets set up during installation.

##### Version
```
ansible 2.3.1.0 

openshift-ansible-3.7.0-0.159.0-6-g63b77fb

package atomic-openshift-utils is not installed
openshift-ansible-3.5.120-1.git.0.c60f69a.el7.noarch
```

##### Steps To Reproduce
1. install CloudForms / ManageIQ: ansible-playbook -i ~/my-inventory ./git/openshift-ansible/playbooks/byo/openshift-management/config.yml
2. wait for completion, get route (oc get route -n openshift-management httpd), and authenticate to CloudForms / ManageIQ with default creds

##### Expected Results
I would expect that there is a way to provide my own password that would be initialized during the installation.

##### Observed Results
The CloudForms / ManageIQ installer just takes a container image and never has a step to set up a password so you end up with the default public image credentials.

##### Additional Information

Pretty standard inventory file with the following CloudForms / ManageIQ vars:

```
openshift_management_install_management=True
openshift_management_storage_class=cloudprovider
```

**Comment by tbielawa** [comment]
We have no way to control this through the installer currently. We have
raised this issue recently with that team in a meeting.

This should be directed to the github manageiq/manageiq-pods project.


On Oct 23, 2017 12:00 PM, "Joel Diaz" <notifications@github.com> wrote:

Description

When running the full installer or just the playbook for installing
CloudForms / ManageIQ, the pod comes up with default credentials. There
should be a way to provide a non-default password that gets set up during
installation.
Version

ansible 2.3.1.0

openshift-ansible-3.7.0-0.159.0-6-g63b77fb

package atomic-openshift-utils is not installed
openshift-ansible-3.5.120-1.git.0.c60f69a.el7.noarch

Steps To Reproduce

   1. install CloudForms / ManageIQ: ansible-playbook -i ~/my-inventory
   ./git/openshift-ansible/playbooks/byo/openshift-management/config.yml
   2. wait for completion, get route (oc get route -n openshift-management
   httpd), and authenticate to CloudForms / ManageIQ with default creds

Expected Results

I would expect that there is a way to provide my own password that would be
initialized during the installation.
Observed Results

The CloudForms / ManageIQ installer just takes a container image and never
has a step to set up a password so you end up with the default public image
credentials.
Additional Information

Pretty standard inventory file with the following CloudForms / ManageIQ
vars:

openshift_management_install_management=True
openshift_management_storage_class=cloudprovider

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-ansible/issues/5849>, or mute the
thread

**Comment by joelddiaz** [comment]
opened manageiq/manageiq-pods#237

**Comment by tbielawa** [comment]
@joelddiaz Thanks!
