### ISSUE TITLE
Docker Image Availability error even though I can Docker pull images from Docker.io

### ISSUE THREAD

**Issue by AdwaitLele** [openshift/openshift-ansible#6189]
#### Description

Provide a brief description of your issue here. For example:

On a single master install, getting a "docker_image_availability" error. It seems that I can't access docker.io which is strange because I can docker pull images fine.

```
2. Hosts:    domain1.domain.com, domain2.domain.com
     Play:     Verify Requirements
     Task:     Verify Requirements - EL
     Message:  One or more checks failed
     Details:  check "docker_image_availability":
               One or more required container images are not available:
                   cockpit/kubernetes,
                   openshift/origin-deployer:v3.6.0,
                   openshift/origin-docker-registry:v3.6.0,
                   openshift/origin-haproxy-router:v3.6.0,
                   openshift/origin-pod:v3.6.0
               Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>
               Default registries searched: docker.io
               Failed connecting to: docker.io
```

##### Version

```
$ ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### Steps To Reproduce
1. Run install playbook (for openshift origin version 3.6)

##### Additional Information

OS information:
```
$ cat /etc/centos-release
CentOS Linux release 7.4.1708 (Core)

```

**Comment by aizuddin85** [comment]
can you run  `git describe`?

**Comment by AdwaitLele** [comment]
```
# git describe
openshift-ansible-3.7.0-0.157.0
```

**Comment by sosiouxme** [comment]
As you can see:

`Checked with: skopeo inspect [--tls-verify=false] [--creds=<user>:<pass>] docker://<registry>/<image>`

... the check is not using `docker pull` to check whether it can pull the image, but rather doing a quick check with skopeo. So the environment is a bit different. In this case:

```
               Default registries searched: docker.io
               Failed connecting to: docker.io
```

It seems skopeo is failing to connect to docker.io at all. What might be configured into docker that isn't for skopeo? Do you have firewalled internet access with an http/s proxy configured for docker? What happens if you do:

`skopeo inspect docker://docker.io/openshift/origin-deployer:v3.6.0`

Part of the check is also doing a tcp connect to see if it can reach the registry; that may be what's failing here. If you did a run with the `-vvv` flag added it may have more useful output about what actually happened.

**Comment by sosiouxme** [comment]
I'm happy to look into this further with a bit more information. Feel free to re-open as needed. Also there is further development work going on [here](https://github.com/openshift/openshift-ansible/pull/6716) that might be relevant.
