### ISSUE TITLE
How to use CA signed certificate to replace self-signed one

### ISSUE THREAD

**Issue by xionglingfeng** [openshift/openshift-ansible#619]
I installed OpenShift with playbook/byo. Is there anyway to specific certificates during the installation to prevent generating self-signed certs? If not, how can I  replace those self-signed certificates with CA signed ones?

**Comment by ReSearchITEng** [comment]
I subscribe. I have same question for few months, could not find an answer / script yet.

**Comment by detiber** [comment]
I'm hoping to have something for this issue next week sometime.  It will require a newer build of OpenShift to support the ability to specify multiple certs/ca bundles to use, since we will still require the self-signed CA for internal service names and IPs that would not be able to be addeed as a SAN from a valid CA.

**Comment by tbielawa** [comment]
Certificate handling has seen major updates since this issue was opened

https://docs.openshift.org/latest/install_config/certificate_customization.html

This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
