### ISSUE TITLE
Error during openshift hosted registry installation

### ISSUE THREAD

**Issue by davidaah** [openshift/openshift-ansible#6521]
#### Description

During the 3.7 installation, the following play is run to install a gluster backed openshift hosted docker registry https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/openshift_hosted/tasks/storage/glusterfs.yml

We are seeing the following error during install:

TASK [openshift_hosted : Activate registry maintenance mode] *******************
<date> ******* 
fatal: [<host name>]: FAILED! => {"changed": false, "failed": true, "msg": "argument env_vars is of type <type 'list'> and we were unable to convert to dict: <type 'list'> cannot be converted to a dict"}

Upon further inspection it appears that the playbook ( https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_hosted/tasks/storage/glusterfs.yml#L49-L80 ) is passing an array not a dictionary to oc_env module's `env_vars` as mentioned in the module documentation at in https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/lib_openshift/src/doc/env#L74-L82 and the code https://github.com/openshift/openshift-ansible/blob/release-3.7/roles/lib_openshift/library/oc_env.py#L1929

This appears to be true of the current `master` branch of the module and play

##### Version

```
openshift-ansible-3.7.9-1-47-gafef12f
```

##### Steps To Reproduce

Run installer with glusterfs based registry

##### Expected Results
it should install

```
ansible-playbook playbooks/byo/config.yml
```

##### Observed Results
Describe what is actually happening.

```
See above for error output
```

**Comment by davidaah** [comment]
@kareiva @jarrpa @sdodson is the fact that this feature isn't tested/supported documented anywhere? i'm fine to close this if this is already doc'd somewhere or if it is planned to be?

**Comment by sdodson** [comment]
I have to defer to @jarrpa for this. I can't speak to the priority of CNS/CRS features and when they'll be finished.

**Comment by jarrpa** [comment]
@davidaah Nope. In general I would say there is no precedent for documenting extraneous features as unsupported as lack of support seems to be implicit until documented otherwise. That said, "supported" just means Red Hat has verified the feature and is willing to commit support time to them. This Issue is still valid regardless of whether RH supports it or not as long as I say I want to fix it. Which I do. :) There's currently no schedule for when this would even make it to testing downstream, however, so don't count on it for production use any time soon.

**Comment by davidaah** [comment]
Sounds good, do you want me to leave this open then? Not sure exactly how issues are being split between here and bugzilla
