### ISSUE TITLE
Installer fails when using Vagrant and VirtualBox 

### ISSUE THREAD

**Issue by wattsteve** [openshift/openshift-ansible#705]
Following the VirtualBox Vagrant instructions here on a Macbook  - https://github.com/openshift/openshift-ansible/blob/master/README_vagrant.md

Note: Even after installing the RHEL 7 VirtualBox box, the script always uses a centos7 box. 

"vagrant up --no-provision" completes successfully
"vagrant provision" fails with the error below:

TASK: [openshift_manage_node | Wait for Node Registration] *******************\* 
changed: [master] => (item=ose3-master.example.com)
failed: [master] => (item=ose3-node1.example.com) => {"attempts": 20, "changed": true, "cmd": ["oc", "get", "node", "ose3-node1.example.com"], "delta": "0:00:00.421160", "end": "2015-10-19 13:24:28.739365", "failed": true, "item": "ose3-node1.example.com", "rc": 1, "start": "2015-10-19 13:24:28.318205", "warnings": []}
stderr: Error from server: node "ose3-node1.example.com" not found
msg: Task failed as maximum retries was encountered
failed: [master] => (item=ose3-node2.example.com) => {"attempts": 20, "changed": true, "cmd": ["oc", "get", "node", "ose3-node2.example.com"], "delta": "0:00:00.437149", "end": "2015-10-19 13:26:22.521020", "failed": true, "item": "ose3-node2.example.com", "rc": 1, "start": "2015-10-19 13:26:22.083871", "warnings": []}
stderr: Error from server: node "ose3-node2.example.com" not found
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/Users/steve/vagrant.retry

localhost                  : ok=10   changed=0    unreachable=0    failed=0  
master                     : ok=167  changed=49   unreachable=0    failed=1  
node1                      : ok=58   changed=21   unreachable=0    failed=0  
node2                      : ok=58   changed=21   unreachable=0    failed=0   

Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

**Comment by snafuprinzip** [comment]
Hi, I have encountered the same or similar problem with a single master on a kvm virtual machine and two hardware nodes as well (all three running RHEL 7.2, but to be honest I am not sure if this a bug or just something I forgot to configure correctly before installing from the master node.

Anyway, any help is greatly appreciated!  (-:

I should mention that I had aborted the installation the first time because it was hanging at the firewalld restart and restarted the ansible-playbook run again. (the flanneld steps are skipped on all nodes, but I'm not sure if that is the problem).

It looks like there has been no virtual network configured on the two nodes (no bridges or other interfaces except the physical and the bonding interface), while on the master everything looks fine.


Without the virtual network the nodes complain in the messages file:
Jan  5 16:03:56 189tuxtst402 origin-node: I0105 16:03:56.586882   25099 kubelet.go:931] Unable to register 189tuxtst402.gfi.ihk.de with the apiserver: Post https://189tuxosm001.gfi.ihk.de:8443/api/v1/nodes: dial tcp 10.189.91.160:8443: i/o timeout
Jan  5 16:03:57 189tuxtst402 docker: time="2016-01-05T16:03:57.388808357+01:00" level=info msg="GET /version"
Jan  5 16:03:57 189tuxtst402 origin-node: I0105 16:03:57.389106   25099 kubelet.go:2405] Recording NodeReady event message for node 189tuxtst402.gfi.ihk.de
Jan  5 16:03:57 189tuxtst402 origin-node: I0105 16:03:57.389139   25099 kubelet.go:928] Attempting to register node 189tuxtst402.gfi.ihk.de
Jan  5 16:03:57 189tuxtst402 origin-node: W0105 16:03:57.631922   25099 common.go:577] Could not find an allocated subnet for node: 189tuxtst402.gfi.ihk.de, Waiting...
Jan  5 16:04:01 189tuxtst402 docker: time="2016-01-05T16:04:01.045576721+01:00" level=info msg="GET /version"
Jan  5 16:04:06 189tuxtst402 docker: time="2016-01-05T16:04:06.046586627+01:00" level=info msg="GET /version"
Jan  5 16:04:09 189tuxtst402 origin-node: E0105 16:04:09.344069   25099 event.go:207] Unable to write event: 'Post https://189tuxosm001.gfi.ihk.de:8443/api/v1/namespaces/default/events: dial tcp 10.189.91.160:8443: i/o timeout' (may retry after sleeping)


the console output of the installation just says that the oc get node 189tuxtst40[12] failed:
PLAY [Set schedulability] *****************************************************

GATHERING FACTS ***************************************************************
ok: [189tuxosm001.gfi.ihk.de]

TASK: [openshift_manage_node | Wait for Node Registration] ********************
ok: [189tuxosm001.gfi.ihk.de] => (item=189tuxosm001.gfi.ihk.de)
failed: [189tuxosm001.gfi.ihk.de] => (item=189tuxtst401.gfi.ihk.de) => {"attempts": 20, "changed": false, "cmd": ["oc", "get", "node", "189tuxtst401.gfi.ihk.de"], "delta": "0:00:00.212830", "end": "2016-01-05 14:40:26.485109", "failed": true, "item": "189tuxtst401.gfi.ihk.de", "rc": 1, "start": "2016-01-05 14:40:26.272279", "stdout_lines": [], "warnings": []}
stderr: Error from server: node "189tuxtst401.gfi.ihk.de" not found
msg: Task failed as maximum retries was encountered
failed: [189tuxosm001.gfi.ihk.de] => (item=189tuxtst402.gfi.ihk.de) => {"attempts": 20, "changed": false, "cmd": ["oc", "get", "node", "189tuxtst402.gfi.ihk.de"], "delta": "0:00:00.193739", "end": "2016-01-05 14:42:13.794365", "failed": true, "item": "189tuxtst402.gfi.ihk.de", "rc": 1, "start": "2016-01-05 14:42:13.600626", "stdout_lines": [], "warnings": []}
stderr: Error from server: node "189tuxtst402.gfi.ihk.de" not found
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/config.retry

189tuxosm001.gfi.ihk.de    : ok=313  changed=66   unreachable=0    failed=1
189tuxtst401.gfi.ihk.de    : ok=100  changed=23   unreachable=0    failed=1
189tuxtst402.gfi.ihk.de    : ok=100  changed=23   unreachable=0    failed=1
localhost                  : ok=13   changed=0    unreachable=0    failed=0


my ansible hosts file looks like this:
[OSEv3:children]
masters
nodes

[OSEv3:vars]
ansible_ssh_user=root
osm_default_subdomain=tardis.gfi.ihk.de
deployment_type=origin

[masters]
189tuxosm001.gfi.ihk.de

[nodes]
189tuxosm001.gfi.ihk.de openshift_node_labels="{'region': 'infra', 'zone': 'default'}" openshift_schedulable=false
189tuxtst401.gfi.ihk.de openshift_node_labels="{'region': 'primary', 'zone': 'rz4'}"
189tuxtst402.gfi.ihk.de openshift_node_labels="{'region': 'primary', 'zone': 'rz4'}"

Thank you very much!

**Comment by jae2** [comment]
I also hit this problem.
If you look on each guest machine you'll notice one of the interfaces is down (eth1):

```
ip addr show
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
    link/ether ..... etc.. 
```

To resolve I had to restart my virtual boxes:

``` vagrant halt ```

``` vagrant up ```

Then when you ssh onto the box you'll see that theres a load of new interfaces all of which are up. Not sure, why this.

**Comment by detiber** [comment]
@jae2 I suspect the issue may be related to the way that we attempt to restart the network (which was needed previously to work around a different networking related bug): https://github.com/openshift/openshift-ansible/blob/master/Vagrantfile#L47

Unfortunately, I do not have a VirtualBox host to test against.

**Comment by jae2** [comment]
Just tried commenting out this line, the problem unfortunately still persists:

```
vagrant ssh node1
[vagrant@ose3-node1 ~]$ ip addr show
<snip>
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast state DOWN qlen 1000
<snip>
```

**Comment by tbielawa** [comment]
We no longer support vagrant in `openshift-ansible`. The vagrant file was removed in https://github.com/openshift/openshift-ansible/pull/2654 Please see https://github.com/openshift/openshift-ansible-contrib for vagrant support.
