### ISSUE TITLE
add a flag to disable configuring the origin repo

### ISSUE THREAD

**Issue by JohnTheodore** [openshift/openshift-ansible#756]
I'm using nodes that don't have Internet access. I've configured all the origin, openvswitch etcd packages already on the existing internal repositories. I can complete an install with openshift ansible, but it takes 5 hours. One of the reasons it takes so long, is yum times out when connecting to centos.org and other repos. It would be nice if these repos weren't added if a disable flag is set.

**Comment by detiber** [comment]
@JohnTheodore hmm, the only repo that openshift_ansible should be setting for origin deployments is the copr repo (https://copr-be.cloud.fedoraproject.org/results/maxamillion/origin-next/epel-7-$basearch/) which is listed with skip_if_unavailable=True, so there shouldn't be anything hanging up installs.

That said, depending on how you are invoking openshift_ansible and the base image being used, it is highly likely that the CentOS repos are enabled by default. It does look like the default timeout is 30s though, so it might be a good idea to update the repo file we lay down for origin to have a much shorter timeout.

That said, I do not see an issue with having a flag to disable repo creation.

If you are able to provide a PR for adding the flag, I'll be happy to expedite a review on it to get it merged, otherwise I suspect it may be a bit before we can get around to tackling this considering the limited scope of the issue (affecting only origin deployments on systems without internet access).

**Comment by elyscape** [comment]
@detiber: Where does Ansible decide which repos to install? As far as I can tell, nothing references the COPR repo aside from [a comment in the example hosts file](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.0.76-1/inventory/byo/hosts.origin.example#L82-L83), but somehow it's getting installed even if you don't specify a value for `openshift_additional_repos`.

**Comment by sdodson** [comment]
@elyscape This copies a set of default repos based on deployment type https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_repos/tasks/main.yaml#L61-L67

**Comment by elyscape** [comment]
Aha!

**Comment by vrutkovs** [comment]
This is now controlled by `openshift_enable_origin_repo=false`
