### ISSUE TITLE
stderr: unable to connect to a server to handle "imagestreamlists"

### ISSUE THREAD

**Issue by brettneese** [openshift/openshift-ansible#779]
When I'm trying to install, I'm getting:

```
failed: [core.brettneese.com] => {"changed": false, "cmd": ["oc", "create", "-n", "openshift", "-f", "/usr/share/openshift/examples/image-streams/image-streams-rhel7.json"], "delta": "0:00:00.179288", "end": "2015-10-31 14:44:13.111711", "failed": true, "failed_when_result": true, "rc": 1, "start": "2015-10-31 14:44:12.932423", "stdout_lines": [], "warnings": []}
stderr: unable to connect to a server to handle "imagestreamlists": Get https://core.brettneese.com:8443/oapi: dial tcp [2604:880:a:6::f4e]:8443: connection refused

FATAL: all hosts have already failed -- aborting

```

Right now I'm just trying to do a single shared host/node deployment on a VPS - we're waiting on new hardware -- so my ansible hosts looks like this:

```
# Set variables common for all OSEv3 hosts
[OSEv3:vars]
# SSH user, this user should allow ssh based auth without requiring a password
ansible_ssh_user=root

product_type=openshift
deployment_type=origin

# If ansible_ssh_user is not root, ansible_sudo must be set to true
#ansible_sudo=true

# enable htpasswd authentication
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/openshift/openshift-passwd'}]

# define openshift types
[OSEv3:children]
masters
# nodes

# host group for masters
[masters]
core.brettneese.com 

# host group for nodes, includes region info
# [nodes]
# node1.brettneese.com openshift_node_labels="{'region': 'infra', 'zone': 'default'}"
```

Which I _think_ is correct. I've also tried uncommenting the lines that create a node at node1.brettneese.com, to no avail. 

Can't seem to find much on this particular problem. Help? I'm on `CentOS Linux release 7.1.1503 (Core).`

**Comment by detiber** [comment]
One thing I notice (unrelated to the error you are seeing) is that you'll want to have the master defined as a node if you are using openshift-sdn (which is the default for Origin). Which would look like the following:
```
[nodes]
core.brettneese.com openshift_schedulable=False
```
If you want to run pods on the master host, then you would omit the openshift_schedulable variable.

Now, onto the actual issue you are seeing. The message seems to indicate that the master service is not running at that point. There should be an error in the journal logs that would help narrow down the issue: `journalctl -u origin-master -l` (The -l flag is important otherwise the log entries will appear truncated).

It could also be that ipv6 is enabled on the host and the rejection from the ip6tables default rule is causing ipv4 fallback to fail. In which case, you  may have to change the default rule to DROP or Add the service ports to ip6tables as well. 

Master service ports: 4001/tcp, 8443/tcp, 53/tcp, 53/udp
Node service ports: 10250/tcp, 4789/udp
Nodes that will host the openshift-router (or other services that bind to non-sdn or portal network addresses): 80/tcp, 443/tcp

**Comment by tbielawa** [comment]
This issue has been inactive for quite some time. Please update and reopen this issue if this is still a priority you would like to see action on.
