### ISSUE TITLE
Scaling doesn't work on origin 3.10

### ISSUE THREAD

**Issue by tomassedovic** [openshift/openshift-ansible#7946]
#### Description

Adding additional nodes to the `new_nodes` group and then running `playbooks/openshift-node/scaleup.yml` does not add the nodes to the new cluster (and it seems to not add the necessary services in either).

##### Version

Please put the following version information in the code block
indicated below.

* Your ansible version per `ansible --version`:

```
ansible 2.5.0
  config file = /home/thomas/code/openshift/openshift-ansible/ansible.cfg
  configured module search path = [u'/home/thomas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

* The output of `git describe`: `openshift-ansible-3.10.0-0.20.0-8-g3c5d997dc`

##### Steps To Reproduce
1. Deploy an Origin + CentOS cluster (1 master, 1 infra, 1 app node)
2. Log in to the master node and run `oc get nodes`
    * Three nodes will be listed
3. Create a new VM and add it in the `OSEv3` and `new_nodes` inventory groups
4. Run `playbooks/openshift-node/scaleup.yml`

##### Expected Results

`oc get nodes` will show 4 nodes -- including the new one.

##### Observed Results

The new node is not shown and it doesn't have the `/etc/origin` directory either.

##### Additional Information

I tried to copy the `deploy_cluster.yml` and remove any tasks not related to the nodes:

```
---
- import_playbook: init/main.yml

- import_playbook: openshift-node/private/bootstrap.yml

- import_playbook: openshift-node/private/join.yml

- import_playbook: openshift-node/private/config.yml
```

Running that playbooks seems to have worked (the new node is now in the cluster). But I'm not sure whether there's something missing or extraneous. The scaleup playbook doesn't seem to have the bootstrap and join entries. Is it enough to just add them in?

cc @smarterclayton

**Comment by smarterclayton** [comment]
I’ll take a look at scaleup, it probably just needs to pick up bootstrap
and join

On Apr 13, 2018, at 9:17 AM, Tomas Sedovic <notifications@github.com> wrote:

Description

Adding additional nodes to the new_nodes group and then running
playbooks/openshift-node/scaleup.yml does not add the nodes to the new
cluster (and it seems to not add the necessary services in either).
Version

Please put the following version information in the code block
indicated below.

   - Your ansible version per ansible --version:

ansible 2.5.0
  config file = /home/thomas/code/openshift/openshift-ansible/ansible.cfg
  configured module search path =
[u'/home/thomas/.ansible/plugins/modules',
u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1
20180303 (Red Hat 7.3.1-5)]


   - The output of git describe:
   openshift-ansible-3.10.0-0.20.0-8-g3c5d997dc

Steps To Reproduce

   1. Deploy an Origin + CentOS cluster (1 master, 1 infra, 1 app node)
   2. Log in to the master node and run oc get nodes
      - Three nodes will be listed
   3. Create a new VM and add it in the OSEv3 and new_nodes inventory groups
   4. Run playbooks/openshift-node/scaleup.yml

Expected Results

oc get nodes will show 4 nodes -- including the new one.
Observed Results

The new node is not shown and it doesn't have the /etc/origin directory
either.
Additional Information

I tried to copy the deploy_cluster.yml and remove any tasks not related to
the nodes:

---
- import_playbook: init/main.yml

- import_playbook: openshift-node/private/bootstrap.yml

- import_playbook: openshift-node/private/join.yml

- import_playbook: openshift-node/private/config.yml

Running that playbooks seems to have worked (the new node is now in the
cluster). But I'm not sure whether there's something missing or extraneous.
The scaleup playbook doesn't seem to have the bootstrap and join entries.
Is it enough to just add them in?

cc @smarterclayton <https://github.com/smarterclayton>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/openshift-ansible/issues/7946>, or mute the
thread

**Comment by tomassedovic** [comment]
Yeah, that seems to have worked. I'll open the PR.
