### ISSUE TITLE
Why the ansible playbook uses images from docker hub

### ISSUE THREAD

**Issue by pgeorgiev333** [openshift/openshift-ansible#7950]
The https://docs.openshift.org/latest/install_config/install/advanced_install.html#advanced-install-configuring-registry-console says that the default registry is registry.access.redhat.com but when i try to deploy 3.9 using the playbooks the pod images for example are downloaded from docker hub (openshift/origin-pod:v3.9.0)

There is a pod image here:
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/openshift3/ose-pod

I'm really confused. Can someone explain please?

Thanks

p.s. 

another example:
docker.io/openshift/origin-deployer is used instead of https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/openshift3/ose-deployer

I'm using the RPM installation (not the containerized one). Is this the reason?

**Comment by jkaurredhat** [comment]
So the issue is if you are not able to pull from registry.access.redhat.com it will skip to pull from docker.io.

In order to prevent you can also block docker.io in docker confirguration,

**Comment by pgeorgiev333** [comment]
But the playbooks reference explicitly docker.io images? Is it a documentation error on the openshift.org site?

**Comment by DanyC97** [comment]
@pgeorgiev333 so what is the underlying problem here: are you trying to deploy on-prem/ no access to `docker.io` ?

in your description you said 

> There is a pod image here:
https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/openshift3/ose-pod

Don't confuse OSE with Origin, they former one is the enterprise version and as such has different image in a different location.

For origin the images do come from docker.io and from different repositories:
* openshift
* gluster
* heketi

the latter 2 are only if you trying to deploy GlusterFS

**Comment by pgeorgiev333** [comment]
I was confused by the official origin documentation first. Then i was confused by the ansible installer that failed to find some images i was able to find on the redhat repo, but not on docker hub.

My recent openshift origin 3.9 installs confirm that i do not need images from the redhat repo so it's all good now.
Thanks for the replies.

p.s. 

Can someone please fix the official documentation:)

https://docs.openshift.org/latest/install_config/install/advanced_install.html

![image](https://user-images.githubusercontent.com/16955574/38987792-a8847d4e-43d9-11e8-9cea-76ec2731afb9.png)

![image](https://user-images.githubusercontent.com/16955574/38987804-bb5b3c82-43d9-11e8-9d94-229e82c70a40.png)
