### ISSUE TITLE
Information Request:  Is deploy_cluster.yml intended to be re-usable?

### ISSUE THREAD

**Issue by clcollins** [openshift/openshift-ansible#9035]
#### Description

Just have a question:  Should we be able to re-run the deploy_cluster playbook to fix/update things within the cluster? It appears in most cases to skip over tasks that have already been done (as one would expect from Ansible), but not in all cases.

And if we make some changes to the variables in our inventory, and re-run, it seems to change some things, but doesn't, for example, redeploy or recreate services that may be making use of the old information (eg, replacing certificates).

If deploy_cluster.yml should *not* be run again, what is the correct way to make changes to and maintain the cluster?

Thanks for any guidance you can provide!

**Comment by michaelgugino** [comment]
Rerunning may not achieve the desired outcome on a running cluster.  We have a variety of plays for things such as redeploying certificates on a running cluster.  The documentation should explain all the different areas we provide plays for.

**Comment by clcollins** [comment]
Thanks @michaelgugino.  I believe I have seen those.  I will spend some more time looking, then.  Thanks for the reply.

**Comment by benfairless** [comment]
Is there a goal to eventually produce a truely idempotent deployment script?

I am trying to deploy Openshift in a way where I can reproduce the same steps as part of a CI pipeline and would like to be able to run a single playbook to do so.

**Comment by michaelgugino** [comment]
@benfairless No.  If you have a specific need in some area for your CI pipeline, please let us know.

**Comment by benfairless** [comment]
Hopefully I'm not derailing this thread but this is what I'd like to achieve:

As an Engineer I want multiple Openshift environments so that I can test upgrades, implement new customisations, and make modifications in a production-like environment, in order to validate my changes before pushing them onto our production multi-tenant environment.

I would like to automate the deployment of Openshift and the promotion of changes through our environments. At the moment our pipeline performs the following steps:
 - provision environment (using Terraform)
 - configure environment (using Ansible, where we import and run the `deploy_cluster.yml` playbook followed by some of our own to add customisations such as additional S2I templates)
 - run some tests to ensure our customisations are working as expected

I'd like to be able to run Ansible idempotently so that I know it is applying changes that are necessary but not changing anything unnecessarily. I appreciate changing certain inventory variables will cause destructive changes but I'd like to minimise these and have a single, automated, way to maintain the cluster.

I hope this sheds light on what I'd like to achieve and hopefully it is similar to what @clcollins is asking about. Any information regarding this topic would be appreciated.

**Comment by michaelgugino** [comment]
@benfairless 

Yes, that would be an ideal workflow.  Unfortunately, re-running deploy_cluster against a running cluster is not supported; any customization you wish to make to a running cluster would have to be done through one of the various playbooks we supply, or something that you have created yourself (for example, we don't have a playbook to update arbitrary values in master configs and roll them, you would need to bring that automation yourself).

You really start getting into the weeds when you consider there may be some level of drift between a cluster that installed fresh at, say, 3.9, and one that was upgraded to 3.9 from 3.7, and one that was upgraded from 3.7.2 to 3.9.1 vs one that was upgraded from 3.7.4 to 3.9.2, etc.  Not to mention, underlying operating system packages (such as the kernel level or any number of system dependencies such as selinux policies) can impact the ability to completely replicate the workflow as well.

The more closely you can replicate all that, the more success you will have.  I definitely encourage having a stage cluster that can be quickly created and destroyed to gate changes before they land on your production cluster.

**Comment by benfairless** [comment]
Thank you for your response @michaelgugino. This has shed a lot of light on how our workflow should be implemented.
