### ISSUE TITLE
Set the default sandbox role APBs run with under Automation Broker to 'admin' instead of 'edit' to allow creation of RoleBindings in target namespace

### ISSUE THREAD

**Issue by jwmatthews** [openshift/openshift-ansible#9231]
#### Description

The Eclipse CHE team requires the ability to create a [Role Binding from within their APB](https://github.com/ansibleplaybookbundle/eclipse-che-apb/blob/master/roles/provision-eclipse-che-apb/tasks/che.yml#L10)

The default configuration of Automation Broker sets the [sandbox role to 'edit'](https://github.com/openshift/openshift-ansible/blob/master/roles/ansible_service_broker/defaults/main.yml#L21) while 'admin' is required for this operation to succeed.

Current recommendation is for a cluster administrator to tweak this setting and restart the Automation Broker.

Eclipce CHE team is requesting that the default sandbox role be changed from 'edit' to 'admin'.
This means that the APB would run with 'admin' privileges in the target namespace opposed to 'edit'

This issue is to track that discussion, asking for guidance from @openshift/sig-security 

@enj @simo5 thoughts, do you have concerns if we change the sandbox role to 'admin' opposed to 'edit'?

cc @openshift/sig-ansible-service-broker

**Comment by enj** [comment]
> The Eclipse CHE team requires the ability to create a Role Binding from within their APB

Why?

They are trying to assign the admin cluster role to a SA in the namespace.  This means that they have destroyed the distinction between admin and edit in that namespace.  Anyone with the edit rights in the namespace will be able to read the SA's secret and use that to escalate to admin.  Thus their approach is broken in general.

> The default configuration of Automation Broker sets the sandbox role to 'edit' while 'admin' is required for this operation to succeed.

Correct.  This is to limit the escalation paths available to APBs.  It also avoids the issue I mentioned above.

> Current recommendation is for a cluster administrator to tweak this setting and restart the Automation Broker.

Seems fine to let the cluster admin opt-in if they desire to.  A per APB role configuration would be best.

> Eclipce CHE team is requesting that the default sandbox role be changed from 'edit' to 'admin'.
> ...
> you have concerns if we change the sandbox role to 'admin' opposed to 'edit'?

No, we should not reduce the default security for all APBs to support their use case.  I realize that some APBs will need higher access rights.  This should be handled on a per APB basis and any APB needing these extra rights should require explict opt-in from the cluster admin.

**Comment by enj** [comment]
Long term I am hoping to have more robust token delegation flows that makes it so that the ASB gets a token for the user and simply uses it to perform all actions.  If the user has the correct access rights, everything works as expected and no specific access is required on the ASB side.

**Comment by liggitt** [comment]
> explict opt-in from the cluster admin.

or from a namespace admin in that namespace, who can also choose to grant the admin role to that service account

**Comment by enj** [comment]
> or from a namespace admin in that namespace, who can also choose to grant the admin role to that service account

IIRC the resistance to this flow is that it must be manually done out of band by the user (since the actual provisioning is done by the ASB SA which only has edit rights).

---

From https://github.com/ansibleplaybookbundle/eclipse-che-apb/issues/17 @l0rd

> why we need a RoleBinding with role_ref_kind: ClusterRole instead of role_ref_kind: Role and

You still need admin rights to create roles in the namespace.

> if sandbox_role set to edit would be enough to create a RoleBindings with role_ref_kind: Role

It does not.  All RBAC related actions require admin.

**Comment by l0rd** [comment]
> > if sandbox_role set to edit would be enough to create a RoleBindings with role_ref_kind: Role

> It does not. All RBAC related actions require admin.

@enj thanks that is clear now. We need a ServiceAccount with edit rights in the provisioned namespace:

1) You are saying that this approach is broken. Why? I don't get the argument about having access to SA secrets: nobody else should have edit rights in the namespace except the SA itself.
2) What should be the right approach to let Che create pods, services, pvcs and routes?

**Comment by enj** [comment]
> You are saying that this approach is broken. Why? 

The linked YAML file grants `admin` to the SA.  That is incorrect.  It should have `edit` at most.

> I don't get the argument about having access to SA secrets

1. User `A` has `edit` rights in namespace `B`
2. SA `C` has `admin` rights in namespace `B`
3. User `A` uses SA `C`'s secret to become the SA, and thus has indirect `admin` rights - i.e. they trivially escalate themselves

> nobody else should have edit rights in the namespace except the SA itself

You do not control that.

> What should be the right approach to let Che create pods, services, pvcs and routes?

The safe way we have today is to have the SA go through an OAuth flow with the user to get a token for the user.  This allows safe delegation of privileges.  This is how Jenkins works today.

Otherwise you can ask the user to manually grant the Che SA `edit` rights to the namespace.  IIRC this is the approach OLM will take for the foreseeable future.

**Comment by l0rd** [comment]
> The linked YAML file grants admin to the SA. That is incorrect. It should have edit at most.

Agreed. Che is designed to require edit rights only. We should fix the yaml.

> The safe way we have today is to have the SA go through an OAuth flow with the user to get a token for the user. This allows safe delegation of privileges. This is how Jenkins works today.

This is what we are looking for! I had a look at Jenkins APB and [it looks like it creates a RoleBinding as we do](https://github.com/ansibleplaybookbundle/jenkins-apb/blob/master/roles/provision-jenkins-apb/tasks/main.yml#L116). Do you know if that flow is possible using an APB?

> Otherwise you can ask the user to manually grant the Che SA edit rights to the namespace.

The point of using an APB for us was to avoid manual steps :-/

**Comment by enj** [comment]
> This is what we are looking for! I had a look at Jenkins APB and it looks like it creates a RoleBinding as we do. Do you know if that flow is possible using an APB?

I am not familiar with the Jenkins APB.  The standard Jenkins template code is run by the user, so it has the correct access needed to set up Jenkins.

I do not see how any service broker could do an OAuth flow with the user (needs browser and user interaction).

> The point of using an APB for us was to avoid manual steps :-/

The same is true for OLM, but they will have to ask the user to do the RBAC steps manually.

**Comment by shawn-hurley** [comment]
> what I understand is that applications that require edit role cannot be fully provisioned with an APB (or OLM) but will always require a manual step.

This is not true, if the sandbox role is set to admin for the broker then the ASB could deploy this APB without a manual step.

**Comment by l0rd** [comment]
@shawn-hurley what I mean is that users that deploy Che (or another application that requires `edit` role at namespace scope) using an APB need to perform a manual step (e.g. setting the sandbox role to admin). Of course if the sandbox role has already been changed there is no manual step to do.

Anyway I prefer asking Che users to manually create the rolebinding rather than setting the ASB sandbox role to admin. Because it can be done even after Che provisioning and because it doesn't affect ASB security. 

@jwmatthews thank you. I am keen to learn more details about this new option.

**Comment by dymurray** [comment]
@l0rd I need to clarify something here. You keep saying Che only requires `edit` role. This is not true. Che requires `admin` role because you are creating RoleBindings in your deployment.

The point that has been made from our team is that you really do not need to be creating this RoleBinding to deploy Pods, Services, Routes, etc.

Is there an explicit need for you to be creating this RoleBinding from the APB? If there is then a solution can be found but I'm not convinced you need to be creating a RoleBinding if you say that you only need the `edit` role.

There should be no manual steps needed from the user if `edit` is sufficient.
