### ISSUE TITLE
Create how-to guide on speeding up the deployment of a large cluster

### ISSUE THREAD

**Issue by abutcher** [openshift/openshift-ansible#930]
This is a pretty common ask and I know that @detiber and @jeremyeder have a lot of experience increasing the performance of openshift-ansible tasks. Maybe this isn't the best place for a doc like this or maybe it could start here?

**Comment by detiber** [comment]
Some preliminary notes copied from a different discussion on the topic:

The ansible.cfg file I've been using for testing:
[defaults]
forks = 10
host_key_checking = False
remote_user = root
roles_path = roles/
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible/facts
fact_caching_timeout = 600

[privilege_escalation]
become = False

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
control_path = %(directory)s/%%h-%%r
pipelining = True

Some notes on the config:
For your use, I would ensure that forks is set to a number greater than the number of nodes you are deploying
pipelining will require either enabling the root user or disabling requiretty for the default user
Increasing the ControlPersist time and the fact_caching timeout will be needed to avoid having to gather facts multiple times and re-establishing ssh connections will not be needed.
I place the config in the root of the openshift-ansible checkout and invoke openshift-ansible directly...  when using bin/cluster, you may have to put it in the default location (/etc/ansible/ansible.cfg) and there may be tweaks needed to bin/cluster to avoid overriding some of the settings.
There is also a cache for the ec2 inventory, which will cause delays due to having to query the api between tasks...  you can modify the cache_max_age setting in inventory/aws/hosts/ec2.ini to increase the current setting of 300s, but you'll want to make sure to clear the cache between runs if you run into any issues (rm ~/.ansible/tmp/ansible-ec2.*)

**Comment by jeremyeder** [comment]
1) use ansible.cfg where forks > nodes (I never did try pipelining)
2) Pre-seed everything possible into your AMI/KVM image
  - In my case this was a full yum update, docker was pre-installed/thinLVM configured and I pre-cached my docker test images to each node
3) Ansible is extremely chatty over the wire.  There are tons of tcp sessions (ssh) and with everything done in parallel, this can mean a lot of work for the installer node.
  - Ensure you are running openshift-ansible from a machine on the local LAN as your cluster, to reduce latency associated with a WAN.  I have a dedicated jumpbox for this inside EC2.  Jumpbox also serves all yum content and is a docker-registry mirror.
4) Thundering herd of yum --  parallelizing ansible is good and bad.  I can't bake everything into the AMI because it will invalidate the test.  This means that each node does have to talk to yum at some point.

The herd of machines then caused I/O bottlenecks.  I added a dedicated EBS SSD (gp2 100G, so 300 IOPS) and that resolved that part.  I believe that on bare metal or a reasonably sized VM config, this might not have been necessary..  I then increased the amount of RAM to greater than my total repo content size (8GB was enough).  This is so I could serve most of yum out of page cache after the initial reads.  Then I found httpd limits; yum was unable to talk to my repos on the jumpbox.  I had to change the prefork config as so:

$ cat mpm_prefork.conf 
<IfModule mpm_prefork_module>
    ServerLimit          100
    StartServers         8
    MinSpareServers      8
    MaxSpareServers      32
    MaxClients           100
    MaxRequestsPerChild  2000
    MaxRequestWorkers    100
</IfModule>

Tagging instances may or may not be necessary based on your requirements.

This is the ansible.cfg that I used:

**Comment by jeremyeder** [comment]
@detiber could we do something in the installer that sets forks=node_count at runtime?

**Comment by jeremyeder** [comment]
Seems that RHEL6 doesn't support ControlPersist.

**Comment by detiber** [comment]
> @detiber could we do something in the installer that sets forks=node_count at runtime? 

That is one of the items we have on the installer roadmap (that said, we are looking at that for the packaged installer and not bin/cluster, but we could apply it to bin/cluster as well).

> ControlPersist was backported to RHEL6 in openssh-clients-5.3p1-96, which means RHEL6.6 or later which includes openssh-clients-5.3p1-104.el6.

Unless we override the default transport  (which is `smart`) The RHEL versions prior to 6.6 would fall back to paramiko. There will be a performance penalty compared to OpenSSH with ControlPersist, but not nearly as bad as OpenSSH without ControlPersist.

**Comment by detiber** [comment]
We should specifically call out the log_path when talking about ansible configuration: http://docs.ansible.com/ansible/intro_configuration.html#log-path

**Comment by rrati** [comment]
Should also provide guidance for what kind of system to run the installer on.  The number of forks may depend on not just the number of nodes, but also the size of the machine the installer is running on.  Some guidance about how to set one in relation to the other would be very helpful.

**Comment by jeremyeder** [comment]
https://docs.google.com/document/d/1Cy_UUtZ1kxQX1t7mJVjlb7PP7mrOSsmr0PiDZ2cRVtA/edit OpenShift Installer Tuning section

**Comment by xiaoping378** [comment]
maybe we should take a way to create a local yum repo

**Comment by jeremyeder** [comment]
Some of the methods we use for scale-out deployments are covered in a blog from last year

https://www.cncf.io/blog/2016/08/23/deploying-1000-nodes-of-openshift-on-the-cncf-cluster-part-1
