### ISSUE TITLE
playbook upgrade_control_plane.yml does not pre-pull docker image of control_plane

### ISSUE THREAD

**Issue by dabelenda** [openshift/openshift-ansible#9748]
#### Description

When running the playbook upgrade_control_plane.yml the docker image for control_plane is not updated.
I traced the whole playbook.
The pulling of the image is done in roles/openshift_control_plane/tasks/main.yml but these tasks are never used by the playbook. In place roles/openshift_control_plane/tasks/upgrade.yml is called but it does not pre-pull the image.

##### Version
```
* ansible version: `ansible 2.6.2`
* git describe: `openshift-ansible-3.10.35-1-10-gbfe7064`
```

##### Steps To Reproduce
1. install OKD 3.10
3. run upgrade playbook
4. see that the images are not updated and the action to pre-pull images is never called

##### Expected Results
The images should be pre-pulled during upgrade too.

##### Observed Results
The images are not pre-pulled during upgrade step.

##### Additional Information
This is a bit of an issue, since I am trying to force the update of the origin docker images during upgrade process but this pulling of the image is not called so I cannot set the "force" option in the docker_image action. I will have to use a master pre-config hook to pull the image as a work around.

**Comment by NilsKet** [comment]
I am having the same issue still (in my case with OSE 3.11) and I my guess is, that this is caused by the condition in `playbooks/openshift-master/private/roles/openshift_control_plane/tasks/pre_pull.yml`. It does the pull only `when: control_plane_image.stdout_lines == []` and this variable is populated by:

```- name: Check that origin image is present
  command: "{{ openshift_container_cli }} images -q {{ osm_image }}"
  register: control_plane_image
```
Leaving this condition to make sure the image is always pulled seems to be the obvious solution. Currently (for example) it is not updating from 3.11.43 to 3.11.51 because it is only checking if there is any 3.11 image available (which obviously is the case) and therefore not updating at all.

With the complexity of the ansible playbooks though I have no clue what removing the condition might brake in other stages (especially for disconnected installs?)
