### ISSUE TITLE
Allow addition of specific node without a entire rerun ansible installer script 

### ISSUE THREAD

**Issue by ivanthelad** [openshift/openshift-ansible#995]
-1 This takes too longs in a large cluster 
-2 introduces downtime in cluster 
-3 unnecessary restart and update of components which have nothing to with adding a node

**Comment by detiber** [comment]
The playbooks/byo/openshift-cluster/scaleup.yml playbook is meant to do just that. Any nodes in the new_nodes group will be configured, without configuring any other hosts in the cluster.

If not using a static inventory, a wrapper playbook around playbooks/common/openshift-cluster/scaleup.yml can be created to do the same.

**Comment by ivanthelad** [comment]
Thanks, Does this work currently(ose3.1) and have you a example config file?

**Comment by detiber** [comment]
Using the same inventory file that you installed with (assuming advanced install). You would simply add the new nodes under a section called new_nodes:

```
[new_nodes]
node-n.example.com <any variables you would have set for previous nodes>
```

You'll also want to add new_nodes under the [OSEv3:children] section.

After completing the run, you would want to move the new nodes to the [nodes] group.

There was a bug with the installer wrapper where it didn't correctly limit the node config to just new nodes, but that should be fixed in the next release.

If using one of the other provider playbooks, I would have to dig in a bit deeper to make suggestions, but there should be an AWS example either in master or in a PR.

**Comment by ivanthelad** [comment]
@detiber 
Shouldn't this be closed as its solved by the new variable "g_new_node_hosts"
 https://github.com/openshift/openshift-ansible/blob/b808eb073e53b0bd3910b75466ef32539a0250c9/playbooks/aws/openshift-cluster/scaleup.yml

**Comment by detiber** [comment]
@ivanthelad yes it should, thanks for bringing it to my attention.

@brenton please close

**Comment by jkroepke** [comment]
This feature should be documented.

**Comment by brenton** [comment]
@jkroepke, we should have a PR to openshift-docs for this within a week.

**Comment by detiber** [comment]
Bugzilla bug for documenting the scaleup playbook: https://bugzilla.redhat.com/show_bug.cgi?id=1304954
