### ISSUE TITLE
Bad use of oreg_url template in openshift_cluster_monitoring_operator

### ISSUE THREAD

**Issue by sjenning** [openshift/openshift-ansible#9987]
https://github.com/openshift/openshift-ansible/blob/master/roles/openshift_cluster_monitoring_operator/defaults/main.yml#L24-L33

Not sure what is happening here but it is bad.  Doesn't work with a `oreg_url` like `registry.reg-aws.openshift.com/openshift3/ose-${component}:v3.11`.  I know that in the normal case `${component}:${version}` is there, but you can't assume that.  It is templated for a reason.

What caused the deviation from established patterns here?

@elad661 @brancz @ironcladlou @sdodson

**Comment by brancz** [comment]
It’s because the component is inherited from coreos/Tectonic where versions were entirely managed by the higher level operator, but with the requirement of all openshift components being tagged with the openshift version instead of the components upstream version (eg. Prometheus v2.3.1 is tagged with the OpenShift version v3.11 instead). At the same time people were just able to specify a “baseImage” or repository in case the image in question comes from a customer’s private registry. We assumed that the openshift version was the canonical source of tags since all our PRs were merged (as a side note, why is it not?). We can rethink the current handling but that would jeopardize code freeze, if you think the case you shared is the only one we need to handle, then we can adapt the regex that just removed “:${version}” to an operation that removes everything from and including the last colon “:”.

**Comment by sdodson** [comment]
I'd split the string replacement into two parts. Replace ose-${component} and then replace ${version}. That way if ${version} doesn't exist in the format string we still properly replace the component, if it does exist we replace version too as expected.

Does that work for both cases?

**Comment by brancz** [comment]
We wouldn't use the latest tag. Tags are still being set, but they are owned by the cluster-monitoring-operator, and (currently) configured through the `openshift_image_tag` variable in ansible. I'm expecting this API to somewhat change for 4.0, but for 3.11 I'd like to just get it to work correctly.

**Comment by sjenning** [comment]
#9998 does not fix this.  With `oreg_url` of `registry.reg-aws.openshift.com/openshift3/ose-${component}:v3.11`, the image path becomes `image: registry.reg-aws.openshift.com/openshift3/ose-prometheus-operator:v3.11:v3.11`

**Comment by michaelgugino** [comment]
Something has gone amiss here and there's a way to handle this type of thing already in other parts of the installer.

**Comment by michaelgugino** [comment]
Okay, I have an idea of what's going on now.

You need something that looks like 'hostname.com/project/ose-component' and no version information.  Latest patch looks to provide that (though some comments in the ansible code would be nice).
